### ISSUE TITLE
(persist): discussion around improving peristence

### ISSUE THREAD

**Issue by rt2zz** [redux-offline/redux-offline#1]
Love the api so far,

One shortcoming to the `createOfflineStore` setup (higher order store creator? 🥇) is that it is not obvious how to achieve more complex persistence patterns. e.g. the most common one of storing some state in session storage and other in localstorage.

Off the top of my head here are a few related ideas:

1. Consider having persist config be an array of configs, generate one persistor per config
2. Consider reimplementing redux-persist
    - make config a nested structure, recurse down the tree persisting things according to their config
    - this could open up some interesting api options like colocating persistence config with each reducer
3. single key persistence
    - serialize each slice of the state (time throttled a la redux-persist)
    - but do not write this state to disk immediately
    - wait until all queued updates are serialized and then write all serialized chunks into one storage key

3 is I think particularly exciting because with redux-offline the consistency of the stored data is paramount - and single state writes will be more likely to be consistent. Additionally it could unlock options like storing an incremental actions with periodic compaction.

Just thoughts for now...

**Comment by jevakallio** [comment]
@rt2zz thanks for these thoughts! 

I'm going to focus my unfortunately limited time the next few days on bugfixes and few core quality issues, but have some thoughts about how to make this happen and aim to push a larger release with better persistence support on the weekend or soon after.
