### ISSUE TITLE
thoughts on switching to typescript?

### ISSUE THREAD

**Issue by bsouthga** [redux-offline/redux-offline#10]
Probably a contentious suggestion, but I've found the tooling around typescript to be a little easier to maintain. I'd be happy to create a PR mapping the existing types / setup to typescript as well.

Also totally understand if many people feel that is too far of a leap.

**Comment by wacii** [comment]
I don't mind either way.

**Comment by sorodrigo** [comment]
I prefer to maintain this lib on js. I'm not a big fan of the type systems myself but I don't mind using flow given that the original repo used it and this way we don't deviate that much. Still, open to other opinions.

**Comment by bsouthga** [comment]
Yeah I think leaving as is makes sense
