### ISSUE TITLE
babel plugin dependencies when using react-native

### ISSUE THREAD

**Issue by benvp** [redux-offline/redux-offline#10]
Hey, first: thanks for this library, just came around this library because I have a project which will need proper offline handling. Was about to implement my own solution, but decided to give this one a try. Looks very promising!

However, when I add the dependency using `yarn add redux-offline` and import the `createOfflineStore`method, it seems that their is an issue with the babel plugins.

![image](https://cloud.githubusercontent.com/assets/981344/24425157/62f70a14-1403-11e7-90c8-2192f9cb272f.png)

Any ideas how to fix this?

**Comment by GertjanReynaert** [comment]
As a quickfix i think that removing the babelrc file from `node_modules/redux-offline` can help you out

**Comment by benvp** [comment]
Thanks for the quick help - I did a short install of the devDependencies as a work-around. But deleting the babelrc should also work. :)

**Comment by jevakallio** [comment]
@benlime thanks for spotting this! When I was developing the library, I used [Whackage](https://github.com/formidablelabs/whackage) to work against it, and that hid this error.

This is basically the same age old issue as https://github.com/gaearon/redux-thunk/issues/43

Will be pushing a fix shortly.

**Comment by jevakallio** [comment]
@benlime @GertjanReynaert :tada: I've just published [v1.0.2](https://github.com/jevakallio/redux-offline/releases/tag/v1.0.2) that fixes this.

Thank you for submitting the issue. Here's an early adopter taco for you 🌮
