### ISSUE TITLE
How to handle retries with cancellation?

### ISSUE THREAD

**Issue by tarr11** [redux-offline/redux-offline#111]
I'm looking at using this library for a "code editor".  My code editor periodically saves to the server based on an interval.  

Let's say we go offline and the user continues working.  There will then queue up multiple requests to save, but in reality, I want to discard all of them except for the last one.  

Is there some way to accomplish this with redux-offline?

**Comment by sorodrigo** [comment]
Hey! There's a new feature incoming that will allow you to achieve this. More info here #65 . I'll close  this one. 👍
