### ISSUE TITLE
How to get effect value for commits and rollbacks?

### ISSUE THREAD

**Issue by doniyor2109** [redux-offline/redux-offline#113]
When redux-offline successfully saves data to server, `commit` event is fired. 
Is it possible to pass response value from `effect`  event, to `commit`'s meta?

**Comment by doniyor2109** [comment]
I have looked in source code and it is possible. Redux offline passes response as payload field in action.

**Comment by sorodrigo** [comment]
Closing as it seems this issue needn't answer.
