### ISSUE TITLE
Get a grip on the 'offline' reducer

### ISSUE THREAD

**Issue by clems36** [redux-offline/redux-offline#115]
I think it would be amazing to be able to have hands on the offline reducer and modify it.
Imagine you have 10 times the same request in the outbox, when you get your connection back you would only want one of them to execute, not all 10...

Is there any proper way to achieve this right now ?
The only way I can think of is by affecting a new value directly to the reducer, which works but is completely anti-pattern. (something like `this.props.offline.outbox = [...];` (WE SHOULD NEVER HAVE TO DO THIS)).
Seems essential to me! 
Cheers

**Comment by dstudzinski** [comment]
I had similar problem. I wanted to just send last version of edited document - not all edits.
I think I found solution which is not based on antipatterns :).

You have to create reducer enhancer: 
[https://github.com/reactjs/redux/blob/master/docs/recipes/ImplementingUndoHistory.md#meet-reducer-enhancers](https://github.com/reactjs/redux/blob/master/docs/recipes/ImplementingUndoHistory.md#meet-reducer-enhancers)

```
const enhanceOffline = reducer => {
  // take original reducer and return new one:
  return function(state, action) {
    switch (action.type) {
      case REMOVE_EXISTING_DOC_EDITS_FROM_OUTBOX:
        const docId = action.payload;
        const outbox = [];

        state.offline.outbox.forEach(el => {
          if (el.type === EDIT_DOCUMENT && el.payload._id === docId) {
            // nothing - drop this doc (or do something else with it and push to outbox)
          } else {
            outbox.push(el);
          }
        });

        return { ...state, offline: { ...state.offline, outbox } };
      default:
        // just proxy all other actions
        return reducer(state, action);
    }
  };
};
```

Then wrap reducer returned from offline enhancer:
```
compose(
  applyMiddleware(middleware),
  offline(offlineConfig),
  createStore => (reducer, preloadedState, enhancer) =>
          enhancer(createStore)(enhanceOffline(reducer), preloadedState)
)
```
I took this function:
```
createStore => (reducer, preloadedState, enhancer) =>
          enhancer(createStore)(reducer, preloadedState)
```
from this issue: [https://github.com/zalmoxisus/redux-devtools-extension/issues/365](https://github.com/zalmoxisus/redux-devtools-extension/issues/365)
it solves this https://github.com/redux-offline-team/redux-offline/issues/57 bug with Redux DevTools BTW

NOTE: after merging this changes: [https://github.com/redux-offline/redux-offline/pull/26/commits/bf61d564bd5ff26c4757313c7886650e28be537d](https://github.com/redux-offline/redux-offline/pull/26/commits/bf61d564bd5ff26c4757313c7886650e28be537d) it will be easier. just:

```
enhanceOffline(enhanceReducer(rootReducer))
```

**Comment by clems36** [comment]
Thanks for your answer! I'll try to implement this and come back here as soon as possible.

**Comment by sorodrigo** [comment]
There's a new feature targeting this. More info here #65 .
