### ISSUE TITLE
Custom https headers for offline request

### ISSUE THREAD

**Issue by yortuc** [redux-offline/redux-offline#116]
Hi,

i cannot see in the documentation, but my api needs some special http headers per request.
Bu it seems like its not possible to define http headers for offline request paths, am i right?

thanks.

**Comment by yortuc** [comment]
it's possible, my bad, i did not check the source code.

**Comment by seismicsix** [comment]
Hi - could you shed light on how you did this please?

**Comment by PaulBrachmann** [comment]
@seismicsix You can implement a custom ```effect``` method. It is called whenever redux-offline tries to deliver a request to your backend. Writing it on your own enables you to make API requests in whatever form you please.  
For more information, see the ["Change how network requests are made"](https://github.com/jevakallio/redux-offline#change-how-network-requests-are-made) section of the README.

**Comment by seismicsix** [comment]
thanks for the reply...

looking at the source - I can also see I can add the headers in my action file too:
```
export const fetchFiles = () => {
  return {
    type: FILES_FETCH_ALL,
    payload: [],
    meta: {
      offline: {
        // the network action to execute:
        effect: { url: `${ROOT_URL}/files`, 
          method: 'GET',
          headers: {
           'X-Requested-With': 'XMLHttpRequest',
          }
        },
        // action to dispatch when effect succeeds:
        // commit: { type: FILES_FETCH_ALL_COMMIT },
      }
    }
  }
}
```
posting here for others to see 👍
