### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by Xyzor** [redux-offline/redux-offline#118]
Hello!

Is it possible to add a working example?

I created a project, based on the readme, but it keeps retrying to send the request.

"Retrying action ... with delay ..."

**Comment by tomsowerby** [comment]
If you're using Apollo client, then I have found https://github.com/ReggaePanda/redux-offline-examples to be excellent.

**Comment by PaulBrachmann** [comment]
@Xyzor To me, it sounds like your backend can't be reached. Have you checked requests are coming through? The ["Change how network requests are made"](https://github.com/jevakallio/redux-offline#change-how-network-requests-are-made) section might help.

In case you are using the Apollo client, you may also want to take a look at [apollo-offline](https://github.com/Malpaux/apollo-offline). It is based on redux-offline and designed from the ground up to enable a seamless Apollo integration.  
(Full disclaimer: I'm the maintainer of the project. - Feedback is highly appreciated!)

@tomsowerby I recently created a simple example using it. You can find its repo here: [apollo-offline-examples](https://github.com/Malpaux/apollo-offline-examples).  
There still is much room for improvement, but I hope it demonstrates the basic techniques.

**Comment by Xyzor** [comment]
First of all, thanks for the suggestions.

I'm not using apollo. If I'm correct it only works with GrapQL, but what I need is what redux-offline does. Send the failed action's payload to the server.

@MLPXBrachmann Sorry, my description was poor. I tested the url and it was reachable, and i overwrite the effect function with a tested fetch code.

**Comment by PaulBrachmann** [comment]
@Xyzor Yes, Apollo is a GraphQL-only client.  
However, the repo @tomsowerby mentioned also contains [an example using just Redux](https://github.com/ReggaePanda/redux-offline-examples/tree/master/simple-web). Have you taken a look at that one?

**Comment by Xyzor** [comment]
@MLPXBrachmann  Yes i saw that. Right now I'm working on a dumb counter app to make redux-offline work, using that example.

**Comment by Xyzor** [comment]
I feel so stupid right now  :cry:

As I said, I tested the url...on the computer and as you would expect the http://localhost/tmp.php is shown in the browser.
From the mobile device, not so much. :smile:

@tomsowerby Thanks for the example.

I created a repo, if someone need an another example next to the others.
https://github.com/Xyzor/react-native-redux-offline-example

**Comment by tomsowerby** [comment]
@Xyzor No worries. Glad that you got it working.

**Comment by Theng** [comment]
@Xyzor , thanks for your example, but when I try to use it with axios I don't get rollback when request error. Ex: Error status 422.
Can you help me if I does anything wrong somewhere. 

I better mention @sorodrigo too.
Thanks you.
```
const reduxOfflineConfig = {
  ...offlineConfig,
  effect: (effect, action) => {
    return axios({
      method:effect.method,
      url:effect.url,
      body: effect.body
    })
      .then(function(response) {
      return response
    }).catch((error) => {
      return Promise.reject(error);
    });
  }
}
```

**Comment by wacii** [comment]
@Theng I would suggest reading the default discard function. It's only a few lines of code.

But the problem is that the default discard function expects `status` to be defined on `error`. Instead of trying to tailor your custom `effect` to work with the default `discard`, it is generally easier to just write your own `discard`.

**Comment by Theng** [comment]
@wacii , thanks you so much I will read and learn more about it.
