### ISSUE TITLE
detectNetwork change listener fires before initial fetch returns

### ISSUE THREAD

**Issue by BradRyan** [redux-offline/redux-offline#120]
Took me a bit to figure out what was going on... state.offline.online was being set to false even though `NetInfo.isConnected.fetch()` would return isConnected = true.  The problem is in `detectNetwork.native.js`, where NetInfo.isConnected change listener would return before the initial NetInfo.isConnected.fetch() would return.

Apparently when I refresh my iOS simulator it would initially read offline, but quickly change to online.  The change would trigger the event listener code before the initial offline reading came back from the fetch, causing the state to be set to offline even when it was online.  Not sure if anyone else experiences this... seems like a recent development for me.  Anyways, the below change to `detectNetwork.native.js` fixes it.

Current:
```
NetInfo.isConnected.addEventListener('change', updateState);
NetInfo.isConnected.fetch().then(updateState);
```

Fixed:
```
NetInfo.isConnected.fetch().then((isConnected) => {
  updateState(isConnected);
  NetInfo.isConnected.addEventListener('change', updateState);
});
```

**Comment by peterleilei86** [comment]
Hey @BradRyan, I am having the similar issue. I am wondering which version of react native are you using? I am using 0.46 and the issue I am having is that __*Offline/STATUS_CHANGED*__ is not triggered when I switch from offline to online. And __*Offline/STATUS_CHANGED*__ gets triggered twice when i first load my app. I am not sure if this is because of the react native NetInfo module issue.

**Comment by BradRyan** [comment]
@peterdev6 I'm using ReactNative 0.48.  I also notice that my status doesn't update when I switch from offline to online when I use the iOS simulator (turning my mac wifi off and on).  It's fine when I switch from offline to online when running on my iPhone though (toggling airplane mode).

If there's something else I can check that you'd think would help diagnose let me know!

**Comment by peterleilei86** [comment]
@BradRyan Thanks for your reply. I may try to upgrade to rn 0.48.
I dont know if there is something wrong with my implementation of redux-offline. I used this workaround(https://github.com/jevakallio/redux-offline/issues/77#issuecomment-301096942) to add redux-logger middleware. 

Are you using redux-logger or redux-dev-tools?

**Comment by BradRyan** [comment]
I am using redux-logger.  I didn't run into a problem implementing it, but from the looks of it I'm not getting the redux-offline events logged in the approach I did.  Thanks for sharing that I may change the approach I used to apply middleware per you shared workaround.

I don't know that upgrading will help since it sounds like I'm experiencing the same problems on 0.48.

**Comment by Jobeso** [comment]
I got the same problem on RN 0.48 so that is not the solution.

**Comment by sorodrigo** [comment]
Hey guys! Some of the issues you’re facing have been dealt with in the community fork we’re maintaining. We now have access to this repo and will be merging them together shortly. Hopefully in these coming days.

**Comment by sorodrigo** [comment]
New version addresses this issue. ✌️
