### ISSUE TITLE
Implementing manual sync

### ISSUE THREAD

**Issue by kbrandwijk** [redux-offline/redux-offline#121]
I want to use `redux-offline` to implement a manual sync feature in my app. I thought about overriding `config.detectNetwork` and manually return true to trigger the updating.

The only issue I'm facing is that I want to detect when the app is busy syncing. Any pointers on how to implement that part? Ideally I'm looking for a way to detect that the sync is complete.

**Comment by sorodrigo** [comment]
The offline state contains a prop `busy` try using that one.

**Comment by kbrandwijk** [comment]
Thanks, got it figured out (mostly) in https://github.com/redux-offline/redux-offline/issues/25
