### ISSUE TITLE
New release upcoming?

### ISSUE THREAD

**Issue by CaryLandholt** [redux-offline/redux-offline#126]
Firstly, thanks very much for this project.  Has been invaluable.

When can we expect a new release?  Thanks!

**Comment by sebasgarcep** [comment]
Hey, the project is currently unmantained as @jevakallio is unavailable. We at https://github.com/redux-offline/redux-offline are currently working on it. You might want to check on its progress!

**Comment by ghost** [comment]
What it means: "@jevakallio is unavailable"? Is he active on other projects? Why he abandoned this one?

**Comment by elf-pavlik** [comment]
Please see: https://github.com/redux-offline-team/redux-offline/issues/117#issuecomment-333851443

**Comment by ghost** [comment]
Thanks @elf-pavlik. Can we close this now?

**Comment by CaryLandholt** [comment]
Thanks @johnunclesam
