### ISSUE TITLE
"Error restoring state" for large datasets

### ISSUE THREAD

**Issue by thalesgaldino** [redux-offline/redux-offline#127]
First of all, thanks for such a great module!

I'm having similar situation as described [here](https://github.com/rt2zz/redux-persist/issues/199). I wonder if anyone has been through this. I have tried [this solution](https://github.com/robwalkerco/redux-persist-filesystem-storage) but it has made the App really slow and getting stuck when restarting/rehydrating. Please let me know there's a workaround for this, will be very appreciated!

**Comment by wacii** [comment]
Closing as unrelated to Redux Offline. If you feel Redux Offline is contributing to the problem, feel free to reopen. We could maybe limit the number of stored unresolved offline actions if that becomes a issue.
