### ISSUE TITLE
Action not being triggered

### ISSUE THREAD

**Issue by connercms** [redux-offline/redux-offline#129]
I am just beginning to implement this library. I am fairly new to redux also, so it may be as simple as an error with how I am creating my store. I get this warning on store rehydration

>       redux-persist/autoRehydrate: 1 actions were fired before rehydration completed. This can be a symptom of a race
>       condition where the rehydrate action may overwrite the previously affected state. Consider running these actions
>       after rehydration:
>      [Object]0: Objectpayload: Objecttype: "Offline/STATUS_CHANGED"__proto__: Objectlength: 1__proto__: Array(0)

My store creation code is 

```
const store = createStore(
  reducers,
  compose(
    applyMiddleware(thunk),
    offline(offlineConfig),
    autoRehydrate({ log: true }),
    window.devToolsExtension ? window.devToolsExtension() : f => f
  )
)
```

And my action looks like
```
export const submitCallLog = (dispatchId, callLog) => (dispatch, getState) => ({
  type: "SUBMIT_CALL_LOG",
  payload: { dispatchId, callLog },
  meta: {
    offline: {
      effect: {
        url: urls.SAVE_CALL_LOGS,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
          "Cache-Control": "no-cache",
          Authorization: "Token " + getState().auth.serverToken
        },
        body: JSON.stringify({
          call_logs: callLog
        })
      },
      commit: { type: "CALL_LOG_SUBMIT_SUCCESS" },
      rollback: { type: "CALL_LOG_SUBMIT_FAILURE" }
    }
  }
})

```

However, when I call submitCallLog, I no longer see any action has been dispatched in the dev tools, and nothing seems to happen. Have I done something wrong to set this up?

**Comment by wacii** [comment]
Redux Offline calls `autoRehydrate()` for you.

**Comment by wacii** [comment]
Also the library doesn't work with devtools yet. This has been fixed, just not released yet.

And while not related to the library, `window.devToolsExtension` doesn't look right.

**Comment by connercms** [comment]
It was an issue with not calling dispatch on the action object. I also had to remove dev tools in store creation to get it to work.

```
dispatch({
    type: ...
    payload: { ... }
})
```
