### ISSUE TITLE
Cannot rehydrate undoable reducers created using redux-undo

### ISSUE THREAD

**Issue by raynor85** [redux-offline/redux-offline#131]
After enhancing an existing reducer with undoable from redux-undo, I noticed that the action 'persist/REHYDRATE' dispatched from redux-offline doesn't restore the changes for the enhanced undoable reducer, even if I manually dispatch the action any time during the app execution.
Related to https://github.com/omnidan/redux-undo/issues/187

**Comment by wacii** [comment]
I took a look at the linked thread and you seemed to have found your answer, so I'm going to close this.
