### ISSUE TITLE
Difference to redux-offline?

### ISSUE THREAD

**Issue by jaulz** [redux-offline/redux-offline#14]
How do we use this fork? Are there any significant differences? I tried to simply replace the imports:
```
import { offline } from '@redux-offline/redux-offline';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults';
```

However, if I just do this the application constantly shows me that it's offline. Any clue what could have gone wrong?

Thanks in advance!

**Comment by sorodrigo** [comment]
Hello! For using this library replacing the imports will do the trick. In what platform are you using redux-offline?

**Comment by jaulz** [comment]
I use it as part of a react-native(-web) project. Do you think a custom network detector is necessary?

**Comment by sorodrigo** [comment]
For web the default config works, for `react-native` projects you'll need to import the `defaults/detectNetwork.native` file instead.

**Comment by jaulz** [comment]
Please check https://github.com/redux-offline/redux-offline/pull/20 and merge if you are fine with it.
It seems there was an regression due to the introduction of netinfo from React Native.
