### ISSUE TITLE
Redux Offline uses Rehydrate even the App is online

### ISSUE THREAD

**Issue by marcusviniciusf** [redux-offline/redux-offline#140]
Hi everyone, I've a problem here. I'm new at redux-offline.
The problem is: after the first action dispatch success (commit, rollback and the main type), the next time i reload the app, even if I'm online, he uses the persist store. I've read all the api config, and the examples, issues on the git, but nothing. Here is the code:
```
dispatch({ 
    type: FETCH_JOGOS, 
    payload: jogos, campeonatos,
    meta: {
      offline: {
        effect: { url: URL, method: 'GET' },
        commit: { type: FETCH_JOGOS_COMMIT },
        rollback: { type: FETCH_JOGOS_ROLLBACK },
      }
    }
  });
```
![captura de tela 2017-11-14 as 11 35 47](https://user-images.githubusercontent.com/17880908/32782908-1e65b8c6-c931-11e7-9cc2-ae34e973df12.png)
the store config: 
```
const store = createStore(
  reducers,
  {},
  compose(
    applyMiddleware(reduxThunk),
    offline(offlineConfig)
  )
);
```

**Comment by wacii** [comment]
So the action is being persisted across sessions, even after it was successfully resolved during the first session?
