### ISSUE TITLE
TypeError: _effect is not a function

### ISSUE THREAD

**Issue by darioielardi** [redux-offline/redux-offline#141]
I'm testing an offline-first implementation with this awesome library and feathersjs.

My basic test-store is like:
```
import { createStore, applyMiddleware, combineReducers, compose } from 'redux'
import { offline } from '@redux-offline/redux-offline'
import offlineConfig from '@redux-offline/redux-offline/lib/defaults'
import client from './feathers'

const config = {
  ...offlineConfig,
  effect: (effect, action) => {
    console.log('EFFECT: ', effect)
    console.log('ACTION: ', action)
    return effect()
  }
}

const ADD_TODO = 'ADD_TODO'
const SET_TODOS = 'SET_TODOS'

export const loadTodos = todos => ({
  type: SET_TODOS,
  payload: todos
})

export const addTodo = todo => ({
  payload: todo,
  type: ADD_TODO,
  meta: {
    offline: {
      effect: () => client.service('todos').create(todo)
    }
  }
})

const todoReducer = (state = [], action) => {
  switch (action.type) {
    case SET_TODOS:
      return action.payload
    case ADD_TODO:
      return [...state, action.payload]
    default:
      return state
  }
}

const reducer = combineReducers({
  todos: todoReducer
})

const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose

const Store = createStore(
  reducer, 
  {}, 
  composeEnhancers(
    applyMiddleware(), 
    offline(config)
  )
)

export default Store
```

client.service('todos').create(todo) returns a Promise, and in fact when my app is online everything was fine, the effect was executed. When my app is offline a todo is added to the store and the effect is enqueued, and if I go back online without refresh the page everything works. But if in the meantime I refresh the page, the 'offline' branch store is rehydrated but the 'offline' meta field of the action is empty, like so.

![capture](https://user-images.githubusercontent.com/19256200/32840608-70a98846-ca18-11e7-90d0-e6d5756daa6a.PNG)

causing this error:

![capture](https://user-images.githubusercontent.com/19256200/32840652-9529c3f2-ca18-11e7-8299-c99cd48b48e1.PNG)

I can't figure out the problem, any suggestion?

**UPDATE**
I tried to remove redux devtools, but still not works.

**Comment by wacii** [comment]
Functions are not serializable. There is no way to save them between sessions, so this will never work through a refresh. This is why the default is to explain requests as objects.

**Comment by darioielardi** [comment]
ok thanks, can be closed.
