### ISSUE TITLE
REHYDRATE action takes a lot

### ISSUE THREAD

**Issue by jlramosr** [redux-offline/redux-offline#149]
Hello,
I use redux-offline to handle the connection state of my app and persist with my localstorage. When I start my app, it executes actions defined by me before _Offline/STATUS_CHANGED_ and _persist/REHYDRATE_. This is a problem with me because REHYDRATE kills the previous state modified by my actions. 

![2017-11-30_16h41_16](https://user-images.githubusercontent.com/6153618/33439312-6e292f14-d5ed-11e7-9465-82807a4321f9.png)

Is there any possibility REHYDRATE action executes first of all?

**Comment by wacii** [comment]
Redux Persist, which is responsible for emitting `persist/REHYDRATE`, saves actions dispatched before it, and replays them onto the state. So it makes an attempt to address this problem by default. You can read about it [here](https://github.com/rt2zz/redux-persist/tree/v4#autorehydrateconfig).

**Comment by rt2zz** [comment]
actually it does not automatically replay them. If you want that you might consider redux-action-buffer

**but** there can be some complexity with buffering action, I suggest holding off on doing any fetching / actions until rehydration is complete. For most apps that should only be a few ms

**Comment by kristfal** [comment]
The recommended approach is to 'gate' your app, so it initializes after Rehydration is complete. 

Let's say you do user authentication, and need to check if the user is logged in or not before moving to the correct screen:

1) In your offlineConfig, have `persistCallback` call an auth function
2) Your auth function checks the store, and then dispatches a navigation action depending on your store condition. Here is an example:

```js
import {NavigationActions} from 'react-navigation';

import store from '../reducers';
import {getLoginStatus} from '../reducers/auth';

export const resetToSignedOutAction = NavigationActions.reset({
  index: 0,
  key: null,
  actions: [NavigationActions.navigate({routeName: 'SignedOut'})],
});

export const resetToSignedInAction = NavigationActions.reset({
  index: 0,
  key: null,
  actions: [NavigationActions.navigate({routeName: 'SignedIn'})],
});

export default () => {
  const isLoggedIn = getLoginStatus(store.getState());
  return isLoggedIn
    ? store.dispatch(resetToSignedInAction)
    : store.dispatch(resetToSignedOutAction);
};
```

In the case above, the default function is used as the `persistCallback` in the offline config.
