### ISSUE TITLE
Documentation for effect is outdated and unclear

### ISSUE THREAD

**Issue by kbrandwijk** [redux-offline/redux-offline#150]
Trying to find out the inner workings of `effect`, and how to achieve the desired behavior with my own effect (unreachable, 40x, 50x), I found out that the documentation about the 'paper thin wrapper around fetch' is outdated, and that the source code for the default effect actually reveals the type of error that I need to return to achieve that behavior: 

https://github.com/redux-offline/redux-offline/blob/39aa110e98c03f71bff750e9854a17ae8b9b0776/src/defaults/effect.js#L6-L10

It might be helpful if the documentation explained that part of the concept better.

**Comment by kbrandwijk** [comment]
For example, it took me a couple of hours to find out why the standard `discard` didn't work, even though I returned a `NetworkError` with the correct status. Turns out that `discard` swallowed a `TypeError`, because I did `import { NetworkError } from '@redux-offline/redux-offline'` instead of `import { NetworkError } from '@redux-offline/redux-offline/lib/defaults/effect'` in my effect.

**Comment by sorodrigo** [comment]
Thanks for pointing this out, we should improve the docs.
