### ISSUE TITLE
on app kill action must not reset

### ISSUE THREAD

**Issue by patilrevansidh** [redux-offline/redux-offline#151]
I want to use write sync in offline mode. once I close the app (kill app) then transactions or actions that wherein queued during no internet scenario get reset.(during offlinemode)
Suppose I made 2 post and there where no internet those actions get queued in outbox. but on app close outbox reset to 0 and no action of the post in background 
Does this lib support offline write in case of app close?

**Comment by sorodrigo** [comment]
I think this can be done by adding a listener on the AppState and dispatching the RESET_STATE action: https://github.com/redux-offline/redux-offline#empty-the-outbox

**Comment by patilrevansidh** [comment]
thank you for your reply. I can you elaborate.
From where I need to dispatch ? from every action? can you please provide like to code?

**Comment by patilrevansidh** [comment]
Thank you for your reply @sorodrigo  Actually I don't want to reset action. It's my mistake title was not clear.
I want to dispatch action those where performed in offline and pending must be dispatch after app kill or after reopening of app

**Comment by sorodrigo** [comment]
Are you reseting the outbox somewhere else in your code? The outbox gets persisted and unless you're clearing it, it should resume after the app is re-opened and the status is online.

**Comment by patilrevansidh** [comment]
I don't think so. Here is my simple action:
```

export  const decrementAction = () =>{
    const effectReconciler=()=>{
        return operationService.doOperation({type:'decrement'});
    }

    const commit = {
         type:DECR_SUCCESS
    }

    const rollback = {
        type: DECR_FAIL
    }

    return {
        type: DECREMENTING,
        meta: {
            offline: {
                effect: effectReconciler(),
                commit,
                rollback
            }
        }
    }
}

```
![actionpayload](https://user-images.githubusercontent.com/11453641/33715272-f8f9ed74-db77-11e7-8173-ecd9ebb7fcb4.png)

You can see here in action payload there is action queued but not in store. is there any way to dispatch such actions ? if you have any code sample then please let me know for better understanding

**Comment by sorodrigo** [comment]
It might have something to do with your custom effect config.
Could you provide a live code example? https://codesandbox.io/s/8xml9l1r0j

**Comment by patilrevansidh** [comment]
Yes sure, here it is [https://r4pvmw776m.codesandbox.io/](url)
I mentioned only imp files, not UI things

**Comment by wacii** [comment]
The provided code includes Redux Persist v5 as a dependency. Redux Offline still uses v4.

Does `apiCall.doOperation({ type: "decrement" })` / `operationService.doOperation({type:'decrement'})` return an object? This needs to be serializable.

Redux Offline should save requests between sessions. So this should be working.

**Comment by patilrevansidh** [comment]
hey @wacii 
`
    "redux-offline": "^2.0.0",
    "redux-persist": "^4.10.1",`

I think version 5 was added by sandbox actually I use above, copied directly from package.json
and `operationService.doOperation({type:'decrement'})`  return promise

I think it shows pending transaction in action when Rehydrate but  in next state, logger shows  outbox pending and transaction empty is there any way to handle this

**Comment by realprabs** [comment]
I am facing the same issue. Offline status is persisted properly. "persist/REHYDRATE" action has expected payload including offline state. After rehydrate, outbox turns 0.

**Comment by wacii** [comment]
@patilrevansidh `operationService.doOperation({type:'decrement'})` shouldn't return a promise. It needs to return an object describing the request. The effect reconciler uses this to make the request.

So that is a problem. Doesn't necessarily explain why your outbox is zero though. The promises aren't serializable so they won't last across sessions, but I would expect the actions to.

**Comment by patilrevansidh** [comment]
this is my **store** : 
 ```
import { applyMiddleware, createStore, compose } from 'redux';
import { offline,createOfflineStore} from 'redux-offline';
import offlineConfig from 'redux-offline/lib/defaults';
import reducer from './reducer';
import logger from 'redux-logger';
import thunk from 'redux-thunk';
import {AsyncStorage} from 'react-native';
import batch from 'redux-offline/lib/defaults/batch';
import retry from 'redux-offline/lib/defaults/retry';
import discard from 'redux-offline/lib/defaults/discard';
import {persistStore, autoRehydrate} from 'redux-persist';
import { createNetworkMiddleware } from 'react-native-offline';




const myConfig = {
    ...offlineConfig,
    effect: (effect, action) => sendData(effect, action),
    persistOptions: {
        storage: AsyncStorage,
        blacklist : ['nav']
    },
};

const networkMiddleware = createNetworkMiddleware();


const configureStore = () => {
    const store = createStore(
        reducer,
        compose(
            applyMiddleware(thunk, logger),
            offline(myConfig),
            autoRehydrate()
        )
    );

    persistStore(store, {storage: AsyncStorage,blacklist:['nav']});
    return store;
}


function sendData (effect, action) {
    console.log(action,"config")
    const promise = new Promise((resolve, reject) => {
        let options = {
            method :"post" //effect.method
        };
        
        options.headers = new Headers();
        options.headers.append('Content-Type', 'application/json');
        options.body = effect.body;
        // console.log(effect,"config")
        fetch("url", options)
        .then((response) => {
            console.log(response)
            const value = JSON.parse(response._bodyInit).value
            // console.log("value",value)
           resolve({number:value})
        }).catch((message)=> {
            reject(message);
        }); 
    });
    return promise;
}

export default configureStore;
```
here is **action** 
```
export  const decrementAction = (number) =>{
    return async (dispatch)=>{
        dispatch({type: DECREMENTING,
            
                meta: {
                    offline: {
                        effect:{body:JSON.stringify({type:"decrement",number})},     //effectReconciler({type:"decrement",number}),
                        commit: { type:DECR_SUCCESS,meta:{number:number}},
                        rollback:{type:DECR_FAIL,meta:{}}
                    }
                }
            }
        )
    }
}

```
these are changes what I made know. Please let me know whether I'm doing right or wrong

**Comment by wacii** [comment]
You don't need to set up Redux Persist. Redux Offline will do that for you.

Your effects reconciler doesn't react properly to responses with a status of 5xx.

Are you still having a problem with the outbox being set to zero?

**Comment by patilrevansidh** [comment]
@wacii  thank you.

**Comment by vishvasNagpal** [comment]
i am facing the same problem. after app kill when you reopen the app the `outbox` is set to 0

**Comment by mojodev** [comment]
this issue still exist in 2.4.0. any one got solution for this issue ?

**Comment by DianaLaa** [comment]
I wanted to report back that I faced this issue using `redux-persist` v5 and the issue disappeared when using v4 (as shipped with `redux-offline`)

I do not have a simple code sample, but the scenario is as descibed: 

- Open your app and ensure you are in a situation where redux-offline thinks you're offline
- Do something that results in an action that requires online access (API call)
- Kill the app
- Open the app again and go online
- The action that was previously done, does not get executed by redux-offline
