### ISSUE TITLE
Workbox vs Redux-offline for PWAs

### ISSUE THREAD

**Issue by johnkorzhuk** [redux-offline/redux-offline#156]
I'd like some help understanding the differences between using [Workbox](https://developers.google.com/web/tools/workbox/) vs Redux-offline for dynamic data caching in a progressive web app and the implications of picking one over the other.

From reading the Redux-offline documentation, Redux-offline doesn't use service-worker's fetch event to cache dynamic data, but similar to Workbox it does use the [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache) and the [IndexDB API](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) (with some fallbacks) to persist the data. However, to get a truly offline-capable web application you need to be able to precache static assets such html, css, and js files using a service worker.

In what scenario would someone choose Workbox by itself to cache both dynamic data and static assets over Redux-offline in conjunction with [sw-precache](https://github.com/GoogleChromeLabs/sw-precache) or Workbox?

Does Redix-offline's outbox/retry system for write-resilience provide a sort of polyfill for [BackgroundSync](https://developers.google.com/web/updates/2015/12/background-sync)?

**Comment by simonedavico** [comment]
I still haven't studied Workbox in detail, but, as the name suggests, redux-offline is redux specific. It is basically an abstraction over redux-persist, with a few commodities (such as the action structure for optimistic effects and the retry system). It doesn't give you everything you need for a PWA (i.e., Service Workers). 

To elaborate a little more, at work we are currently writing a PWA using create-react-app (which gives you a nice service worker for caching out of the box) and redux-offline.
As a side project, I am writing a React-Native app that uses redux-offline to persist data to RN's AsyncStorage and gives me network status and resiliency with very little effort.

**Comment by sorodrigo** [comment]
Yes like @simonedavico explains, `redux-offline` only takes care of the redux part of your application. It allows you to dispatch actions across sessions and takes care of maintaining the network status, retry and optimistic/pesimistic updates.

I think workbox and sw-precache are both compatible with `redux-offline`. Finally background sync is not yet supported.
