### ISSUE TITLE
Purging the store

### ISSUE THREAD

**Issue by ghost** [redux-offline/redux-offline#157]
There is no info  how to purge a store and a total mess when googling it since different version and reference to redux-persit. 
Plain simple 
`import {persistStore } from 'redux-persist';`
`persistStore(store).purge();` 
does not work even though the action persist/Perge is launched.
I am using Expo. Can you say how to purge the store.

**Comment by wacii** [comment]
@waubau You can setup Redux Persist yourself. Just set the offline config `persist` option to `false`.

**Comment by ghost** [comment]
I have found the solution. 
`import persist from '@redux-offline/redux-offline/lib/defaults/persist';`
`persist(store).purge()`

**Comment by sorodrigo** [comment]
There’s another example here https://github.com/redux-offline/redux-offline/issues/88
