### ISSUE TITLE
Delay render 

### ISSUE THREAD

**Issue by thm-design** [redux-offline/redux-offline#158]
I'm trying to delay the render of a component. In the readme it says I can use:

```
const config = {
  persistCallback: () => { /*...*/ }
};
```

Can you expand on how to achieve the delay this way? What would the function look like?

EDIT: To be clearer, I am using `react-router-redux` and I am having an issue where, the router is firing `"@@router/LOCATION_CHANGE"` before `"persist/REHYDRATE"`.  The component I am routing to (via `@@router/LOCATION_CHANGE`) will redirect unless a prop (that comes in via `"persist/REHYDRATE"`) is true.

Hope that makes sense. Think I basically need to delay the router until after `"persist/REHYDRATE"` is fired.

Any suggestions?

**Comment by sorodrigo** [comment]
Hey, in here #149 there's a code example that might help you.
