### ISSUE TITLE
Update documentation on rollback's payload

### ISSUE THREAD

**Issue by dgptamayo** [redux-offline/redux-offline#159]
Specifically, how can I pass the error to rollback action? The docs says:

>  If the rollback action does not have a payload, an error object returned by the effects reconciler will be set as the payload.

What if the rollback action also receives a payload?

**Comment by wacii** [comment]
@dgptamayo The documentation is wrong. The payload is always the error object. If you provide your own payload, it will just be rewritten.

**Comment by wacii** [comment]
Addressed in #160.
