### ISSUE TITLE
Please add TypeScript bindings!

### ISSUE THREAD

**Issue by deanmoses** [redux-offline/redux-offline#161]
Please add TypeScript bindings!

When I try to use redux-offline like this...
`import { offline } from 'redux-offline';`
... I get the following TypeScript compile error:

> Could not find a declaration file for module 'redux-offline'.

**Comment by PaulBrachmann** [comment]
Hey @deanmoses, take a look at [this PR](https://github.com/redux-offline/redux-offline/pull/112)

**Comment by sorodrigo** [comment]
I want to merge that soon. I’m not using typescript though, and some things have changed since it was submitted. I was wondering if someone could help out updating it so we can merge it.

**Comment by sorodrigo** [comment]
Thanks to @MLPXBrachmann bindings are coming in the next release.
