### ISSUE TITLE
Keep actions in the outbox without scheduling a retry

### ISSUE THREAD

**Issue by Xyzor** [redux-offline/redux-offline#164]
Hello

If I'm correct, now you have two option to handle actions with failed requests:
1. Discard the action and rollback
2. Keep retrying (also discard after a certain amount of time)

Scenario:
The user try to update the counter value from 0 to 1, but the request fails for **whatever reason**.

In this case i have to do two things:
1. update the counter in the store to 1 so the user can use the app
2. keep the update action in the outbox to be able to re-send it later to the server

I'd like to know if it's possible to keep the action in the outbox without automatically retrying?

**Comment by wacii** [comment]
@Xyzor Actions in the outbox are retried, one at a time, starting with the oldest. If you want to save actions without having them eventually retried, the outbox is not the place for this.

**Comment by Xyzor** [comment]
I ended up modifying the module to be able to store them in outbox.

Because it's not the place for them, I would not put unnecessary code here, but if needed i can share it.
