### ISSUE TITLE
Exist any way for dispatch multiple action in commit?

### ISSUE THREAD

**Issue by jose920405** [redux-offline/redux-offline#169]
Something like:

` commit: [{ type: 'DISPATCH_1', val: any }, { type: 'DISPATCH_2', val: any }],`

**Comment by wacii** [comment]
@jose920405 This is not supported.

**Comment by jose920405** [comment]
😭

**Comment by sorodrigo** [comment]
A new feature has been merged, the `dispatch` will return a promise that will be resolved when`commit` is dispatched and rejected when `rollback`. There some caveats though, promises won't persist across sessions, so this will only work if your action's `request` and `commit` are both dispatched in the same session.

**Comment by jose920405** [comment]
hi @sorodrigo thanks. 

You have any usage example.

I'm not sure what to do to access this new feature

**Comment by sorodrigo** [comment]
Hey, it will be available when we pubkish next release. Were currently discussing another possible solution that might suit you better

**Comment by fqborges** [comment]
This can be solved by an array middleware, can't this?

**Comment by jose920405** [comment]
maybe some combination with `redux-thunk`?

**Comment by sorodrigo** [comment]
If the actions can be performed concurrently, this can be achieved with `redux-thunk`. If they need to be sequential, the thing gets a little trickier.

#177

**Comment by jose920405** [comment]
I made some attempts:

```
export const get_items = (token: string, params: GetItemsParams) => {
  return (dispatch: Dispatch) => { // Redux thunk helper
    const executingDispatch = getExecutingObj(params.page, params.from == 'home');
    const query = { query: getQuerys(QUERY_NAMES.ALL_ITEMS, params.page, params.currentCategory) };

    dispatch({
      ...executingDispatch,
      meta: {
        offline: {
          effect: {
            url: GRAPHQL_URL,
            method: TYPE_POST,
            body: JSON.stringify(query),
            headers: buildHeaders(token)
          },
          commit: multipleDispatchCommit(dispatch, ITEMS_SUCCESS, params),
          rollback: dispatchErrorAlertObject()
        }
      }
    });
  };
};

const multipleDispatchCommit = (dispatch: Dispatch, type: string, params: any) => {
  // Dissmis Spinner
  dispatch({ type: SET_ALERT_SPINNER_VAL, value: null }); // is executed immediately like executingDispatch
  return { type, value: params }; // Executed when service dispatch response
};

```

when i call `multipleDispatchCommit` i was expected `commit` to work as a callback when the service succeeded for doing concurrently. But it seems that it reads what is sent in `commit` and gets the dispatch to then execute it later. This is what I think happens and that would explain why my dispatch `SET_ALERT_SPINNER_VAL` is executed immediately.

_____

Then I tried something else for doing sequential, that I will not share because it ended up being something that was clearly wrong, it seemed very unstable and ugly in sight ... But it worked, although I did not do many tests. I will not use it because of what was mentioned above.

**Comment by wacii** [comment]
@fqborges Some sort of generic array middleware won't work because Redux Offline adds various properties to the commit and rollback actions before dispatching.

@jose920405 `commit` is dispatched when the request succeeds. Your code is dispatching the spinner action because you are calling `multipleDispatchCommit` yourself. Perhaps you meant to pass the function instead of executing it? Although that ultimately is not a good idea with Redux Offline.
