### ISSUE TITLE
Remove `console.log` statements

### ISSUE THREAD

**Issue by wacii** [redux-offline/redux-offline#17]
In the original repo, there are a few PRs to toggle or customize logging, but I see no reason to keep it around at all. Almost anything interesting that happens in the library is accompanied by an action anyways.

**Comment by sebasgarcep** [comment]
I agree with you. Even if yoy really want/need logging you can override most of the behaviour in firebase offline with the initial config. We should hold back from doing the changes until someone else gives their thoughts on the issue, though.
