### ISSUE TITLE
Keep effect callback after rehydrate

### ISSUE THREAD

**Issue by tobob** [redux-offline/redux-offline#170]
In effect I put callback that takes two arguments (resolve and reject), it dispatch `redux-api-middelware` action, so my effect implementation looks like this:

```
  effect: (dispatchEffect) => {
     if (dispatchEffect && dispatchEffect.length === 2) {
       return (
         new Promise((resolveEffect, rejectEffect) => {
           dispatchEffect(resolveEffect, rejectEffect);
           setTimeout(() => rejectEffect(), 1234);
         })
       );
     }
 
     return (new Promise(resolve => resolve()));
   },
```

everything works fine till rehydrate, because then Im out of this callback, rollback and reject are fine because they are plain objects, is there a way to keep this callback with redux-persist?

**Comment by tobob** [comment]
it is obvious that 

```
JSON.stringify({foo: function() { console.log('bar') }})
"{}"
```

**Comment by sorodrigo** [comment]
This is not supported.  Sorry
