### ISSUE TITLE
Add `redux-offline` + `redux-saga` example.

### ISSUE THREAD

**Issue by sorodrigo** [redux-offline/redux-offline#173]
There's been some issues about sagas not playing well with redux-offline, or needing custom configs to make it work. Inspect this issue by adding an example.

Related to #77

**Comment by gusgard** [comment]
Based on @dabit1 solution, worked for me

```
import { compose, createStore, applyMiddleware, combineReducers } from 'redux';
import createSagaMiddleware from 'redux-saga';

import { offline } from '@redux-offline/redux-offline';
import defaultConfig from '@redux-offline/redux-offline/lib/defaults';
import { createOfflineMiddleware } from '@redux-offline/redux-offline/lib/middleware';

import sagas from './sagas';

const offlineConfig = {
  ...defaultConfig,
};

const sagaMiddleware = createSagaMiddleware();
const middleware = [sagaMiddleware, createOfflineMiddleware(offlineConfig)];

export default (initialState = {}) => {
  const reducers = combineReducers({ ... });

  const composeEnhancers = global.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

  const createOfflineStore = offline(offlineConfig)(createStore);

  const store = createOfflineStore(
    reducers,
    initialState,
    composeEnhancers(applyMiddleware(...middleware))
  );

  // run the sagas
  sagaMiddleware.run(sagas);

  return store;
};
```

**Comment by dabit1** [comment]
Hi everyone!

I have just created a pull request of my middleware that add functionality to dispatch thunk actions:

[https://github.com/redux-offline/redux-offline/pull/178](https://github.com/redux-offline/redux-offline/pull/178)

While it is reviewed you can add my fork to your dependencies:
[https://github.com/dabit1/redux-offline/tree/patch-4](https://github.com/dabit1/redux-offline/tree/patch-4)

I have also created a documentation :) (look for "What about if I want to dispatch a thunk after commit or rollback is dispatched?"):
[https://github.com/dabit1/redux-offline/blob/patch-4/README.md](https://github.com/dabit1/redux-offline/blob/patch-4/README.md)

I hope it help you!

Regards,

David Escalera

**Comment by msmaromi** [comment]
I fork this repo (simple react native) then add redux-offline & redux-saga https://github.com/msmaromi/basic-react-native-redux-example/tree/master

**Comment by sorodrigo** [comment]
@msmaromi Hey! sorry for replying so late, been busy. You're example is really cool, you say that sagas fix the `dispatch promises not working across sessions` issue. How do they do that?

**Comment by msmaromi** [comment]
If you have "offline action" in sagas function, and you call it when offline, then the whole function will hold until the "offline action" resolved and it continue execute the next line.

**Comment by ducpt2** [comment]
@msmaromi i'm trying your example and meet an issue: "missing email or user name",
anyway, seem like it only persist data on device (not run real request when device go back online), how can i test it run with real API?

I try to config my own project with redux-offline + redux-saga like your example, but i always got issue: "undefined not an object, '_iterator[typeOf Symbol === "function" ? Symbol.iterator: '@@iterator'].

@gusgard can you public an example?
Thank you all you guys.

**Comment by sorodrigo** [comment]
@msmaromi but that way you’re still losing the promise returned by dispatch after rehydration.

**Comment by dabit1** [comment]
@sorodrigo what about my PR? #178 We have a pending conversation hehe

**Comment by sorodrigo** [comment]
@dabit1 I know haven’t forgotten about that hehe. I’m trying to get things moving, will resume the conversation in the PR asap promise!

**Comment by sorodrigo** [comment]
Thanks everyone for your contributions, were really helpful! We have official docs now, see https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/redux-saga.md .

**Comment by sorodrigo** [comment]
Hello, as per the link you mentioned:

> What does this (partial support) mean?
Well, when dispatching an offline enhanced action, the effect reconcilier will handle the API requests and responses. This means that for offline actions you won't be able to manage the requests from within a saga. There's currently some discussions about changing the architecture to support sagas and other inside the effect reconcilier. Until then however, support will be limited to non API effect sagas.

Your problem is more related to `Next.js + redux-offline` integration please check out: https://github.com/redux-offline/redux-offline/issues/197

**Comment by ezrqnkemboi** [comment]
Thanks for this issue. Thanks, @gusgard for your breakdown of the use of sagas with redux-offline.
