### ISSUE TITLE
Default discard does not detect NetworkError correctly

### ISSUE THREAD

**Issue by Rafe** [redux-offline/redux-offline#179]
Having some problem running lint/flow on my machine so post the issue here:

Code to reproduce: https://8xml9l1r0j.codesandbox.io/

In defaults/discard.js:
```
export default (
  error: NetworkError,
  action: OfflineAction,
  _retries: number = 0 // eslint-disable-line no-unused-vars
): boolean => {
  // not a network error -> discard
  if (!('status' in error)) {
    return true;
  }

  return error.status >= 400 && error.status < 500;
};
```

Because in defaults/effect.js
```
// $FlowFixMe
NetworkError.prototype = Error.prototype;
NetworkError.prototype.status = null;
```

The `!('status' in error)` will always be false because status has been set to `null`
And `null >= 400 && null < 500` return false, so discard will never work when regular Error happened in effect, and will keep retry and congest the queue.

**Comment by wacii** [comment]
We don't set `status` of the error to `null`. We set `status` of the error's prototype to `null`. Which is never really visible as we initialize `status` in the constructor function. In fact, now that I think about it, I'm not sure why we bother setting it on the prototype at all...

**Comment by jussi-laitinen** [comment]
Just noticed this as well. Maybe it would be better to use `error.hasOwnProperty('status')` instead of `'status' in error`?

**Comment by Rafe** [comment]
> It will be the same result for `error.hasOwnProperty('status')`
(nevermind I am wrong about this)

 as @wacii said, maybe set the status to NetworkError only is a better solution. which is remove the `NetworkError.prototype.status = null` if it is not necessary

Otherwise setup more check like `typeof error.status === 'number'` can fix the problem too.
