### ISSUE TITLE
Rollback immediately without retrying

### ISSUE THREAD

**Issue by philwilks** [redux-offline/redux-offline#180]
Is it possible to change the retry strategy for different requests? In particular I'd like to be able to trigger the rollback straight away for certain actions. Here's an example of where that would be needed...

Imagine a simple Twitter clone that supports two actions, **fetching a list of tweets** and the ability to **like tweets**.

**Liking tweets** would be done via an optimistic UI update like this. The rollback might undo the like action at a later time according to the retry strategy, which by default means up to an hour later.

```JavaScript
const likeTweet = (tweetId) => ({
  type: 'LIKE_TWEET_REQUEST',    // Show the tweet as being liked
  payload: { tweetId },
  meta: {
    offline: {
      effect: { url: '/api/like', method: 'POST', body: { tweetId } },
      rollback: { type: 'LIKE_TWEET_ROLLBACK', meta: { tweetId } }    // Remove the like
    }
  }
});
```

**Fetching tweets** is different. We would update the UI to show an activity spiner, and when the commit happened the list of tweets would update. However, we don't want to wait an hour for the rollback. If the API wasn't reachable or returned an error, we would want to know about that immediately and show a message to the user like _"Sorry but we couldn't update the list of tweets at the moment"_.

```JavaScript
const fetchTweets = () => ({
  type: 'FETCH_TWEETS_REQUEST',    // Show an activity spinner
  meta: {
    offline: {
      effect: { url: '/api/tweets', method: 'GET' },
      commit: { type: 'FETCH_TWEETS_COMMIT' },    // Update the list of tweets
      rollback: { type: 'FETCH_TWEETS_ROLLBACK' }    // Show a message to the user
    }
  }
});
```

I realise of course that I could do this without `redux-offline` and that triggering the rollback immediately is missing the whole point of library. However, it makes it very tidy to have all network requests written the same way and I wonder if this would be a simple thing to achieve. 

I might be missing something really obvious too...

**Comment by sorodrigo** [comment]
You can change the effect so that it reads a flag from the action and then pass different values to the discard when needed.

**Comment by philwilks** [comment]
Thanks @sorodrigo but I'm not sure how you'd actually do this. Are you able to give any more details or a code snippet?

**Comment by sorodrigo** [comment]
Here's an example, what you want is the errorCode:
```js
import defaultEffect from '@redux-offline/redux-offline/lib/defaults/effect';

const JSONAPIDeserializer = require('jsonapi-serializer').Deserializer;

const deserializeOptions = {
  keyForAttribute: 'camelCase'
};

export default function effect(
  { url, headers, promise, errorCode, deserialize = true, ...params },
  { auth, ...action }
) {
  const req = {
    ...params,
    url,
    headers: { ...headers, Authorization: `Bearer ${auth}` }
  };
  const canDeserialize = res => res && typeof res === 'object' && res.data && deserialize;
  return defaultEffect(req, action)
    .then(
      data =>
        canDeserialize(data) ? new JSONAPIDeserializer(deserializeOptions).deserialize(data) : data
    )
    .catch(err => {
      if (errorCode) return Promise.reject({ msg: err, status: errorCode });
      throw err;
    });
}
```

**Comment by wacii** [comment]
`retry()` receives the action, so you could do it there as well. Just test for whatever flag and return `null`|`undefined` if you don't want to retry.

The documentation says:
> If this method returns null or undefined, the action will not be retried until the next time the app comes online

But that isn't right. It will dispatch the rollback and dequeue the action. I'll have to update the docs...

**Comment by philwilks** [comment]
Thanks so much @wacii and @sorodrigo. I think updating `retry()` might be easier in my case.
