### ISSUE TITLE
`Offline/STATUS_CHANGED` Action fired before `REHYDRATE`

### ISSUE THREAD

**Issue by timLoewel** [redux-offline/redux-offline#182]
shouldn't redux-offline wait for the rehydrate to be done?
And why is rehydrate triggered twice?

![image](https://user-images.githubusercontent.com/4966412/35694822-d4851356-0782-11e8-838b-83fae48fa5de.png)

redux-persist complains, that there might be a race condition.

![image](https://user-images.githubusercontent.com/4966412/35694860-f60751c4-0782-11e8-9287-12819444c7c4.png)

I am initializing my store via:
```
    const epicMiddleware = createEpicMiddleware(rootEpic);

    const reduxOfflineConfig = {
      ...defaultConfig,
      effect: (effect, action) => serverApiCall(effect, action),
      persistAutoRehydrate: () => autoRehydrate({log: true}),
      persistOptions: {
        storage: AsyncStorage,
        blacklist: ['serverSocket', 'geolocation', 'nav'],
        transforms: [immutableTransform()],
      },
    };
    const devToolsCompose =
      window['__REDUX_DEVTOOLS_EXTENSION_COMPOSE__'] || compose;
    
const enhancer = devToolsCompose(
      applyMiddleware(createRavenMiddleware(Raven), epicMiddleware),
      offline(reduxOfflineConfig),
    );
    const reducerWithLogout = logoutReducer(rootReducer);

    const store = createStore(reducerWithLogout, undefined, enhancer);
    persistor = persist(store, {});
```
my redux offline version is  "@redux-offline/redux-offline": "^2.2.1",

**Comment by sorodrigo** [comment]
You need to use the persistCallback key: https://github.com/redux-offline/redux-offline/pull/38

**Comment by timLoewel** [comment]
Thanks for the answer.

But unfortunately I am not the one that calls `offline/statusChanged`. That is triggered by the redux-offline library.
As I understand it, I can use the `persistCallback` to wait with my actions until the state is rehydrated.  But how do I make the redux-offline library wait?

I added the callback, and it does not change the behaviour. The network event is called before rehydrate. And rehydrate is called twice.

Am I adding the libraries in the wrong order?

**Comment by wacii** [comment]
`offline/STATUS_CHANGED` being dispatched before `persist/REHYDRATE` isn't a problem, as we handle the rehydration of offline state manually. We could wait though. If it does away with a warning it might be worth it.

As to why `persist/REHYDRATE` is being dispatched twice, Redux Offline calls `persistStore()` for you. It looks like you are duplicating work and setting up Redux Persist a second time. Which might be doing it.

If you want to set up Redux Persist yourself, you should `offlineConfig = { ...defaultConfig, persist: false }`.

**Comment by timLoewel** [comment]
Thanks!
Yes. That was it. 
It would be cool if the network detector could wait for the store to be persisted, so that there is no superfluous warning. The warning really sent me on the wrong track. I thought the two problems were related.
