### ISSUE TITLE
Update README.md with correct travis build link

### ISSUE THREAD

**Issue by fabriziomoscon** [redux-offline/redux-offline#184]
The correct link is `https://travis-ci.org/redux-offline/redux-offline`

There are flow errors since this develop commit: https://github.com/redux-offline/redux-offline/commit/d2a2916985f7778785675785fb58d33e2516e52a

**Comment by sorodrigo** [comment]
Thanks! I'll try to address the flow errors soon.

**Comment by sorodrigo** [comment]
Addressed in #186 would review it? I think it's fixed but just in case...
