### ISSUE TITLE
 TypeError: Cannot read property 'outbox' of undefined

### ISSUE THREAD

**Issue by evheniy** [redux-offline/redux-offline#187]
Hi

I use redux-observable and after updating from 2.2.1 to 2.3.1 I got an error
```
middleware.js:42 Uncaught TypeError: Cannot read property 'outbox' of undefined
    at middleware.js:42
    at redux-logger.js:1
    at index.js:14
    at middleware.js:13
    at createEpicMiddleware.js:73
    at Object.dispatch (applyMiddleware.js:35)
    at Function.epicMiddleware.replaceEpic (createEpicMiddleware.js:83)
    at injectEpic (epics.js:43)
    at Object../src/modules/layout/index.js (index.js:8)
    at __webpack_require__ (bootstrap 6f7b8c5e48217c67fbcf:712)
```

I'm injecting a new epics or replacing old with HMR using my library https://github.com/evheniy/wpb/blob/master/src/store/epics.js

It makes action EPIC_END:
```
action @@redux-observable/EPIC_END @ 18:19:12.966
error      TypeError: Cannot read property 'outbox' of undefined
    at middleware.js:42
    at redux-logger.js:1
    at index.js:14
    at middleware.js:13
    at createEpicMiddleware.js:73
    at Object.dispatch (applyMiddleware.js:35)
    at Function.epicMiddleware.replaceEpic (createEpicMiddleware.js:83)
    at injectEpic (epics.js:43)
    at Object../src/modules/layout/index.js (index.js:8)
    at __webpack_require__ (bootstrap 6f7b8c5e48217c67fbcf:712)
```

**Comment by sorodrigo** [comment]
Could you share your offline config? It seems to be a problem with the `offlineStateLens.get` returning undefined.

**Comment by evheniy** [comment]
Hi
I use default config
https://github.com/evheniy/wpb/blob/master/src/store/store.js

**Comment by wacii** [comment]
I don't see any glaring errors. Please link something that we can run.

**Comment by evheniy** [comment]
yes
```
git clone https://github.com/evheniy/react-app.git
cd react-app
npm i
npm run dev
```
open http://localhost:8000/
and see Uncaught TypeError: Cannot read property 'outbox' of undefined

or 
`npm start`
open http://localhost:3000/
and the same error

**Comment by wacii** [comment]
Thanks for the code. It looks like a problem on our end. Specifically with the HMR related code. Not sure why it would have only recently become a problem as it looks broken to me. I'll try and write a fix within the next couple days.

**Comment by evheniy** [comment]
Thank you!

**Comment by evheniy** [comment]
Maybe it helps - it works with previous 2.2.1 version

**Comment by evheniy** [comment]
Hi

I think I found a fix
https://github.com/redux-offline/redux-offline/blob/develop/src/middleware.js#L22

```
var offlineAction;
if (offline) {
  offlineAction = config.queue.peek(offline.outbox);
}

```

instead of 

`var offlineAction = config.queue.peek(offline && offline.outbox);`

**Comment by wacii** [comment]
If the offline state slice doesn't exist, an error should be thrown. But I have a fix open for review if you want to take a look at that.
