### ISSUE TITLE
How do you use redux-persist-migrate with redux-offline

### ISSUE THREAD

**Issue by spruce-bruce** [redux-offline/redux-offline#188]
I'm making the assumption that these libraries will play together with a little fiddling, but I can't get my migration functions to run. I think this has to be me misunderstanding how all this works, hopefully somebody can point me in the right direction

Any of you guys doing this successfully?

Here's what my store config looks like right now

```
import createMigration from 'redux-persist-migrate';

const migrations = {
  1: (state) => {
    console.log('running migration 1');
    // migration clear out state
    return state;
  },
}

const migration = createMigration(migrations, 'appVersion');

const customConfig = {
  ...defaultConfig,
  effect: async (effect, _action) => {
    // custom stuff
    return payload;
  },
  persistOptions: {
    transforms: [immutableTransform()],
  },
}

export default createStore(
  reducers,
  compose(
    applyMiddleware(apiRequestMiddleware, thunk),
    migration,
    offline(customConfig)
  )
);
```

reducers are defined like:
```
combineReducers(
  ...,
  appVersion: (state = {}) => state
);
```

**Comment by spruce-bruce** [comment]
My current guess is that this has to work by overwriting the autoRehydrate with `persistAutoRehydrate`

I tried that like this:

```
{
  ...
  persistAutoRehydrate: compose(migrate, autoRehydrate())
  ...
}
```

but got an error about a missing `next` function so I think maybe I misunderstand what's expected there.

**Comment by wacii** [comment]
I have not used the migrations library myself, but I don't see anything wrong with your code. Although `apiRequestMiddleware` does make me a bit wary as Redux Offline is very particular about how it handles requests.

If you can provide some runnable code, preferably without immutable, I might be able to help.

**Comment by spruce-bruce** [comment]
Hi - thanks for the response!

`apiRequestMiddleware` watches for a specific key in the action and does nothing if that key isn't present, so this shouldn't be the issue. I've back-burnered this problem in my project, but I'll put together a runnable example soon.

I _think_ the solution has to be composing a new `autoHydrate` function using migrate and passing that into the redux-offline config.

**Comment by calumpeak** [comment]
Hi @tribou,

This might sound odd, but have you tried flipping the argument order from `migrate, offline()` to `offline(), migrate` in compose? I did a rough test in a codesandbox [HERE](https://codesandbox.io/embed/qv8kx5l6oj) and it looks like all the manifest functions are running correctly, when they wouldn't run the way that @spruce-bruce has specified them.

Code in question:
```javascript
const store = createStore(
  reducer,
  compose(
    offline(offlineConfig),
    migrate
  )
);
```
Try that and let me know :)

**Comment by chidg** [comment]
@echoes221 worked for me.
