### ISSUE TITLE
Not able to fulfill peer dependencies of redux-offline@^2.0.0

### ISSUE THREAD

**Issue by EvanWillms** [redux-offline/redux-offline#19]
I'd like to use this community maintained package of redux-offline with [https://github.com/Malpaux/apollo-offline](apollo-offline).   Apollo-offline correctly requires a redux-offline greater than major version of 2, since jevakallio introduced a breaking API change with that release in April.  

This fork does appear to include that new API (`offline` rather than `createOfflineStore `), but still carries a package version of 1.1.0.

I've created PR #18 for this minor metadata change.

**Comment by sorodrigo** [comment]
merged, closing.
