### ISSUE TITLE
How to handle promises rejected from store.dispatch?

### ISSUE THREAD

**Issue by birgernass** [redux-offline/redux-offline#191]
With the newest update store.dispatch returns a promise for offline actions. I thought about my options to avoid unhandled promise rejections and this is what I came up with so far:

```js
export const mapDispatchToProps = actions => dispatch => {
  const dispatchWithCatch = action => {
    const dispatched = dispatch(action)
    return typeof dispatched === 'object' &&
      typeof dispatched.then === 'function'
      ? dispatched.catch(() => {})
      : dispatched
  }
  return {
    actions: bindActionCreators(actions, dispatchWithCatch),
  }
}
```

I think this new behavior should be optional. Or is it already and I am missing something? And what are your approaches to this?

**Comment by sorodrigo** [comment]
So you're getting a warning of the promise not being resolved? Our intention was to make this optional.

**Comment by birgernass** [comment]
I get an unhandled promise rejection error when a request fails.

**Comment by sorodrigo** [comment]
Thanks for the input. I’ll try to fix it from our end.

**Comment by birgernass** [comment]
No, they don't fail. But in development builds those errors trigger a fullscreen alert, which has to be dismissed.

**Comment by sorodrigo** [comment]
So I played a little bit with this. My best idea was to add an `onRejected` callback to the the resolved promise:
```js
new Promise((res, rej) => rej('oops'))
  .then(data => data, e => console.log('inner catch', e))
  .then(data => /*handle data */ data)
```
But this forces the promise to always resolve, even when it rejects internally.

So I guess the best thing you can do is to [disable the error rejection logging](https://github.com/zloirock/core-js#unhandled-rejection-tracking), or catch your promises.

**Comment by birgernass** [comment]
What do you think about making this feature configurable? We could introduce a flag, which one would have to pass into redux-offline's configuration object, to make store.dispatch return a promise in the first place. The other options seem a bit verbose for an experimental, unstable feature.

**Comment by sorodrigo** [comment]
I’m down with that, what do you think?@wacii

**Comment by wacii** [comment]
@sorodrigo Sounds good.

Even without the error, having to opt-in to the feature with offline config is probably a good idea. Returning promises is probably a breaking change and I don't want to do a major version bump for an experimental feature.

**Comment by birgernass** [comment]
Even with the new returnPromises flag set to false, you reject promises in the offlineActionTracker#rejectAction function. Because of this I still get those annoying red screens, which I can't suppress without forking the react-native project. [react-native/.../Promise.js#L17](https://github.com/facebook/react-native/blob/26684cf3adf4094eb6c405d345a75bf8c7c0bf88/Libraries/Promise.js#L17)

**Comment by wacii** [comment]
@birgernass Ah, right, of course not returning the promise wouldn't stop the error. I'll work on a proper fix this week.

**Comment by birgernass** [comment]
Thank you very much. Hope I don't sound unthankful or anything. Sometimes those things get lost in emoji free communication in a foreign language. I really appreciate the work of all of you on this project!
