### ISSUE TITLE
Dispatch returning promises

### ISSUE THREAD

**Issue by wacii** [redux-offline/redux-offline#196]
This is currently an experimental feature that must be opted in to. If we decide to keep it we should probably do a major version bump and get rid of `config.returnPromises`.

**Comment by piranna** [comment]
A major version is not needed if using `await`, since it will swallow the Promise and general behaviour would be the same as current one with returned literals. Currently, `await` is already being used in the `discard()` heuristics (commit done by me).

**Comment by wacii** [comment]
@piranna Guess I didn't understand what you meant earlier by using `await` after all. Where would you add the `await` statement?

**Comment by piranna** [comment]
> Where would you add the await statement?

Same line where it's being check the promiseEnable, it's said, when fetching the value returned by the dispatch.
