### ISSUE TITLE
Next.js support

### ISSUE THREAD

**Issue by wacii** [redux-offline/redux-offline#197]
I have played around with this off and on for awhile. The suggested way of connecting _Redux_ and _Next.js_ doesn't work with Redux Offline, and needed to be rewritten. The new code along with a working example can be found [here](https://github.com/wacii/next-redux-replay).

I'm hesitant to add an entry for this in the main documentation as it is already getting a bit long. Maybe in a separate page in the wiki? Might be a good idea to start pulling out topics regardless.

**Comment by sorodrigo** [comment]
What do you think about making a website? Show some examples perhaps and host the docs in a better way?

**Comment by wacii** [comment]
@sorodrigo Yeah, all that should probably be done. I'm starting to rewrite/reorganize the docs. I'll open a WIP PR once I have enough of it done to establish some basic structure.

**Comment by jesper-bylund** [comment]
So does this solve the issue with using redux-offline with next.js? Just replace next-redux-wrapper with replay?

**Comment by wacii** [comment]
@raelmiu It appears to, but I am not using Next.js right now. So I would consider the solution experimental.

**Comment by jesper-bylund** [comment]
@wacii thanks! I'll try it out tomorrow and report back.

**Comment by jesper-bylund** [comment]
Tried it out, still seems to work. Does require some store tweaking.

**Comment by sjunka** [comment]
@wacii @raelmiu Hi, im testing this repo example [next redux-offline](https://github.com/wacii/next-redux-replay/tree/master/examples/with-redux-offline) but it seems to be outdated and not working. Do you guys have another working project?

**Comment by wacii** [comment]
@sjunka No, but I'll give it a look.
