### ISSUE TITLE
JS_ERROR does not save all errors correctly.

### ISSUE THREAD

**Issue by liviuignat** [redux-offline/redux-offline#198]
Hi,

Looking at the screenshot bellow, `JS_ERROR` action does not serialize an `Uncaught error` of type `Error`, making code extremely hard to debug and understand what happened.

<img width="1008" alt="screen shot 2018-03-06 at 16 22 37" src="https://user-images.githubusercontent.com/2430288/37041724-29400312-215d-11e8-8718-b52258a33aed.png">

**Comment by sorodrigo** [comment]
Thanks for reporting, will have a look as soon as possible.

**Comment by DCKT** [comment]
Any news about this ? It's pretty hard to debug in this case 😅

**Comment by sorodrigo** [comment]
Sorry been busy with other stuff haven’t had the time to test it, happy to review a PR if you’re willing to contribute.

**Comment by sorodrigo** [comment]
Hello, this might come a little late. I tested the `JS_ERROR` feature and it seems to be working. The content of error is the Error instance itself, so maybe when stringifying in the dev tools it appears as an empty object.

If you still have problems with this could you share a live example where I can reproduce this? Thanks 🙂

**Comment by lab-notes** [comment]
I've just been debugging a similar error when retro fitting redux-offline into an existing app. The issue in my case was caused by a conflict with redux-axios-middleware, I solved it by just removing redux-axios-middleware and refactoring our effects.

To debug the problem I added `throw error` into send within send.js in redux-offline then removed it once I had an idea what the error was.

**Comment by rhuanbarreto** [comment]
Redux-offline should send the error to the console at least. Using redux dev tools only show an empty object.

**Comment by sorodrigo** [comment]
I think that’s reasonable. Will update the code when I find some time.

**Comment by rhuanbarreto** [comment]
I had to put a breakpoint in the source code inspector to see that the error was triggered by my reducer. Log errors and warnings to console in development is better than dispatching an action that redux dev tools will not show details. Unless you serialize the error as an object serializable by DevTools.
