### ISSUE TITLE
Deleting persisted data

### ISSUE THREAD

**Issue by no23reason** [redux-offline/redux-offline#203]
Hi, I wonder if there is some easy way to remove the data persisted by this library (e.g. for testing)?

I know you can remove the items from local storage in web browsers but what about React Native?

**Comment by nik-amir** [comment]
Use [purge](https://github.com/rt2zz/redux-persist/tree/v4#persistor-object)() function from redux-persist.

Example
```js
import persist from 'redux-offline/lib/defaults/persist';

const store = createStore(...);

const purge = () => {
	return new Promise(
		(resolve, reject) => {
			// Purge RAM cached reducer states
			store.dispatch({ type: "RESET" });

			// Purge disk cached reducer states
			const persistor = persist(store, {}, 
				(err) => {
					if (err)
						reject(err);
					resolve();
				}
			);
			persistor.purge(); // v5 returns a promise, might want to await
		}
	);
};
```

**Comment by SKempin** [comment]
Note the import should now be:
`import persist from '@redux-offline/redux-offline/lib/defaults/persist';
`

**Comment by pantomath91** [comment]
What about when we need to dlete the persisted data after a particular time period, do not want to go with seteout hell for different reducer??
