### ISSUE TITLE
Add example on how to retrieve data

### ISSUE THREAD

**Issue by ranfdev** [redux-offline/redux-offline#205]
By looking at the docs, a new user can't find a way to retrieve data. It would be better to make an example on how to retrieve data and explain where it will be stored (`action.payload`).
This is going to help **a lot** the new users approaching the library

**Comment by wacii** [comment]
It's suggested and kind-of demonstrated in [A pessimist is never disappointed](https://github.com/redux-offline/redux-offline#a-pessimist-is-never-disappointed), but it certainly could be clearer.

The docs have gotten a little out of hand, and I am currently working on a rewrite, but if you wanted to improve them in the interim, PRs are always welcome.

**Comment by aviadavretz** [comment]
I 'm having some thoughts about retrieving data using redux-offline too.

I need the state's offline.busy and offline.online flags so I could show a spinner to let the user know a loading operation is in progress (only when he's online of course).

Problem is, if I dispatch the retrieval action using redux-offline while my network's disconnected, then it will be queued and dispatched once I go back online, which doesn't make much sense - if I'm offline I don't want the retrieval action to be queued, it's relevant only when I'm online.

I thought about using redux-observable to take care of the retrieval actions, but then I'm missing on redux-offline's features + I need to update the store's offline.busy flag myself (is this a thing that's reasonable to do?) if I want to keep the spinner logic in tact.

I'm quite confused about this subject and I'd be happy to hear some advice here :)
