### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by dabit1** [redux-offline/redux-offline#206]
Hi guys, I can't start my React Native app because of I receive the error `Unhandled promise rejection`. If I don't use `redux-offline` everything works fine. Do you know what is the reason? If not, later I will try to fix it. It seems related to NetInfo.

**Comment by sorodrigo** [comment]
Yes this is related to #201 I'm sorry if we broke something. I'll try to get that merged and released fast. You could help me out reviewing that PR 😉
