### ISSUE TITLE
Offline and CRUD

### ISSUE THREAD

**Issue by marcinj1** [redux-offline/redux-offline#208]
Hello, I see that redux-offline is great for create, update and delete operations. But what about listing a lof of data? For this moment i have implemented table with server-side searching, ordering and pagination. For offline case I have to load all data and do this operations on client side. The problem is how to handle big amount of data?

**Comment by calumpeak** [comment]
That's more down to your application than the redux-offline middleware. If you want to be able to search whilst offline you'll either need to keep that data in the store or somewhere in local storage. You might want a service worker to help cache requests etc.

**Comment by piranna** [comment]
I did [redux-offline-crud-rest](https://github.com/piranna/redux-offline-crud-rest) just for this use case, maybe you'll find it interesting :-)
