### ISSUE TITLE
How would i be able to integrate this with async actions and sagas

### ISSUE THREAD

**Issue by adaschevici** [redux-offline/redux-offline#211]
This is more of a question so It should be labeled as such.

I am not sure if my approach is entirely correct:

The project I am working on uses sagas for side effects and I was considering redux-offline for  an offline first approach.
I have a bit of a problem in the chain of middlewares. The issue is that I require to pull data from the SecureStorage (Keystore/ Keychain) then I can add the meta on the action because I need to add an Auth headers to the effect meta.

```javascript
meta: {
   offline: {
       effect: {
           url: '/',
           method: 'GET',
           headers: {
               'Auth-Header': getTokenFromAsyncStorage() 
           },
      }, 
       commit:  {   type:POP, success:true}, rollback:...}}}))
```

Because I am dealing with side effects using sagas I am wondering what the proper way to order the middlewares would be.
As far as I understand it what I should do is 
saga(side effect) -> actionCreator ( with auth header ) -> saga(side effect)

Is the approach correct or am I missing something.

**Comment by wacii** [comment]
I can't help you with Redux Saga. But you shouldn't be fetching the token when you are creating an action (probably). If not resolved, offline actions can last across session, so the token may not be valid by the time an action is resolved. Generally better to add the token to the request in the effect reconciler.

**Comment by adaschevici** [comment]
ok, that moves me one step closer to the solution.
so the effect reconciler would be in the config of the enhancer, and that is where i would do the caching in case the fetch fails

**Comment by sorodrigo** [comment]
I'm wondering how would you set up the sagas side-effects to work with the offline effect reconciler (I'm asking, don't know the answer)?

About the auth header issue, I had to do something similar in another project. I wasn't using sagas though. What I did is create a middleware that would inject the auth token into every dispatched offline action:

```js
const authMiddleware = ({ getState }) => next => action => (
    action.type && action.type.endsWith('REQUEST') ? next({ ...action, auth: getState().user.token }) : next(action)
  );

// middleware
const middleware = applyMiddleware(thunk, authMiddleware);
```

And then just read it in a custom effect reconciler and apply it to the request:
```js
export default function effect(
  { url, headers, errorCode, deserialize = true, ...params },
  { auth, ...action }
) {
  if (url && typeof url === "string") {
    const req = {
      ...params,
      url,
      headers: { ...headers, Authorization: `Bearer ${auth}` }
    };
    return defaultEffect(req, action)
      .then(
        data =>
          canDeserialize(data)
            ? new JSONAPIDeserializer(deserializeOptions).deserialize(data)
            : data
      )
      .catch(err => {
        if (errorCode) return Promise.reject({ msg: err, status: errorCode });
        throw err;
      });
  }
}
```

**Comment by adaschevici** [comment]
I think the suggestion is essentially the same as you are suggesting and it would most likely work with sagas as far as I can tell.
I tried to look high and low for a preferred solution for applying along with sagas but there seem to be some requests about documenting the saga based approach.

The problem I am having is that the token is stored in AsyncStorage so the retrieval is async in nature, that was my main problem and also i wanted to not break the side effect management i do with sagas exclusively that got me confused as to what the order should be in the middlewares + enhancers.

**Comment by sorodrigo** [comment]
This has worked for some people https://github.com/redux-offline/redux-offline/issues/173#comment-359569250

**Comment by carlosbensant** [comment]
Hi @sorodrigo, thank you for sharing that [piece of code](https://github.com/redux-offline/redux-offline/issues/211#issuecomment-380272645), I've been looking for the best approach to handle Auth Headers avoiding side-effects in actions/reducers.

For HTTP Requests I use `axios`, which allows me to set [global axios defaults](https://github.com/axios/axios#global-axios-defaults) so there you can inject the authorization header. Therefore, it comes attached with every request. 

Here is my final solution:

```
const authMiddleware = ({ getState }) => next => action => {
      // Get access token from the store
      const { accessToken, tokenType, isAuth } = getState().session.access

      // It also confirms the user is authenticated
      if (action.type && action.type.endsWith('REQUEST') && isAuth) {
            axios.defaults.headers.common['Authorization'] = `${tokenType} ${accessToken}`
            axios.defaults.headers.common['Accept'] = 'application/json'
      }

      return next(action)
}
```

```
export default function configureStore( initialState ) {
      ...
      applyMiddleware(
            logger,
            authMiddleware
       ),
}
```

**Comment by DianaLaa** [comment]
For future generations: This doesn't work if you also want to put a hold on the queue if there is no token. I've tried combining this with #266 and that gives a subtle bug: If you log off, enqueue an action and then log in, authMiddleware doesn't get an access token from your store and your action is rolled back.

I'm not sure what the exact reason is, but I think it has to do with the fact that the middleware is called before your access token reaches the store. In the `peek` method, however, the access token **is** present. I solved it like so:

        queue: {
          ...defaultQueue,
          peek(array, item, context) {
              // Pause the queue if the user is not logged in
              const state = store.getState();
              if (state && state.user) 
              {
                if (state.user.token)
                {
                  const result = defaultQueue.peek(array, item, context);
                  if (result)
                  {
                    result.bearer = state.user.token;
                    return result;
                  }
                    
                  return false;
                }                
              }
              
              return false;
          },
        }

**Comment by sorodrigo** [comment]
@DianaKoenraadt That's a nice way to do it! :)
