### ISSUE TITLE
Fetching binary content

### ISSUE THREAD

**Issue by 4xemme** [redux-offline/redux-offline#213]
I'd like to use the module to fetch binary content (images, docs) from a REST API.
When trying to parse the response the module runs into an exception.
I know there's a way to provide a custom effect, is that the right approach?

**Comment by 4xemme** [comment]
Thanks @wacii . Anyone has an example?

**Comment by wacii** [comment]
I would just look at the default implementation. https://github.com/redux-offline/redux-offline/blob/develop/src/defaults/effect.js

You're making the request given an effect object (from an offline action), parsing the response body if successful, and returning a `NetworkError` if not. The only important feature about `NetworkError` is that is has the property `status` with the status code (this is used by discard to decide whether to retry the request or not).

**Comment by sorodrigo** [comment]
https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/customize-requests.md
