### ISSUE TITLE
Full redux-saga intergration (feedback requested)

### ISSUE THREAD

**Issue by kurzyx** [redux-offline/redux-offline#214]
As far as I am aware it is not possible to fully use redux-offline via saga's, therefore I am planning on forking this repository. I would like feedback on this idea.

#### Problem:
The effect is completely managed by redux-offline's effect reconciler. Because redux-offline uses this "effect reconciler" defined in the redux-offline config it is impossible to have saga's fully manage this process (reconciling the effect) e.g. fetching/posting data.

#### Possible solution:
Remove this "effect reconciler" and dispatch an action instead. A saga (or anything really) can then take that action, do its thing and report back if it had failed.

This would be the flow of actions:
1. Initial action is dispatched with metadata describing the resulting actions (commit and rollback). In addition to these 2  actions, we'll add 2 more actions: effect and failure. Effect is now an action and not (serializable) data that was previously passed to the effect reconciler.
2. redux-offline dispatches the effect action when it thinks it should.
3. The effect action is taken by a saga, this saga is required to dispatch the failure action when it failed doing its thing.
4. redux-offline listens for the failure action and if it was dispatched redux-offline decides whether to retry (step 2) or dispatch the rollback action.

Note: I did keep the definition of the commit action in this example (step 1), but this is now unnecessary due to it being managed by saga's.

Visual representation of the flow of actions:
![sagas redux-offline example](https://user-images.githubusercontent.com/1412696/38773063-a3a2e2ea-4044-11e8-83df-b3d81689e1cf.png)

**Comment by wacii** [comment]
Not all that familiar with Redux Saga, but this is the same solution I came up with. My only worry was that you would be replacing so much of Redux Offline, that it might be easier to just rewrite it using Redux Saga directly.

**Comment by kurzyx** [comment]
Will you though? I reckon change will keep to a minimum, since all you're changing is the effect part. (see send.js)

**Comment by sorodrigo** [comment]
I see your point in replacing send, I wonder if we could do this in a plugin fashion? We’re talking about making a v3 release soon. It would be nice if we could give first class support for sagas, if we manage to do it without changing all the library.
I was thinking on a plugin architecture because the offline config keeps growing and growing, and also today people want sagas support but maybe afterwards they’ll want epics with redux-observable or what not. I don’t want to commit to anything but i think this should be a part of the v3 discussion.

**Comment by wacii** [comment]
@kurzyx Everything kept to the effect reconciler? Huh. It would need to communicate with something that could listen for dispatched actions, in order to resolve the returned promise. I can picture how to do that with a new middleware; imagine it would be basically the same using Redux Saga.

**Comment by bryanph** [comment]
@kurzyx did you ever move along with this?

**Comment by calumpeak** [comment]
I'm currently collating ideas for a re-write for V3. I like the plugin idea but it depends on how much of the logic we want to shift into said plugin (whether it be default or not).  As well as making the migration path simple for those that just want a standalone upgrade. `send.js` does a lot more than a simple dispatch at the end of the day.

**Comment by kurzyx** [comment]
@bryanph I did manage to use saga by dispatching a new action within the returned promise in the configurable effect property. Added to the payload of this action are two functions to either resolve or reject the promise, which one of the functions can then be called by a saga.

Though I'm not sure whether this is the best approach, but it does work.

**Comment by kurzyx** [comment]
Looking back at the initial comment. I said the following:

> I did keep the definition of the commit action in this example (step 1), but this is now unnecessary due to it being managed by saga's.

This is incorrect, because redux-offline needs to know wheter/when it succeeds.

**Comment by Pushplaybang** [comment]
@kurzyx any chance of an example?
