### ISSUE TITLE
Fetch using redux-offline 

### ISSUE THREAD

**Issue by aviadavretz** [redux-offline/redux-offline#216]
I 'm having some thoughts about retrieving data using redux-offline.

I need the state's offline.busy and offline.online flags so I could show a spinner to let the user know a loading operation is in progress (only when he's online of course).

Problem is, if I dispatch the retrieval action using redux-offline while my network's disconnected, then it will be queued and dispatched once I go back online, which doesn't make much sense - if I'm offline I don't want the retrieval action to be queued, it's relevant only when I'm online.

I thought about using redux-observable to take care of the retrieval actions, but then I'm missing on redux-offline's features + I need to update the store's offline.busy flag myself (is this a thing that's reasonable to do?) if I want to keep the spinner logic in tact.

I'm quite confused about this subject and I'd be happy to hear some advice here, how you guys retrieve data in your offline-first app? :)

**Comment by donni106** [comment]
Is this related to that https://github.com/redux-offline/redux-offline/issues/65#issuecomment-359264262?

**Comment by bryanph** [comment]
@aviadavretz How did you end up handling this?
