### ISSUE TITLE
Any plans regarding Redux v4?

### ISSUE THREAD

**Issue by donni106** [redux-offline/redux-offline#218]
As Redux [v4.0.0](https://github.com/reactjs/redux/releases/tag/v4.0.0) was released officially 7 days ago, i wonder if there is a roadmap for redux-offline to get updated?

**Comment by sorodrigo** [comment]
It seems to me like there’s no breaking changes for us. It would only affect users that dispatch inside a reducer, and thats a bad practice so I don’t know if we’re supposed to treat that case as a breaking change. That said we need to test it.

**Comment by sorodrigo** [comment]
I was bumping the version, but just realised we have it as a peer dependency, this will add a warning to many users. Currently we support `>=3` and I think this is reasonable.

**Comment by wacii** [comment]
@sorodrigo Yeah, that sounds fine.
