### ISSUE TITLE
Difference with redux-persist?

### ISSUE THREAD

**Issue by Cretezy** [redux-offline/redux-offline#22]
Since this is a new project, what is the difference with https://github.com/rt2zz/redux-persist ?

**Comment by sedubois** [comment]
Have you read the medium article and readme?

**Comment by Cretezy** [comment]
I have not seen the Medium article, mind link me?

**Comment by sedubois** [comment]
https://hackernoon.com/introducing-redux-offline-offline-first-architecture-for-progressive-web-applications-and-react-68c5167ecfe0

**Comment by sedubois** [comment]
And note this in readme:

"Instead of reinventing the wheel, Redux Offline uses the excellent redux-persist library."

**Comment by rt2zz** [comment]
The clarify for others headed this way: in addition to general state persistence, redux-offline solves the high order problem of managing offline effects.

**redux persist:** persist state
**redux offline:** persist state + manage offline effects (retry + commit + rollback)

**Comment by dancomanlive** [comment]
What are offline effects?
