### ISSUE TITLE
Action Offline/BUSY: false no longer emitted

### ISSUE THREAD

**Issue by calumpeak** [redux-offline/redux-offline#223]
Hi!
First off, just wanted to say great work on the redux-offline library. We're currently using it to build a large offline first application and it works like a charm. The implementation is fantastic, especially since you've exposed the queue to the config!

I just wanted to raise an issue around the `Offline/BUSY` action. The original Implementation ([HERE](https://github.com/redux-offline/redux-offline/pull/52) used to dispatch `Offline/Busy -> true` on when an offline action was being processed and `Offline/Busy -> false` when the promise resolved. Not sure when this was changed, but the current implementation swallows this change directly on the reducer on complete ([HERE](https://github.com/redux-offline/redux-offline/blob/develop/src/updater.js#L108)), instead of dispatching `Busy -> false`. 

It's nice to use these actions to tell whether the application is 'syncing' or not, but as the action dispatch is not consistent the only solution to this I've found is to subscribe to the store (instead of a piece of middleware) and update based on our internal status and whether or not `offline.busy` is true/false to dispatch relevant actions. Here's a rough example:

```javascript
import { PENDING } from '../constants/status';

const statusHandler = ({ getState }, { start, end }) => () => {
  const { offline, syncStatus } = getState();

  if (offline.busy && syncStatus !== PENDING) {
    start();
  }

  if (!offline.busy && syncStatus === PENDING) {
    end();
  }
};

export default (store, statusHandlers) =>
  store.subscribe(statusHandler(store, statusHandlers));
```
There's a chance here that multiple events get emitted repeatedly due to being a subscription (this is handled elsewhere via some debouncing etc).
Would it be possible to get this action to be consistent, similar to `network_status_changed`. More than happy to raise a PR for this if it's something that's viable...

Let me know 😄

**Comment by calumpeak** [comment]
@sorodrigo Any thoughts?

**Comment by sorodrigo** [comment]
Hello 👋 ! Sorry for the late reply, I don't get whats the difference TBH. The `offline.busy` gets updated either way. Would you please explain me your intentions with having `Offline/BUSY` do this.
Thanks!

**Comment by calumpeak** [comment]
Hey @sorodrigo 😄 ,

No problem, thanks for coming back to me. 

It's more about consistency in the interface and detecting when we're busy from outside of `redux-offline`. The busy flag is set explicitly by an action which is easy to capture in a bit of middleware but detecting when we're not busy relies on checking the store for that value which IMO, is a more expensive/awkward as you'd have to set a subscription to work out when the value changed or check the meta tags on each committed/rolled back action which isn't as reliable/clean. It also has the potential, as it's a subscription, to call func/emit values more than it needs to.

If it was just the case of connecting a component to the `busy` state of `offline` that'd be fine. But for more complex applications (such as ours) where multiple things could trigger busy/syncing in the application (e.g. push notification services etc) we need to mediate between various syncing inputs to define the correct output. Hiding (from a redux action perspective) when the busy flag is set back to false makes more complex integrations (or other side effects) a little harder to work with the library (though still possible).

Instead of the above which uses a subscription, you can rely on the actions explicitly in middleware e.g.

```javascript
const statusHandler = store => next => action => {
  next(action);

  if (action.type !== 'Offline/Busy') return;

  return action.payload.busy ? something() : somethingElse();
}
```
It's why I bring up the `network_status_changed` action; it's explicit every time it changes which makes it easy to do other side-effects/be reactive to those changes in the application (e.g. start/stop various connections, pull data that's not handled by `offline` etc).

Thanks!

**Comment by sorodrigo** [comment]
Ok now I get it 😛 ! I don't think there's a problem with making this change, what do you think? @wacii

**Comment by sorodrigo** [comment]
Could you submit a PR restoring the change linked above? @echoes221

**Comment by calumpeak** [comment]
@sorodrigo Yeah not a problem I'll work on restoring that and raise a PR when it's ready. Thanks guys!

**Comment by calumpeak** [comment]
@sorodrigo Hi! Me again.
I don't want to open another issue as this is connected here.
We're accessing `redux-offline` constants via a deeply nested path (e.g. `'@redux-offline/redux-offline/lib/constants'`) and was wondering how static they're likely to be as they're currently private? Are there any plans to export them in the future to allow further use cases? I want to avoid breaking changes between minor versions if possible (basically, are they safe for the time being).

Like the above we run some side effects off these actions, or other examples, like making dev debugging easier:

```javascript
import { JS_ERROR } from '@redux-offline/redux-offline/lib/constants';

export const offlineJsError = action$ =>
  action$
    .ofType(JS_ERROR)
    .do(({ meta }) =>
      console.error(
        'Something went wrong whilst resolving an offline action',
        meta.error,
      ),
    );
```

Thanks in advance!

**Comment by sorodrigo** [comment]
Yes at least some of these actions (if not all) should be part of the public API. Maybe updating the docs to include them will be enough? Thought @wacii ?

BTW I want to thank you for your help answering other people's issues! It's very much appreciated @echoes221

**Comment by calumpeak** [comment]
@sorodrigo Awesome that sounds good, so I'll keep the deeply nested imports for the time being. If you want these to be part of the API I can raise a PR to export them if you need :)

And no problem. I'm one of the ones responsible for our offline first initiative here at Mendeley. I'm using redux-offline day in day out here and come up against some nice challenges to adapt this to. We previously had an in house solution using `persist` (complete with a version of your proposed `smart-queue` - which I might raise a PR for when I get some time as I need to put it back in the project!) as redux-offline didn't offer enough out of the box for us this time last year (mainly access to the queue system). But since the update earlier this year I've refactored the application around it and it's really nice to use. I'll help where I can as I've come up against a fair few of these questions myself and I'd love to contribute to the project.

We're building a desktop(electron) & web app and have a beta for it. I'll share it with you guys once it's progressed a little further as our beta is currently very rough.

**Comment by sorodrigo** [comment]
Stuff like this is always great to hear! About the smart-queue there's an implementation on the making .

I've been quite busy and haven't had the time to test it as it should. If you're curious, check it out here: https://github.com/redux-offline/queue/pull/2

**Comment by calumpeak** [comment]
Ah awesome, I didn't spot that branch. It looks good!
