### ISSUE TITLE
Type error when using createOffline's middleware

### ISSUE THREAD

**Issue by aviadavretz** [redux-offline/redux-offline#224]
When i used the offline creator approach in my Angular TypeScript app it worked,  now i'm trying to use redux-offline with redux-observable, so i have to use createOffline to get the enhancers and middleware.

However, there seems to be a type mismatch between the returned middleware from createOffline function and applyMiddleware's expected parameters.

Here's my code:
```
export class StoreModule {
  constructor(public ngRedux: NgRedux<AppState>, devTools: DevToolsExtension, private epics: RootEpics) {
    const offlineEnhancers = createOffline(offlineConfig);
    const middleware = applyMiddleware(
      createEpicMiddleware(this.epics.createEpics()), offlineEnhancers.middleware);

    const store: Store<AppState> = createStore<AppState>(
      offlineEnhancers.enhanceReducer(rootReducer),
      INITIAL_STATE,
      compose<StoreEnhancerStoreCreator<AppState>>(
        middleware,
        offlineEnhancers.enhanceStore,
        devTools.isEnabled() ? devTools.enhancer() : [])
    );

    ngRedux.provideStore(store);
  }
}
```

Here's the error message:
`ERROR in src/app/store/store.module.ts(23,88): error TS2345: Argument of type '<A = any, R = any>(store: any) => (next: (action: A) => R) => (action: A) => R' is not assignable to parameter of type 'Midd
leware'.
  Type '(next: (action: Action) => Action) => (action: Action) => Action' is not assignable to type '(next: Dispatch<S>) => Dispatch<S>'.
    Type '(action: Action) => Action' is not assignable to type 'Dispatch<S>'.
      Type 'Action' is not assignable to type 'A'.
`

Any help would be appreciated :)

**Comment by sorodrigo** [comment]
It seems that our typings for `createOffline` are incorrect. Could you try ignoring that error and test if it works? That would help us discard other issues, and just update the typing to the correct one. :)

**Comment by aviadavretz** [comment]
@sorodrigo 
It looks like despite the type error, things are working (including the redux-observable intergration)

**Comment by sorodrigo** [comment]
Thanks! I don’t use typescript so it’s harder for me to know if a type definition is incorrect. It’d be great if you could PR us with the correct typing change.

**Comment by aviadavretz** [comment]
@sorodrigo 
Created a PR, would be great if you'd take a look :)
