### ISSUE TITLE
How to rewrite persisted data?

### ISSUE THREAD

**Issue by nimblemo** [redux-offline/redux-offline#225]
How to rewrtite persisted data? When i load new data troug redux saga, persisted store can't rewrite and it return old data.

1) I set redux-offline with saga how it descibed in the instruction
2) I use a standart way to organize application

- actions.js

```js
export const RECIEVE_TRAINING_ACTIONS = 'RECIEVE_TRAINING_ACTIONS';

import Reactotron from 'reactotron-react-native';

export function recieveTrainingActions(actions) {
  return {
    type: RECIEVE_TRAINING_ACTIONS,
    payload: actions,
  };
}
```

-saga.js

```js
export function* getDictionaries() {
  const trainings = yield call(api.getDictionaries);

  yield put(actions.recieveTrainingActions(snapshotToArray(trainings)));
}
```

-reducer.js

```js
export default function reducer(state = initialState, action) {
  switch (action.type) {
    case RECIEVE_TRAINING_ACTIONS:
      return {
        ...state,
        dictionaries: { train: action.payload },
      };

```

3) But if persist store have old data, then new data cant't stored here 

![360](https://user-images.githubusercontent.com/8470244/39895014-68b7103a-54b1-11e8-88db-434d666625e4.png)

**Comment by sorodrigo** [comment]
It’s hard for me to tell, with the info provided. I think you might be missing a persistCallback but it would be great if you coukd provide us some code examples to know for sure.

https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#persistcallback

**Comment by thisroot** [comment]
This problem was solwed.

Need to add you object to initial state

```js
let initialState = {
  ...
  dictionaries: {
    train: undefined,
  },
...
};
```

**Comment by thisroot** [comment]
https://bitbucket.org/egormikheev/bigdogproto

**Comment by nimblemo** [comment]
This data is updated after the application is restarted. I was getting an error when updating the application in dev mode directly
