### ISSUE TITLE
"Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android"

### ISSUE THREAD

**Issue by timLoewel** [redux-offline/redux-offline#226]
On android with 
    "react-native": "0.53.3",
and 
    "@redux-offline/redux-offline": "^2.3.3",

I get the warning, that a timer was set with a long timeout.
(this warning comes with each Offline/SCHEDULE_RETRY)
Does anyone have a workaround for this? The warning says, that this was a correctness issue. 
 
This is the referenced feature request for react-native: [react native github issues](https://github.com/facebook/react-native/issues/12981) 

This is the complete warning message:
```
Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 180000ms)
console.warn @ YellowBox.js:82
setTimeout @ JSTimers.js:253
(anonymous) @ middleware.js:25
Promise @ es6.promise.js:171
after @ middleware.js:24
(anonymous) @ middleware.js:56
(anonymous) @ createEpicMiddleware.js:71
(anonymous) @ middleware.js:72
dispatch @ applyMiddleware.js:45
_callee$ @ send.js:97
tryCatch @ runtime.js:65
invoke @ runtime.js:299
prototype.(anonymous function) @ runtime.js:117
step @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
run @ es6.promise.js:66
(anonymous) @ es6.promise.js:79
flush @ _microtask.js:18
tryCallOne @ core.js:37
(anonymous) @ core.js:123
(anonymous) @ JSTimers.js:301
_callTimer @ JSTimers.js:154
_callImmediatesPass @ JSTimers.js:202
callImmediates @ JSTimers.js:470
__callImmediates @ MessageQueue.js:329
(anonymous) @ MessageQueue.js:147
__guardSafe @ MessageQueue.js:316
flushedQueue @ MessageQueue.js:146
invokeCallbackAndReturnFlushedQueue @ MessageQueue.js:142
t @ RNDebuggerWorker.js:1

```

**Comment by GianniGM** [comment]
Same issue!! Annoying!!! 💃

**Comment by sorodrigo** [comment]
From the issue linked above:
> There's nothing to worry about here, and the warning is incorrect and should be removed. There isn't a "Timing Module" to keep awake, there's just a Choreographer callback that checks for timers every frame (which also makes the min granularity for timers be ~16ms).
There is a correctness issue in the sense that timers won't fire in the background on either iOS or Android. This warning seems to be specifically about Android though and does not appear to be accurate. All timers should eventually fire when the app comes back into the foreground.

Without entering in whether this is an issue or not, I think this falls more under the `react-native` domain. If/when an alternative solution is provided we can then address this issue.
More over, it's on the roadmap but currently we do not support background sync, so you could say this issue does not affect redux-offline.

Open to suggestions if you feel there's something we could improve! We can discuss it and if it leads to a PR thats great!
