### ISSUE TITLE
[Question] How to test 

### ISSUE THREAD

**Issue by DCKT** [redux-offline/redux-offline#227]
Hello,

I'm using `redux-offline` on my project and I still don't know how to test properly this module with Jest. I'm  using [redux-mock-store](https://github.com/arnaudbenard/redux-mock-store/blob/master/src/index.js).

Thanks for your help.

**Comment by calumpeak** [comment]
You shouldn't need to test third party/open source code that's already tested. What you should test is your actions and reducers, it should be enough. If you're wanting to test the entire throughput you'll need to use something like `nock` to mock HTTP requests, though I don't think that's necessary.

**Comment by DCKT** [comment]
@echoes221 You're totally right. It would be over-testing. Thanks 😄
