### ISSUE TITLE
commit is fired multiple times if other actions are dispatched during request

### ISSUE THREAD

**Issue by benvp** [redux-offline/redux-offline#23]
Following scenario (react-native, should apply to web, too):

During component mounting, I dispatch an action to be picked up by `redux-offline`. During the time the request is made, I dispatch some other actions, which should not be handled by `redux-offline`. However, these actions will be picked up by the middleware and will end in calling the `commit` handler multiple times for the amount of times of the actions, which have been dispatched during the time the request is made (or during the time the effect waits for promise resolve). 

I hope you understand what I mean, it's not that simple to describe. My proposed solution to this would be to check in the middleware if an meta.offline key is present, otherwise just ignore the action.

What do you think?

**Comment by benvp** [comment]
@jevakallio any ideas on this? This is making me a lot of trouble and I don't know how to get around this issue. Every time I dispatch some UI specific actions immediately after dispatching an action with an offline key, the reconciler is fired multiple times therefore creating duplicated entities in my backend.

Any idea how to solve it which points me into the right direction would be great and I'll submit another PR.

**Comment by dabit1** [comment]
I have the same problem. When my app starts dispatch an action that does not have meta and another that has meta, and the action with meta is dispatched twice. In my case, "persist/REHYDRATE" action causes that the action with meta be dispatched twice.

**Comment by Noitidart** [comment]
I am still having this problem.

I am using redux thunk.


```
function push() {
    return (dispatch, getState) => {

        ////// start first dispatch
        dispatch({
            type: 'PUSH',
        })
        ////// start first dispatch

        ////// start second dispatch
        dispatch(apiCall(id));
        ////// end second dispatch
    }
}

function apiCall() {
    return (dispatch, getState) => {
        // this is really where second dispatch happens
        dispatch({
            type: 'API_CALL',
            meta: {
                offline: {
                    effect: getEffect(),
                    commit: { type:'API_DONE' },
                    rollback: { type:'API_FAIL' }
                }
            }
        })
        // end really dispatch second
    }
}
```

It seems if I dispatch a

**Comment by Noitidart** [comment]
So this is still a problem. I tried it without thunk's too. It is not firing multiple times, it doesnt fire at all. It gets to the `dispatch((0, _actions.busy)(true));` but the promise never resolves or errors:


```
  return config.effect(metadata.effect, action).then(function (result) {
    console.log('config.effect result:', result);
    return dispatch(complete(metadata.commit, true, result));
  }).catch(function (error) {
    console.error('config.effect gave error:', error);
    // discard
    if (config.discard(error, action, retries)) {
      console.log('Discarding action', action.type);
      return dispatch(complete(metadata.rollback, false, error));
    }
```

**Comment by bendelonlee** [comment]
Seem to be having a similar issue, using version 2.6.0

**Comment by sorodrigo** [comment]
This is strange it shouldve been fixed a while back, could you share more info? Maybe a reproduction of the bug or a screenshot of the devtools logs.
