### ISSUE TITLE
Android not rehydrating if app is "minimized"

### ISSUE THREAD

**Issue by nbastoWM** [redux-offline/redux-offline#231]
I'm using this package to store the menu  from my App. 
The problem I'm facing in Android is, if the device is offline, the rehydration only happens if the App is fully closed. If I just press back to "close" it, when I open it, the rehydrate doesn't fire.

**Comment by sorodrigo** [comment]
Could you share your offline config?

**Comment by nbastoWM** [comment]
Hi,

```js

const config = {
  ...offlineConfig,

  // @overwrite effect
  effect: (effect, action) => {
    console.log(`Executing effect for ${action.type}:`, effect);

    return fetch(effect.url, {
      method: effect.method,
      headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(effect.body)
    }).then(res => {
      console.log('response', res);
      return res.json();
      // return res.ok
      //   ? res.json()
      //   : Promise.reject(res.text().then(msg => new Error(msg)));
    });
  },

  // @overwrite discard
  discard: (error, action, retries) => {
    console.log(error);
    return retries > 0;
  },

  // @overwrite retry
  retry: action => (action.meta.urgent ? 100 : 10000),

  // @overwrite persist
  persistCallback: () => console.log('Rehydratation complete'),
  persistOptions: {
    storage: AsyncStorage,
    whitelist: ['readConfigReducer', 'readContentsReducer'],
    debounce: 300,
    stateReconciler: autoMergeLevel2
  }
};

```

I got this from this example:
https://github.com/Xyzor/react-native-redux-offline-example/blob/master/src/store.js

I tried different stateReconciler but with no success.

**Comment by sorodrigo** [comment]
Sorry I misunderstood your initial issue. There's no need to rehydrate when the app is minimized because the store (should) still hold the state in memory. Is this not happening to you? In that case, could you provide a code example replicating this issue?
