### ISSUE TITLE
Airplane mode doesn't trigger retry

### ISSUE THREAD

**Issue by DCKT** [redux-offline/redux-offline#232]
Hello,

I've noticed when I switch on Android to the Airplane mode, it looks like `redux-offline` doesn't notice the `connectionChange` event, so every action is not backed up in the store.

I'm using the default offline config.

Any ideas about this ?
Thanks.

**Comment by bgerhards** [comment]
@DCKT do you have any updates? Are you still having this issue? Can you share what you have tried?

**Comment by sorodrigo** [comment]
Are you testing on a simulator or real phone?
