### ISSUE TITLE
onBeforeLift in redux-offline

### ISSUE THREAD

**Issue by otaviogaiao** [redux-offline/redux-offline#234]
Hello, I'm setting up redux-offline in my application and there are some actions that I'd like to do before the HYDRATE action happens. On redux-persist there is the onBeforeLift function. But I can't find where to use it with redux-offline. 

Is this functionality, or something similar, available?

Thanks.

**Comment by calumpeak** [comment]
Hi @otaviogaiao `onBeforeLift` is part of `redux-persist`'s `<PersistGate />` component. `PersistGate` only ships with v5 of persist, `redux-offline` uses v4. You will likely need to build your own implementation of the gate, there's an old recipe [here](https://github.com/rt2zz/redux-persist/blob/f4a6e86c66693a0bd5e6ea73043fd98b14f44a96/docs/recipes.md) from v4, or take queues from the current [persist gate implementation](https://github.com/rt2zz/redux-persist/blob/master/src/integration/react.js) and adapt it for V4.  You can do a simple promise based component that has it's own 'onBeforeLift'. There might be something else in the rest of the v4 docs [here](https://github.com/rt2zz/redux-persist/tree/f4a6e86c66693a0bd5e6ea73043fd98b14f44a96/docs)

**Comment by otaviogaiao** [comment]
Thank you man. I will take a look !

**Comment by sorodrigo** [comment]
You can use redux-persist v5 also, but you'll have to set it up yourself. https://github.com/redux-offline/redux-offline/issues/119#issuecomment-343588170
