### ISSUE TITLE
How to differentiate a commit action from outbox vs normal commit?

### ISSUE THREAD

**Issue by ethantran** [redux-offline/redux-offline#237]
I make a SELL_REQUEST action with SELL_SUCCESS as the commit and SELL_FAIL as the rollback. If the network is online, the SELL_SUCCESS commit happens as normal and I show an alert("success"). However, I don't want this alert to show up if the SELL_SUCCESS commit happens from an "offline to online" scenario. There could be a bunch of outbox SELL_REQUESTS when a user has airplane mode on. When they turn airplane mode off and the SELL_REQUESTS become SELL_SUCCESS, a bunch of alerts will fire.

Perhaps I am not handling the UX correctly for an offline first experience. When the network is online, I do the usual loading indicator and success alert flow. But that approach doesn't seem to work with this scenario. I can't show pending state because it will be stuck there since redux offline does not return anything after a SELL_REQUEST when network is offline. So I don't use that flow by checking if the network is offline. When the network is offline, I just update the UI as if the SELL_SUCCESS happened. But I don't know how to prevent alerts from popping up when outbox makes SELL_REQUESTS later on. The alerts are done in componentDidUpdate with an equality check.

**Comment by calumpeak** [comment]
I might be wrong in suggesting this (or might not understand your problem correctly) but have you thought about modifying the `queue` config to decorate the commit/rollback action that you're queueing?

`redux-offline` gives you access to `queue.enqueue` and `queue.dequeue`. These both describe how actions are stored/removed within the `outbox`. When you go to enqueue your action you can check the online state at that point, you can then use middleware/reducer to check the action carries a flag to whether that action was created offline or not to know when to sync.

Here's a rough example that sets a 'wasOnline' flag to the commit actions meta before the action is added to the `outbox` before `redux-offline` processes the request:

```javascript
import { createStore } from "redux";
import { offline } from "@redux-offline/redux-offline";
import offlineDefaultConfig from "@redux-offline/redux-offline/lib/defaults";
import { set, cloneDeep } from "lodash";

let store;
const getStore = () => store;
const offlineConfig = {
  ...offlineDefaultConfig,
  queue: {
    ...offlineDefaultConfig.queue,
    enqueue: (outbox, action) => {
      const { online } = getStore().getState().offline;
      const clonedAction = cloneDeep(action);

      return [
        ...outbox,
        set(clonedAction, "meta.offline.commit.meta.wasOnline", online)
      ];
    }
  }
};

store = createStore(s => s, offline(offlineConfig));
```

I'd be aware of caveats of this however, e.g. going offline mid action request and the action setup for a retry in that process.

This would do it by default. If you wanted more control over which actions do and don't need this information in the commit/rollback actions then you can change each action you dispatch to a `thunk` and lookup the current online state before you dispatch the action and decorate each commit actions meta then...

Also to note, if you have difficulties catching actions in the middleware that have been emitted by redux offline you may need to do a custom setup.

**Comment by ethantran** [comment]
This looks like it will work. However, I get the "cannot call getState in a reducer that is running" error. I tried using the context parameter of enqueue but it is undefined because it looks like redux-offline isn't updated with that commit yet. I will try the thunk strategy.

**Comment by calumpeak** [comment]
Ah yeah - my bad - you can't do that as it's in the reducer and an anti-pattern. I forgot about that. Thunk will definitely work in that case however. 

I over complicated my example, `enqueue` has three arguments ([according to the code](https://github.com/redux-offline/redux-offline/blob/develop/src/updater.js#L96)) , it receives the rest of the state, you should only need to do this for enqueue to read the onlinestate:

```javascript
const offlineConfig = {
  ...offlineDefaultConfig,
  queue: {
    ...offlineDefaultConfig.queue,
    enqueue: (outbox, action, { offline }) => {
     const clonedAction = cloneDeep(action);

      return [
        ...outbox,
        set(clonedAction, "meta.offline.commit.meta.wasOnline", offline.online)
      ];
    }
  }
```

**Comment by sorodrigo** [comment]
I will try to push a new version this week. The context param may help you achieve this.
