### ISSUE TITLE
Outbox not persisting when using redux-persist v5

### ISSUE THREAD

**Issue by connercms** [redux-offline/redux-offline#239]
I am manually setting up redux persist v5 and setting persist to false in my offline config so redux-offline doesn't try to set it up. When I toggle my connection offline and have an item in the outbox then close the application and restart it, the outbox items are not persisted. The offline store is missing from the persist/REHYDRATE action payload, but all my other stores are there so I feel like I am just missing something in the setup.

Here is my configure store file
```
const persistConfig = {
  key: 'root',
  storage
}

const reduxOfflineConfig = {
  ...offlineConfig,
  persist: false,
  effect: effect =>
    axios(effect)
      .then(response => response.data)
      .catch(error => Promise.reject(error))
}

const sagaMiddleware = createSagaMiddleware()

const persistedReducer = persistReducer(persistConfig, reducers)

const middlewareList = [thunk, sagaMiddleware]

const {
  middleware: offlineMiddleware,
  enhanceReducer,
  enhanceStore
} = createOffline(reduxOfflineConfig)

const middleware = applyMiddleware(...middlewareList, offlineMiddleware)

export default () => {
  let store = createStore(
    enhanceReducer(persistedReducer),
    compose(enhanceStore, middleware)
  )

  sagaMiddleware.run(mySaga)

  let persistor = persistStore(store)

  return { store, persistor }
}
```

And my app entry file if relevant 
```
const { store, persistor } = configureStore()

export default class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <PersistGate persistor={persistor}>
          <CleanTouchMobile />
        </PersistGate>
      </Provider>
    )
  }
}
```    

"react-native": "^0.55.3",
"@redux-offline/redux-offline": "^2.3.3",
"redux-persist": "^5.9.1",

**Comment by calumpeak** [comment]
Have you tried the setup from [HERE](https://github.com/redux-offline/redux-offline/issues/119#issuecomment-343588170) ?

**Comment by connercms** [comment]
Using that setup, it does seem to persist the outbox also, but now none of my actions are being resolved by my reducers. Should I be importing and adding my own reducers to the config somewhere?

```
const {
  middleware: offlineMiddleware,
  enhanceReducer: offlineEnhanceReducer,
  enhanceStore: offlineEnhanceStore
} = createOffline({
  ...offlineConfig,
  persist: false,
  effect: effect =>
    axios(effect)
      .then(response => response.data)
      .catch(error => Promise.reject(error))
})

const persistConfig = {
  key: 'root',
  storage
}

const baseReducer = (state = {}) => state
const reducer = persistReducer(persistConfig, offlineEnhanceReducer(baseReducer))

const sagaMiddleware = createSagaMiddleware()

const middlewareList = [thunk, sagaMiddleware]

const middleware = applyMiddleware(...middlewareList, offlineMiddleware)

export default () => {
  const store = createStore(
    reducer,
    compose(middleware, offlineEnhanceStore)
  )

  const persistor = persistStore(store)

  sagaMiddleware.run(mySaga)

  return { store, persistor }
}

```

**Comment by calumpeak** [comment]
Yeah, replace `baseReducer` with your reducers.

**Comment by connercms** [comment]
Ok, I had tried that and the app would not pass the PersistGate. I thought maybe I was doing something wrong, but instead I had to do a fresh install of the application for some reason to get it to work properly. Thanks for all your help @echoes221

**Comment by connercms** [comment]
Doing that allowed both my reducers and redux-offline state to be persisted, but now toggling connection does not trigger the outbox to attempt the queued items. Have to completely close application and reopen to trigger this.

**Comment by calumpeak** [comment]
@connercms as per the docs for `createOffline` [HERE](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/create-offline.md), `offlineEnhanceStore` must come before `middleware` in `compose` (it's picky!). That should fix your issue :)

**Comment by connercms** [comment]
Ok I believe that resolved the issue. Thanks!

**Comment by ghost** [comment]
Trying to manually setup redux-persist 5 as well @connercms, any steps you'd recommend from your experience?

**Comment by DianaLaa** [comment]
Same as issue #151? I encountered the same and downgrade back to v4 resolved it.
