### ISSUE TITLE
How to retry forever?

### ISSUE THREAD

**Issue by saade** [redux-offline/redux-offline#240]
Hello! I'm implementing this on a react-native app, i need to retry forever until user become online, is this possible?

**Comment by wacii** [comment]
Write your own ‘config.retry’ that never returns ‘null’. (That is the function that returns the delay between retries)

**Comment by saade** [comment]
Nice, i'll try

**Comment by nitesh047** [comment]
> Nice, i'll try

hey..did you try??
I also want to do something like this. Can you help me with this??
