### ISSUE TITLE
persistCallback with React-Native ? 

### ISSUE THREAD

**Issue by KevinGulj** [redux-offline/redux-offline#242]
Hello !
I was wondering if someone could help me with an issue.
I have been using redux-offline for my react web-apps very nicely for quite some time.
But now I have moved to react-native and I ran into a problem with persistCallback.
Does anyone have any suggestions how to handle it in React-Native?  
Instead of React.render() , I have index.js that includes:

`AppRegistry.registerComponent('MyApp', () => App);
`

I cannot export this function as a callback to persistCallback because then react-native will throw:

`
Module AppRegistry is not a registered callable module (calling runApplication)
`

What I tried was 
`export default () => AppRegistry.registerComponent('MyApp', () => App);`

```
import renderApp from "../../../index";
const customOfflineConfig = {
  ...offlineConfig,
  effect: customEffectReconciler,
  discard,
  persistCallback: () => renderApp()
};
```

**Comment by ashconnell** [comment]
@kevingulj redux-offline uses redux-persist by default so theoretically you should be able to use PersistGate from that library 

https://github.com/rt2zz/redux-persist/blob/master/README.md

**Comment by sorodrigo** [comment]
We're not using redux-persist 5 so persist gate will only work if you set up redux-persist 5 yourself (which can be done), otherwise importing the renderApp function should work.

What I personally do is the following:
```js
// offline.js
import offlineConfig from '@redux-offline/redux-offline/lib/defaults';
import { offline } from '@redux-offline/redux-offline';

const config = params => ({
  ...offlineConfig,
  persistCallback: params.persistCallback
});

export default params => offline(config(params));

// main.js
import offline from 'offline';

const startApp = () => {
  // do stuff
}
const store = createStore(
  reducer,
  preloadedState,
  compose(
    applyMiddleware(middleware),
    offline({ persistCallback: startApp })
  )
);
```

**Comment by KevinGulj** [comment]
@carlosbensant Thats pretty much what I eventually did. Although I just listen to the REHYDRATE redux action and then use getDerivedStateFrom props to check if it was dispatched.

**Comment by FranciscoCHT** [comment]
> @carlosbensant Thats pretty much what I eventually did. Although I just listen to the REHYDRATE redux action and then use getDerivedStateFrom props to check if it was dispatched.

How did you listen to the REHYDRATE action in getDerivedStateFromProps?, I'm struggling with the same problem. :(
