### ISSUE TITLE
The store doesn't seem to persist for more than 1 event

### ISSUE THREAD

**Issue by bbigras** [redux-offline/redux-offline#249]
Here's a simple example where I add the current date in an array. If I hit the "add" button more than once, I'll see every dates on my screen but only 1 will be saved in local storage.

https://codesandbox.io/s/jzj0lm89y3

I'm probably doing something wrong.

**Comment by calumpeak** [comment]
Looks to be an issue with your reducer - you were not returning a new list array, but the old one mutated. See an updated version here: https://codesandbox.io/s/j79875wn99

**Comment by bbigras** [comment]
:+1:  Thank you very much.
