### ISSUE TITLE
Implement manual sync?

### ISSUE THREAD

**Issue by kbrandwijk** [redux-offline/redux-offline#25]
I want to use `redux-offline` to implement a manual sync feature in my app. I thought about overriding `config.detectNetwork` and manually return true to trigger the updating.

The only issue I'm facing is that I want to detect when the app is busy syncing. Any pointers on how to implement that part? Ideally I'm looking for a way to detect that the sync is complete.

**Comment by wacii** [comment]
The reducer is found in [updater.js](/redux-offline/redux-offline/blob/master/src/updater.js). Which is admittedly a pretty bad name for it. The key you are interested in is `outbox`. So when `state.offline.outbox.length === 0`, there are no actions left to sync.

Might be worth adding a selector for this...

**Comment by kbrandwijk** [comment]
Thank you for the quick reply. I think I understand at least part of the answer. The `state.offline.outbox` part I get, the reducer part not so much...

**Comment by sebasgarcep** [comment]
@kbrandwijk I think you may be looking for `state.offline.busy`. Is a boolean value that tells you when the app is syncing on the background. @wacii's answer is useful to know if you have pending actions. It really boils down to what you need.

**Comment by wacii** [comment]
When the app is waiting to retry again `state.offline.busy` will be `false` and `state.offline.retryScheduled` will be `true`. Waiting to retry is part of the syncing process, so you will likely want to use both.

I'm not 100% sure that those two values will always accurately represent the state though. There might be frames where they are incorrect.

**Comment by kbrandwijk** [comment]
Thank you @wacii and @sebasgarcep. The 'show it's busy syncing part' seems covered by those states. I'll have to do a bit more experimentation with the manual sync. If I come up with a proper solution, I'll post it somewhere for the docs.

**Comment by sebasgarcep** [comment]
@wacii I didn't know about `state.offline.retryScheduled`. In redux it is recommended that state is normalized, i.e. that there is little to no redundancy in the state you store. Is there any difference between `state.offline.retryScheduled` vs. `state.offline.outbox.length === 0`?

**Comment by wacii** [comment]
@sebasgarcep They are different. `busy` means a request is currently being made to the server and `retryScheduled` means that Redux Offline is currently waiting to make the next request. Either mean that there are still actions left to sync.

There is no redundancy, although you could argue that this state would be better represented by an enum or string or something. Two flags means four states, and there are only three valid ones here (both `busy` and `retryScheduled` should not be true at the same time).

**Comment by sebasgarcep** [comment]
@wacii I was talking about `state.offline.retryScheduled` vs. `state.offline.outbox.length === 0`, but you are right that `retryScheduled` and `busy` cannot be both true at the same time, and that they should better be represented as an enum. Maybe we could rethink some parts of the state and add selectors?
