### ISSUE TITLE
How to handle CRUD offline flow.

### ISSUE THREAD

**Issue by phmngocnghia** [redux-offline/redux-offline#253]
I want to create offline todo-list that work in work both online and offline.. In offline mode, user would add a todo list and then edit and remove that todo list. When connection is back, it would sync to server. How to dermine the id if user want to edit or delete todo that have been added when they offline ?

**Comment by sorodrigo** [comment]
Basically what you want to do is create a todo and when editing, if the created todo hasn’t been synched with the server, edit the create todo values with a custom queue implementation. We’re actually working on a plugin that would automate this. I’ll let you know when it’s out.

**Comment by phmngocnghia** [comment]
Also an options in meta data for specific mutation that update UI before  commit in offline mode would be nice. for example `before commit`:

```js
offline: {
  // the network action to execute:
  effect: { url: '/api/follow', method: 'POST', body: JSON.stringify({ userId }) },
  // The action to update UI
  beforeCommit: {type: 'FOLLOW_USER_OFFLINE', meta: {userId},
  // action to dispatch when effect succeeds:
  commit: { type: 'FOLLOW_USER_COMMIT', meta: { userId } },
  // action to dispatch if network action fails permanently:
  rollback: { type: 'FOLLOW_USER_ROLLBACK', meta: { userId } }
}
```

**Comment by sorodrigo** [comment]
This is already possible by defining the _request_ action payload you can do optimistic updates. See https://github.com/redux-offline/redux-offline/blob/develop/docs/basics/rollback.md

**Comment by piranna** [comment]
@PhmNgocNghia maybe you would be interested in https://github.com/piranna/redux-offline-crud-rest.

Disclaimer: it's mine :-)

**Comment by sorodrigo** [comment]
I think this is cleared now, if anything pops out we can re-open.
