### ISSUE TITLE
How persist/REHYDRATE first

### ISSUE THREAD

**Issue by jlramosr** [redux-offline/redux-offline#257]
Hello,
at first, in my app I have this is the order of my redux actions:
![2018-08-21_09h43_32](https://user-images.githubusercontent.com/6153618/44387785-bba08680-a526-11e8-93d7-182fa82a705c.png)
If I want persist my data at first, I must have installed _redux-action-buffer_ library and call to _createActionBuffer_ method:
```javascript
createStore(
  reducers,
  {},
  composeEnhancers(
    offline(rootConfig),
    applyMiddleware(
      createActionBuffer('persist/REHYDRATE'),
      thunk,
      routerMiddleware(history),
    )
  )
)
```
and then:
![2018-08-21_09h47_10](https://user-images.githubusercontent.com/6153618/44387956-35387480-a527-11e8-895e-7a6b8bd59713.png)

How can I ensure that persist my data at first without using this library? (it seems that it has not been updated for a long time)

Thanks in advance.

**Comment by sorodrigo** [comment]
You need to add a [persistCallback](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#persistcallback)
