### ISSUE TITLE
What about merge / conflict scenarios?

### ISSUE THREAD

**Issue by benvp** [redux-offline/redux-offline#26]
Given an backend with multiple client applications - for example a mobile and a web client. The client updates some data using the mobile application while being offline. Then the user makes some data changes using the web client, which immediately saves the changes to the backend. Now, when the mobile application gets network connectivity again, we technically have a conflict.

How do we choose which data  of the `outbox` queue should be sent to the server and which should be discarded in favor of the newer remote data? Or is this more kind of a backend topic? I haven't dealt with such scenarios yet, but a possible solution which comes to mind is to integrate a timestamp into the request and let the backend decide, if it should accept the changes or not.

**Comment by jevakallio** [comment]
Great question! This will be different for different backend sync strategies, so I don't want to build in too many assumptions. You can now already include timestamps as action metadata, and process them accordingly in your effects handler.

As I've coyly [alluded here, error handling support is still only half-implemented](https://github.com/jevakallio/redux-offline#change-how-errors-are-handled), and client-side state updates to conflict errors definitely fall into that category.

I do want to collect feedback on this, so let's keep this open for now.

Let 's the eventually decide whether there is a general enough approach to implement this in code, or if updating the documentation is a way to go.

**Comment by danalexilewis** [comment]
This is very dependant on what you want to do. 

I would basically divide the cases in two:

1. The data from both devices is desired
2. The most up to date data is desired

Case 1. Will be some sort of logging or creation of new data, eg. Workout entries, time tracking entries, adding a new recipe to a collection, etc...

Case 2. Is typically patching/updating an entry. Updating your workout entry, time log or modifying an existing recipe. In general given multiple change a coming to a backend from multiple devices you should look to use the latest one. eg. User starts updating there profile on a computer in a plane, runs out of power and switches to their mobile. Realised that they have not got the changes from the computer and starts making all there changes again. Ie they expect this to become the truth later - not what's on the computer.

I'd also say that in general offline should not be available for multiple people managing a collection. Eg a library catalog. One person loaning out books/building yard gear from multiple devices is probably ok as they know roughly what they have loaned. But even this is probably not a good idea - there be dragons down this path. I'd probably just try and avoid using offline writing with any centralised catalog system. Maybe instead allow user to create quotes/intentions that could later be reviewed and applied.

Essentially quotes/intentions would just be a log of items so would follow the rules of case 1 and 2 above.

**Comment by pollen8** [comment]
For case 2 you may want to look at operational transformations to merge in changesets. Something like https://github.com/share/sharedb
