### ISSUE TITLE
[Question] How to handle stored API responses if offline?

### ISSUE THREAD

**Issue by SpaghettiC0des** [redux-offline/redux-offline#261]
Sorry for the noob question. ✌️ 

For example:
I have a `FETCH_MESSAGES` action, and fetching data from `api/v1/hello` endpoint. Does it return the same data even if the app is offline?

**Comment by wacii** [comment]
Hmm. To simplify things a bit, Redux Offline will dispatch a commit action when it has successfully completed a request, and a rollback action when it receives a client error. When it fails a request due to other reasons, it just keeps retrying that request until it gets either a successful response or a client error.

When the app is offline, Redux Offline just waits until it gets online again. And then starts retrying requests again. There is no 'returning' really.

**Comment by isaaclem** [comment]
@wacii Thanks for the explanation to help out the newbies like me. I'm wondering if we still need `redux-persist` if we already have `redux-offline`? If we kill the app while there is some request being made, the next time we load the app again, will the requests + whatever previously in the store, still be in the store?

**Comment by wacii** [comment]
@isaaclem Redux Offline includes and configures Redux Persist for you. It does this so that it can persist your requests across sessions. So no you do not need to include it yourself, and yes your previous requests and state are persisted across sessions.

**Comment by isaaclem** [comment]
@wacii : This is probably the best package I've ever came across! Thank you so so much!

**Comment by SpaghettiC0des** [comment]
> Hmm. To simplify things a bit, Redux Offline will dispatch a commit action when it has successfully completed a request, and a rollback action when it receives a client error. When it fails a request due to other reasons, it just keeps retrying that request until it gets either a successful response or a client error.
> 
> When the app is offline, Redux Offline just waits until it gets online again. And then starts retrying requests again. There is no 'returning' really.

@wacii Thanks for your reply! Sorry if I cannot explain it very well, because English is not my native language.

Does that mean `redux-offline` middleware automatically resolves a network request response, even if the app is offline?

For example:
I ran the app for the first time.
1. The app is online: I have a list of messages, then clicking an item will dispatch an ASYNC `READ_MESSAGE` action that will fetch the message data from the API and return a promise, then it successfully gets the message then `redux-persist` stores it using `AsyncStorage`. And then I will navigate to the message viewer screen.
2. The app is offline: I clicked a message item again, does `redux-persist` automatically returns a `Promise` with the resolved value from the offline data?

**Comment by calumpeak** [comment]
@karlmarxlopez `redux-offline` will store the decorated offline action in a queue (data does not get fetched all at once, it's a FIFO queue so redux-offline processes the requests in order), it does not return a promise, it will only dispatch actions. It works on optimism - you can react to the offline action immediately as it goes through your reducers. The network request won't be made until you come back online, at which point you will get either your `commit` or `rollback` action dispatched to your reducers with the data from the server - it's then down to the reducers to decide what to do with that data.

Would advise reading further into our docs on [write resilience ](https://github.com/redux-offline/redux-offline/blob/develop/docs/basics/write-resilience.md) and [commit ](https://github.com/redux-offline/redux-offline/blob/develop/docs/basics/commit.md)/[rollback](https://github.com/redux-offline/redux-offline/blob/develop/docs/basics/rollback.md)

**Comment by isaaclem** [comment]
@echoes221 : 

> it's then down to the reducers to decide what to do with that data

Is it means that we handle the server response at reducer level instead of Action level? Is it actually better to handle at reducer as all this while data massaging i've been handling it at action level

**Comment by calumpeak** [comment]
@isaaclem Well the data from the server is dispatched by your specified action in the `commit` or `rollback` so you can only really handle that 'naked' (data just lives in `action.payload`) data in a middleware/side-effect or the reducer itself. It's difficult to handle it in the action itself as redux-offline handles the actions in a generic way, and as the action has to be a plain object, can only be lightly decorated before it's dispatched to redux-offline.
