### ISSUE TITLE
redux-offline & redux-form submissionError

### ISSUE THREAD

**Issue by maartendra** [redux-offline/redux-offline#262]
Hi! Thanks so much for redux-offline, it's working like a charm!

One question though, I'm now trying to implement to show server side validation errors within my forms. But I just don't know how to stitch this (https://redux-form.com/7.4.2/docs/api/submissionerror.md/) together with redux-offline.

For example, this is my login action:

```js
export const login = ({ email, password }) => ({
  type: 'LOGIN_REQUEST',
  payload: { email, password },
  meta: {
    offline: {
      effect: { url: `${API_URL}/auth/login`, method: 'POST', data: `email=${email}&password=${password}` },
      commit: { type: 'LOGIN_COMMIT', meta: { email, password } },
      rollback: { type: 'LOGIN_ROLLBACK', meta: { email, password } },
    }
  }
});
```

Where and how should I throw the `submissionError()`? Does perhaps anyone have an example of how this would work?

Thanks!

**Comment by wacii** [comment]
[returnPromises](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#returnpromises) documents...ok, briefly discusses using the promise returned by `store.dispatch()`. So you could:

```js
store.dispatch(login()).catch(_error => throw new SubmissionError());
```

You have to opt-in to this feature in the offline config.

**Comment by maartendra** [comment]
@wacii Aah, nice! It's working, thanks!

```js
class Login extends Component {
  login = values => {
    return this.props.login(values).catch(error => {
      throw new SubmissionError(error.response.data.errors)
    });
  };

  render() {
    return <LoginForm onSubmit={this.login} />;
  }
}
```
