### ISSUE TITLE
put a hold on queue

### ISSUE THREAD

**Issue by Adwich** [redux-offline/redux-offline#266]
Hello everyone,

first of all I want to thank you guys for this amazing package.

I have a use case that I can't find the solution to. Is it possible to put a hold on the queue until further notice.

Here is my case. The user has a token and a refresh token. If for any reason the refresh token came to be expired I want the user to login again and meanwhile stop the execution of the queue. How could I stop redux-offline's execution of the queue in while my user is doing another login ?

thank you guys

**Comment by sorodrigo** [comment]
I can think of 2 ways, the first is to implement a custom queue that won’t dequeue until the token is valid again, sounds a little complicated.

The other one is to dispatch the redux-offline busy action. When the busy state key equals true, the whole execution of the middleware is paused.

I believe this feature is not fully documented, don’t expect to change it anytime soon but be aware of that.

**Comment by Adwich** [comment]
Hello @sorodrigo, thank you for your answer. I too think that the second option is the simpler one. Could you explain how to dispatch the busy action ?

**Comment by Adwich** [comment]
I think I found it but my question is : if the app is killed, does the busy boolean keeps its value or is it reset to false ?

```
import { OFFLINE_BUSY } from "@redux-offline/redux-offline/lib/constants";

store.dispatch({ type: OFFLINE_BUSY });
```

**Comment by sorodrigo** [comment]
Sorry been a lil busy, it would keep its value until you change it again.

**Comment by Adwich** [comment]
That's great thank you @sorodrigo. But i'm running into another trouble. It is in my discard function that i detect that the token is invalid and need refreshing. And the function that refresh the token is called during the discard function. If the refresh token is invalid I call the busy action and resolve the discard function. The thing is that the discard function updates the busy to false. So redux offline keeps executing the queue. Could I make it that the discard function would not update the busy boolean ?

**Comment by Adwich** [comment]
After looking more in-depth into how redux-offline works I think i would
need to edit the `finally` on the `send` core-function so that it would not
dispatch the busy action and reset. But it would require to change the
library's core. Do you have a better approach ?

**Comment by sorodrigo** [comment]
Ha! That's a nice solution! 👍

**Comment by ForumT** [comment]
@sorodrigo  Hi what exactly did you do to fix this? can you show what your peek function looks like?

**Comment by calumpeak** [comment]
@ForumT You'd need to do a little closuring/scoping but the general gist looks something like this
```javascript
function peek(outbox, action, { offline }) {
  if(!refreshToken) {
    return false;
  }

  return outbox[0];
}
```

**Comment by ForumT** [comment]
@echoes221 Thanks for the response. This code works fine. But I am embarrassed now. The execution pauses alright and I have a button to restart execution. So my outbox empties alright. But when i try creating things offline/online again, the effect is never triggered. My queue looks like so:

    queue: {
        ...defaultQueue, 
        peek(outbox, action, { offline }) {
            if (store.getState().commonDetails.pauseQueue) return false;
           return outbox[0];
        },
     },

**Comment by ForumT** [comment]
@echoes221 : I was able to figure out the issue. I also had a custom effect method with axios request. Removing that fixed the problem. Thanks!

**Comment by calumpeak** [comment]
@ForumT Awesome, glad it worked :)
