### ISSUE TITLE
[Question] How `config.retry` works?

### ISSUE THREAD

**Issue by dsinecos** [redux-offline/redux-offline#267]
Please help me clear up my understanding of how `config.retry` works.

If my outbox has two actions - 1. A GET request 2. A POST request. Suppose the first action - GET request - fails. Is it retried until successful before moving on to the next action in the outbox?

Considering the default implementation of `retry` if the GET request fails the first time, which of the following would happen

1. GET request fails. Wait for 1 second. Send the GET request. (Assuming the GET request is successful this time) Send the POST request

2. GET request fails. Send the POST request. After the lapse of 1 second, send the GET request again

Thanks :)

**Comment by calumpeak** [comment]
Scenario 1 will happen. As the order of the outbox queue is important, we retry the action from the queue head.
If other connected actions in the queue need to amended on failure of an action (when it's dequeued) then you have the ability to do that from creating a custom queue implementation to handle that via the config.

**Comment by dsinecos** [comment]
Thanks @echoes221 :)
