### ISSUE TITLE
finally is not a function

### ISSUE THREAD

**Issue by Flofie** [redux-offline/redux-offline#269]
The promise implementation of angular doesnt have a finally function. If I remember correctly finally is not part of the Promise standard.
The current version 2.4.0 uses finally here: https://github.com/redux-offline/redux-offline/blob/develop/src/send.js#L72
since it is not there in the angular implementation an error gets thrown and nothing gets send to the server.
Version 2.3.3. work perfectly thou.

**Comment by calumpeak** [comment]
@Flofie [Promise.finally](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally) is part of the Promise standard. The change between version 2.3.3 and 2.4.0 was to fix a small action consistency regression (#233).  I would advise to use the `promise.prototype.finally` shim which can be found [HERE](https://www.npmjs.com/package/promise.prototype.finally) and is the recommended one as proposed by [tc39](https://github.com/tc39/proposal-promise-finally).

**Comment by Flofie** [comment]
Thanks for clearification. I use the shim and everything is fine.

**Comment by jfbloom22** [comment]
if anyone is interested in quickly adding the shim for promise.finally:
`npm install promise.prototype.finally`

Then somewhere in the initial launch of your app:

```
const promiseFinally = require('promise.prototype.finally');
promiseFinally.shim();
```
I was having an issue in MS Edge where offline.busy was stuck to true after a successful Post call. This shim fixed the issue.

**Comment by sorodrigo** [comment]
Would you like to add this to our docs?
