### ISSUE TITLE
Commit and Rollback should be optional

### ISSUE THREAD

**Issue by Bhullnatik** [redux-offline/redux-offline#27]
Pretty much following up on this issue https://github.com/jevakallio/redux-offline/issues/72 in this repo since it is actively maintained.

What do you think? That seeems like a reasonable idea, as you don't necessarily want to dispatch a commit/rollback action for every offline action, for example in the case of an optimistic update (as shown in examples in the README).

**Comment by sebasgarcep** [comment]
I personally agree with this. The change is simple and it will not break the library. @sorodrigo @wacii Any thoughts?

**Comment by wacii** [comment]
Yeah, I'm fine with this. Not sure that I can think of a situation where I wouldn't want to be notified of a failure, but there is no reason for the library to impose that.

**Comment by sorodrigo** [comment]
I'm not sure about the use case. If you don't want to be notified about a failure, why not use an effect outside of `redux-offline`? I get that you might want to take advantage of the retry strategy, but then again why not add a rollback action in case it doesn't succeed? However this isn't a breaking change so not sure I disagree either

**Comment by sebasgarcep** [comment]
I have an use case right now where an action updates the local database and then syncs with the backend. These actions will be retried until they succeed and no conflict resolution has to be done on them, so they eventually will. Doing these actions outside of `redux-offline` means I have to reinvent the wheel to have a retry strategy in place, which doesn't make any practical sense. Unless I'm doing something wrong, I think this might be a valid use case.

**Comment by sebasgarcep** [comment]
#30 Solves this.
