### ISSUE TITLE
Can someone please provide a proper Demo App?

### ISSUE THREAD

**Issue by VatsaPatel** [redux-offline/redux-offline#271]
Please provide a proper Demo App which properly implements and demonstrates offline functionality.

**Comment by sorodrigo** [comment]
What do you mean by _proper demo app_?

We have an example app where you can test how the library works. It would be amazing to have a real-life example app, but I currently don't have time to build it.

All of the maintainers and contributors do it on their free time in exchange of nothing. So please take that in mind when you ask for someone to provide a _proper demo app_.

We're always happy to receive pull requests, specially when it's regarding documentation 😄 ! So if feel up for the challenge, I invite you to create such app and make a PR so we can link to it!
