### ISSUE TITLE
Can we send a thunk in commit or rollback ?

### ISSUE THREAD

**Issue by seharconrad** [redux-offline/redux-offline#273]
Hi
I am using Redux thunk as one of my middleware. Can i send a thunk instead of actions in commit or rollback.If can please guide me how to do that
 "@redux-offline/redux-offline": "^2.4.0"
"redux-thunk": "^2.2.0"

**Comment by calumpeak** [comment]
You cannot use thunks in commit/rollback as the actions have to be serialisable and must be simple objects. You may have some luck with the experimental [return promises](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#returnpromises) spec, but I don't think it's ready for the limelight yet.

Personally I would use a custom bit of middleware, or something like [Redux-Observable](https://redux-observable.js.org/) (I use this in production in tandem with redux-offline and it works really well) or [Redux Saga](https://github.com/redux-saga/redux-saga) and handle commit/rollback actions as side effects and do further computation from there

**Comment by seharconrad** [comment]
Can you show me an example on how to use redux-observable with redux- offline

**Comment by calumpeak** [comment]
You should be fine to setup redux-offline as normal and and setting up Redux-Observable as per their docs which are linked above.

**Comment by sorodrigo** [comment]
I personally prefer `redux-saga` because you don't have to learn observables 😛 .
