### ISSUE TITLE
Broken types in typings.d.ts in typescript project  

### ISSUE THREAD

**Issue by IvMalakhov** [redux-offline/redux-offline#274]
I tried to connect redux-offline to empty TS react project and get this error :
```
.../node_modules/@redux-offline/redux-offline/typings.d.ts
(107,24): Parameter 'number' implicitly has an 'any' type.
```
connect 
```
import { Store, createStore, applyMiddleware, compose } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension';
import { offline } from '@redux-offline/redux-offline';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults';

import rootReducer from './index';

const middleware = composeWithDevTools(compose(applyMiddleware(), offline(offlineConfig)));
export const store: Store<any> = createStore(rootReducer, middleware);

```

i think the problem here:
node_modules/@redux-offline/redux-offline/typings.d.ts
```
    offlineActionTracker: {
      registerAction: (number) => Promise<any> | (() => void),
      resolveAction: (number, any) => void | (() => void),
      rejectAction: (number, Error) => void | (() => void)
    }
```

json 
```
{
  "name": "empty-ts-project",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@redux-offline/redux-offline": "^2.4.0",
    "react": "^16.5.0",
    "react-dom": "^16.5.0",
    "react-redux": "^5.0.7",
    "react-scripts-ts": "2.17.0",
    "redux": "^4.0.0"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/jest": "^23.3.1",
    "@types/node": "^10.9.4",
    "@types/react": "^16.4.13",
    "@types/react-dom": "^16.0.7",
    "@types/react-redux": "^6.0.9",
    "@types/redux": "^3.6.0",
    "redux-devtools-extension": "^2.13.5",
    "typescript": "^3.0.3"
  }
}
```
may be  i do somthing wrong ?

**Comment by zshanhui** [comment]
Yes, hello. I came across the same problem with Typescript. Is there any fixes?

**Comment by jonatanpineda** [comment]
I solved that error by setting false "noImplicitAny" in compiler options of my tsconfig.json 
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    //setting false
    "noImplicitAny": false,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```

I don't know the disadvantages of that but redux-offline is working with typescript.

**Comment by zshanhui** [comment]
@JonatanPineda Well, if we are using Typescript, then we'd want the strict type checkings of Typescript and would not be desirable to turn it off.

**Comment by sorodrigo** [comment]
I haven’t used R-O with typescript but I believe @echoes221 may be able to help you

**Comment by calumpeak** [comment]
Just about to use RO with TS so i'll take a look.

**Comment by calumpeak** [comment]
@IvMalakhov I've tested this, you're running an old version, please update to v2.5.0 which has the updated typings for `offlineActionTracker`. See release https://github.com/redux-offline/redux-offline/releases/tag/2.5.0

@sorodrigo I've found an issue regarding `createOffline` when we've integrated with TS. 

This:
```typescript
export const createOffline: (userConfig: Config) => ({
    enhanceReducer: (reducer: any) => (state: any, action: any) => any,
    enhanceStore: (next: any) => <T extends { [key: string]: any }>(
      reducer: (state: T, action: any) => T,
      preloadedState: T,
      enhancer: StoreEnhancer<T>,
    ) => Store<T>,
    middleware: (api: MiddlewareAPI<any>) => (next: Dispatch<any>) => Dispatch<any>,
})
```
gives this as error when middleware is consumed by redux `applyMiddleware`:

```
Argument of type '(api: MiddlewareAPI<any, any>) => (next: Dispatch<any>) => Dispatch<any>' is not assignable to parameter of type 'Middleware<any, any, any>'.
  Type '(next: Dispatch<any>) => Dispatch<any>' is not assignable to type '(next: Dispatch<AnyAction>) => (action: any) => any'.
    Types of parameters 'next' and 'next' are incompatible.
      Types of parameters 'action' and 'action' are incompatible.
        Type 'T' is not assignable to type 'AnyAction'.
```

It should be:

```typescript
export const createOffline: (userConfig: Config) => ({
    enhanceReducer: (reducer: any) => (state: any, action: any) => any,
    enhanceStore: (next: any) => <T extends { [key: string]: any }>(
      reducer: (state: T, action: any) => T,
      preloadedState: T,
      enhancer: StoreEnhancer<T>,
    ) => Store<T>,
    middleware: Middleware
  });
```

We can explicitly use the `Middleware` type from `redux` to handle this - I will raise a PR to get this fixed.

**Comment by sorodrigo** [comment]
This rings a bell, just remember that I was investigating how to type redux stuff and I think that I didn't know what to do atm.  There were some breaking changes from v3 to v4 just in terms of typescript, so we need to settle which version we support.

EDIT:
See https://github.com/redux-offline/redux-offline/pull/228

**Comment by calumpeak** [comment]
Yup, I saw the change history for it. The ‘Middleware’ typing is near enough identical, it just uses the correct generics passing through. We should try and use Redux’s typings where possible as when they update, we update. 
On the case of v3 ➡️V4 there were no breaking changes, more documentation improvements so I think we’re safe to update this, see: https://github.com/reduxjs/redux/issues/1342

For now we can fix this on our side by assigning it where we use it (middleware as Middleware) but we should fix this for everyone . I have a pr ready, will push it up later.

**Comment by sorodrigo** [comment]
Ok sounds great! I don't use typescript that often so I felt more less like this last time 😅 

![dont know what Im doing](http://thumbpress.com/wp-content/uploads/2013/05/I-Have-No-Idea-What-Im-Doing-1.jpg)
