### ISSUE TITLE
Can we have some actions without the offline meta?

### ISSUE THREAD

**Issue by himanshusharma9400** [redux-offline/redux-offline#275]
I have both type of actions in my app some have offline meta and some have not(because I don't want them to have).But in a scenerio where the app is offline and then som offline actions are executed and then a non offline action is executed it gets network error but due to that the **offline action's rollback is executed** which should not happen.The rollback message is as follows:
{type: "UPDATE_TASK_ROLLBACK", meta: {…}, payload: TypeError: Network request failed
    at XMLHttpRequest.xhr.onerror (blob:http://localhost:8081/ae71…}
I don't think this is normal behaviour as I expected rollback should'nt have happened or even effect should'nt have triggered as app was offline so can you tell me what am I doing wrong or a way by which I can have both type of actions(with offline meta and without them)
My store is:
const config = {
    ...offlineConfig,
    persist:false,
  };
const {
    middleware: offlineMiddleware,
    enhanceReducer: offlineEnhanceReducer,
    enhanceStore: offlineEnhanceStore
  } = createOffline({
    ...config
});
  const persistConfig = {
    key: 'root',
    storage,
    whitelist:['offline','_persist']
  };
  const persistedReducer = persistReducer(
    persistConfig,
    offlineEnhanceReducer(AllReducers)
  );
export const store =  createStore(
    persistedReducer,
    compose(
        offlineEnhanceStore,
        applyMiddleware(thunk,logger,offlineMiddleware)
    )
);
export const persistor = persistStore(store);

**Comment by calumpeak** [comment]
Hi @himanshusharma9400, I see you're using the custom setup for redux-offline. Can you please ensure that you follow the [setup docs ](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/createOffline.md) correctly (order of arguments to `createStore` matters). `redux-offline` uses `redux-persist` under the hood so there should be no need to setup your own instance of `persistReducer`. If you need to update the persist config, you can do that via `redux-offline`'s [config](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md) under the `persistOptions` key. 

If that doesn't work, please provide a codepen so that we can help debug your problem further.

**Comment by himanshusharma9400** [comment]
Yes I have tried all combinations in createStore but same result, also I haven't used redux-offline provided persistOptions as I am using redux-persist-v5 and using persist gate and persisting some nested properties of state only and it is working perfectly fine for me i.e I have all state which I need to persist and also the outbox is persisting.The only problem I am facing is when **app is in offline mode the actions which doesn't use offline meta generate network error when triggered, due to which the offline actions which were in outbox before this, there rollback method gets called and hence gets removed from the outbox.**
         Also in offline mode when only the offline meta actions are called they run perfectly fine i.e they do not commit or rollback just get added in queue or outbox and when app gets online they are executed successfully.
        When app is online all actions works fine whether offline meta actions or normal actions.
My actions are somewhat linke these:
Offline:
export function updateTask(jobId,payload,userData){
    return {
        type:actionTypes.UPDATE_TASK_OPTIMIST,
        payload:{msg:'UNSYNCED',jobId:jobId,jobStatus:userData.pl.jb_sts},
        meta:{
            offline:{
                effect:{url:apiConstants.API_SERVER_HOST + "/jobs/" + jobId, method:'POST', body:JSON.stringify(userData)},
                commit:{
                    type:actionTypes.UPDATE_TASK_COMMIT,
                    meta:{msg:'OK'}
                },
                rollback:{
                    type:actionTypes.UPDATE_TASK_ROLLBACK,
                    meta:{msg:'ERROR'}
                }}}}}
And action without offline:
export function fetchAllTasks(payload,userData){
    return (dispatch) => {
        dispatch(startFetchAllTasks())
        RESTApi.POST('jobs/search', payload, userData,(data) => {
            if(data)
            dispatch(saveAllTasks(data))
        }, (error) => {
            dispatch(errorFetchingAllTasks(error))
        })
    }
}
export function startFetchAllTasks(){
    return {
        type:actionTypes.START_FETCH_ALL_TASKS
    }
}
export function saveAllTasks(payload){
    return{
        type:actionTypes.SAVE_ALL_TASKS,
        payload:payload
    }
}
export function errorFetchingAllTasks(error){
    return{
        type:actionTypes.ERROR_FETCHING_ALL_TASKS,
        payload:error
    }
}

**Comment by himanshusharma9400** [comment]
@echoes221 ,I have read some issues and some of them are somewhat related to mine eg: #23 .I think this issue may be arising due to the two middleware.

**Comment by calumpeak** [comment]
@himanshusharma9400 I'm assuming you found the issue? If you can please document for others if they run into it.
