### ISSUE TITLE
Rollback event called on actions when network error occurs.

### ISSUE THREAD

**Issue by himanshusharma9400** [redux-offline/redux-offline#276]
When the device is on a weak network with low internet connectivity then rollback event is called immediately.
Steps to reproduce:
Create a wifi-hotspot from another device and set the mobile network off and connect your test device to that wifi.Then whenever the event is being triggered the network error occurs and rollback is triggered immediately.Also the network status shows offline:true.
Also I'm using the default offlineConfig
Expectation:
I think in such a case the network status should detect this and show online as false or it should retry again and should not rollback immediately.
PS:Actually I'm creating an app for such a scenerio where the people using them may have a weak connectivity so I don't want ever to trigger a rollback when a network error happens.

**Comment by calumpeak** [comment]
Hi @himanshusharma9400 Redux-offline uses [Navigator.onLine](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine) which:

> if the browser is not able to connect to a local area network (LAN) or a router, it is offline; all other conditions return true. So while you can assume that the browser is offline when it returns a false value, you cannot assume that a true value necessarily means that the browser can access the internet

This only checks to see if you have connection to a network, not the internet. This is a limitation of the native browser implementation, but redux-offline aims to be as light as possible in this regard.

I would advise:

- Configuring network detect to use a strategy of your choosing (perhaps a '/ping => 200 OK' endpoint on your server and setup a polling endpoint (websocket/server sent event would be less noisy in the network tab), that way you know that you definitely have an internet connection to make the requests. There are libs that can help with this too
- Configuring the discard config to retry if the network error is todo with the server being unreachable/network connectivity

**Comment by himanshusharma9400** [comment]
So I guess this is normal behaviour when network connection is there but no internet connectivity.So is there a way where ,I can keep retrying in fixed interval(say 1 min) indefinitely when this case(no internet connectivity) occurs and retry in default way when other cases occurs(like server error etc.)

**Comment by calumpeak** [comment]
Yeah - I'd configure `discard`, it receives the error (and therefore the status code) as part of the arguments, you should be able to work out what you want to do with that. You could also configure your retry to handle that too.
Ideally you should augment the [network connection](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#detectnetwork)via the config however, else you're just jumping through hoops to solve it in a roundabout way instead of solving the root problem. A simple implementation with socket.io/websockets (it has connected/disconnected handlers) to ensure a steady connection to your server would suffice.

**Comment by himanshusharma9400** [comment]
@echoes221 
I found this to check the internet connectivity:

NetInfo.isConnected.fetch().then(isConnected => {
  console.log('First, is ' + (isConnected ? 'online' : 'offline'));
});
function handleFirstConnectivityChange(isConnected) {
  console.log('Then, is ' + (isConnected ? 'online' : 'offline'));
  NetInfo.isConnected.removeEventListener(
    'connectionChange',
    handleFirstConnectivityChange
  );
}
NetInfo.isConnected.addEventListener(
  'connectionChange',
  handleFirstConnectivityChange
);

but I'm not quite sure how to implement and integrate this within the plugin or will this even work?
