### ISSUE TITLE
POST API call with offline effect not working.

### ISSUE THREAD

**Issue by pcnayak** [redux-offline/redux-offline#279]
I am trying to call a REST API to post data using the offline effect. Although the method gets called the data is not getting passed. 
When I try the same using a Fetch Async call it works. Can someone point me what I am doing that is not correct?

export const createTodoWithId = (userId, content, status, tempId) => {
    
     return {
      type: CREATE_TODOS_REQUEST,
      payload: { 
                 userId, 
                 content, 
                 status,
                 tempId
                },
      meta: {
        offline: {
            // the network action to execute:
            effect: { 
                        url: 'http://localhost:4321/todos', 
                        //body: `userId=${userId}&content=${content}&status=${status}`
                        //json: {userId  ,content , status } 
                        method: 'POST',
                        headers: {
                            'Accept': 'application/json',
                            'Content-Type': 'application/json'
                        },
                        body:  JSON.stringify({
                            userId: 'PCN', 
                            content: 'Its not working!', 
                            status: 'Doing'
                        })
                    },

            // action to dispatch when effect succeeds:
            commit: { type: CREATE_TODOS_COMMIT, meta: { userId, content, status, tempId } },
            // action to dispatch if network action fails permanently:
            rollback: { type: CREATE_TODOS_ROLLBACK, meta: { userId, content, status, tempId} },
        }
      }
    }
  }

**Comment by pcnayak** [comment]
The error I get from the API is
"ToDo validation failed: userId: Path `userId` is required., content: Path `content` is required., status: Path `status` is required."

**Comment by sorodrigo** [comment]
Sorry there's features in develop that haven't been released yet. This shouldn't happen, I will release the develop branch soon. In the meantime you can use:
```js
{
  effect: { body: JSON.stringify({userId  ,content , status }) }
}

**Comment by pcnayak** [comment]
This is the store.js and App.js files

import { createStore, applyMiddleware, compose } from 'redux';
import { offline, createOfflineStore } from 'redux-offline';
import offlineConfig from 'redux-offline/lib/defaults';
import thunk from 'redux-thunk';
import {createLogger} from 'redux-logger';

import reducer from '../redux/reducers/index';

const logger = createLogger();
const store = createStore(
  reducer,
  undefined,
  compose(
      applyMiddleware(thunk, logger),
      offline(offlineConfig)
  )
);

export default store;




import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Provider } from 'react-redux';

import store from './src/redux/store';
import Main from './src/components/Main';

export default class App extends React.Component {
  render() {
    return (
      <Provider store={store}>
        <Main />
      </Provider>
    );
  }
}

**Comment by pcnayak** [comment]
Also here is my package.json 

  "@redux-offline/redux-offline": "^2.4.0",
    "eslint-config-rallycoding": "^3.2.0",
    "lodash": "^4.17.11",
    "react": "^16.6.0-alpha.8af6728",
    "react-native": "^0.57.3",
    "react-redux": "^5.0.7",
    "reactotron-react-native": "^2.1.0",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.5",
    "redux-logger": "^3.0.6",
    "redux-offline": "^2.0.0",
    "redux-persist": "^5.10.0",
    "redux-promise": "^0.6.0",
    "redux-thunk": "^2.3.0",
    "uuid": "^3.3.2"

**Comment by pcnayak** [comment]
Also I tried with the @ redux-offline/redux-offline 2.5.0 and  body: JSON.stringify({userId  ,content , status }) , still had the same issue. Data was not passed to the backend API.

**Comment by pcnayak** [comment]
I updated the references as suggested, but it still doesn't work. Also I removed the redux-promise. I am not using this.

**Comment by pcnayak** [comment]
Do you have a project set up where you tested this?

**Comment by sorodrigo** [comment]
You can check the `examples/` directory we have a small react app using it.

**Comment by pcnayak** [comment]
I have checked the examples, what I see is for POST requests to use  json: { userId } OR  body: `name=${name}&email=${email}`

I have still not been able to make it work.

**Comment by sorodrigo** [comment]
Sorry I can’t be of more use without a live example. Perhaps you could copy/paste the default effect into your config and pass it as custom. Then you could add a debugger and try to see what’s going on. If you can provide a code example using code sandbox we might be able to help you.
