### ISSUE TITLE
Exit browser and re-enter - outbox is emptied with no request being made.

### ISSUE THREAD

**Issue by Ryan8765** [redux-offline/redux-offline#281]
### Are you using `offline()` or `createOffline()` API?
No

### Store config
Please paste your config below.
```js
const store = createStore(rootReducer, compose(
    applyMiddleware(thunk),
    //window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__(),
    offline(offlineConfig))
);
```

### Offline config

Are you using a custom configuration? If you are please paste your config below.
```js
Default configuration
```
I am a little new at this - so bear with me.  I have redux offline hooked up to my application and under the following condition it is working:

- If I disconnect the internet and send a request, don't close out of the browser, and then turn the internet back on - the request fires away as expected an all is good (rollback and commit is working great). 

The problem I am running into is the following:

- If I turn off the internet, then close out of the browser, then open my application again in the browser I can inspect the outbox array and see the effect waiting to get fired off when I connect to the internet.  I connect the internet and watch the outbox empty - the only problem is it is not triggering the commit or the rollback it seems - it is just clearing the outbox with no network request being made at all.  Am I missing something in the configuration that I should be doing (I am using the default configs?).

**Comment by sorodrigo** [comment]
Hello!! What you're describing sounds like a bug. However I was unable to reproduce it using the latest version (`2.5.0`).    
If you see in the next 2 images, I reopen a tab with online status to false and the outbox is empty. 

<img width="859" alt="screen shot 2018-11-08 at 01 10 51" src="https://user-images.githubusercontent.com/12124839/48169394-71dc6680-e2f3-11e8-9791-d08643a4bf52.png">

Afterwards the redux-persist rehydrate kicks in and I have 3 actions on the outbox. Finally as you can see all the actions are completed and its commit action dispatched after online status changed.

<img width="751" alt="screen shot 2018-11-08 at 01 11 09" src="https://user-images.githubusercontent.com/12124839/48169476-bd8f1000-e2f3-11e8-8f1e-64195ddd545c.png">

If you're able to submit a reproduction of the bug I can give it a go.

**Comment by Ryan8765** [comment]
Maybe that is my issue - the version number.  When I try to force a 2.5 install (npm install redux-offline@2.5.0 --save) it errors though telling me that version is not available.  My package-lock.json is showing:

```
"redux-offline": {
      "version": "2.0.0",
      "resolved": "https://registry.npmjs.org/redux-offline/-/redux-offline-2.0.0.tgz",
      "integrity": "sha1-WJbpVHdBfIFz4IP08tl3Rm7JGAg=",
      "requires": {
        "redux-persist": "4.10.2"
      }
   }
```
and package.json:

`"redux-offline": "^2.0.0",`

**Comment by sorodrigo** [comment]
I see the problem you have is that the library is now under `@redux-offline/redux-offline` name

**Comment by Ryan8765** [comment]
That solved the issue.  Thanks for the help.
