### ISSUE TITLE
[question] Do you support Immutable.js as root initialState and combineReducers from `redux-immutable`

### ISSUE THREAD

**Issue by JustFly1984** [redux-offline/redux-offline#282]
I'm using immutable.js for most of my projects in redux, and I'm thinking to use offline with workbox webpack plugin. Is `redux-offline` compatible with my kind of architecture?

**Comment by sorodrigo** [comment]
Yes R-O is compatible with the immutableJS lib. In the future we might migrate to the latest redux-persist and this will make it incompatible with immutable root state. However if we decide to do this a new breaking change version would be released.

**Comment by JustFly1984** [comment]
Well, immutable state is useless if root reducer mutable. At least in Redux
case.

**Comment by sorodrigo** [comment]
Please check the docs https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/immutable.md

**Comment by 7ErAz7** [comment]
as said in docs, it's configurable to use with immutable root state, will this be possible to config even after the migration you mentioned above?

**Comment by JustFly1984** [comment]
Well, immutable.js is kind of unmaintained for long time, and looks like nobody cares much. I had switched to immer for all my newer projects anyway.

**Comment by 7ErAz7** [comment]
Yes, I've also changed my mind once I considered immer, I thank god that I found immer and did not go ahead with immutable.js
Great thanks to @mweststrate
