### ISSUE TITLE
API Request header Content-Type auto append application/json?

### ISSUE THREAD

**Issue by isaaclem** [redux-offline/redux-offline#288]
I'm using Reactotron as debugging tool and noticed that eventhough I've specified header content-type to be `application/x-www-form-urlencoded`, it seems like content-type will become `
application/json,application/x-www-form-urlencoded` instead.

**Comment by isaaclem** [comment]
```
      const ax = axios.create({
        timeout: 30000,
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded'
        },
        cancelToken: cancelTokenSourceLogin.token
      });

      // Attempt register operation
      ax.post(urljoin(API_BASE_URL, API_ENDPOINT_JOB, id, API_ENDPOINT_UPDATE), {
        body: JSON.stringify({
          json: JSON.stringify(body)
        })
      })
      .then(({ data }) => {
        console.log('DEBUG::success!!! data::', data);
      })
      .catch((err) => {
        console.log('DEBUG::err', err);
      }); 
```

I've tried to change to the above format and the tracked `request header` looks correct

**Comment by sorodrigo** [comment]
Hmmm interesting, I think I might know what's going on 🤔 . Could you try setting the header as
`{ 'content-type': 'application/x-www-form-urlencoded' }`

**Comment by isaaclem** [comment]
@sorodrigo : Yeap value for `content-type` is showing correctly now but at the same time im seeing extra `header`: `accept: application/json, text/plain, */*` ?

**Comment by isaaclem** [comment]
@sorodrigo : Kindly ignore my previous comment which I've deleted to avoid confusion for future readers. Your solution is working fine, so the problem seems to be due to case sensitivity. Thanks a lot!

**Comment by sorodrigo** [comment]
No problem, actually I do think this is a bug. If I'm not mistaken that header should be valid in both formats, we should make changes so that users don't face this problem again!
