### ISSUE TITLE
Sagas

### ISSUE THREAD

**Issue by valinaga** [redux-offline/redux-offline#29]
How does this play withe redux-sagas? I use sagas instead of redux thug and I wonder how to add it to redux-offline. Thanks

**Comment by rationalthug** [comment]
It seems like it should integrate seamlessly with redux-saga. Redux-offline is promise based, so you could simply use it inside of your sagas with whatever network lib/effects code you want and trigger actions based on the result.

**Comment by JonatanGarciaClavo** [comment]
I was trying to make it happens, and I couldn't accomplish it, because actions made by redux-offline never propagates to other middlewares like redux-saga, so if someone could tell us how to make it works I will appreciate it.

**Comment by JonatanGarciaClavo** [comment]
BTW i guess that because other libs like redux-logger and redux-devtools are not working too.

**Comment by wacii** [comment]
Redux Offline has been updated and now plays better with other libraries. There is also a new `createOffline()` api that lets you decide exactly where you want the offline middleware in your middleware chain.

If you still have problems integrating with `redux-saga`, please open a new issue.

**Comment by JonatanGarciaClavo** [comment]
@wacii could be nice to add more info about how to integrate it, because I can't found it also i am not sure how i should integrate it. I will check it and if i have doubts i will let you know

**Comment by JonatanGarciaClavo** [comment]
@wacii no clue how to use createOffline() together with other settings, could you provide a little example of it please?

**Comment by wacii** [comment]
There is an example in the documents [here](https://github.com/redux-offline-team/redux-offline#choose-where-the-offline-middleware-is-added). The `config` variable passed to `createOffline()` is the same configuration object described [here](https://github.com/redux-offline-team/redux-offline#configuration).

**Comment by tadeo** [comment]
[Updated createOffline doc link](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/create-offline.md)
