### ISSUE TITLE
How can we look in to XHR logs

### ISSUE THREAD

**Issue by navneetgarggate6** [redux-offline/redux-offline#293]
I am trying to view the XHR log request but there is no log in network tab of chrome can any one tell me how we can view the XHR logs?

**Comment by calumpeak** [comment]
Can you please clarify? If you're offline then there will be no XHR logs. We only make requests when the user is online.

**Comment by navneetgarggate6** [comment]
We are not offline. We are testing our app online but we are not able to view the XHR logs. Can you please tell us the setting by which we can disable offline feature (always work online) of our testing and see the XHR logs?

**Comment by calumpeak** [comment]
There is no setting such as that. If you're online you should see your XHR logs go out as normal in the network tab when you make a request.

**Comment by navneetgarggate6** [comment]
Ok, thanks let me check the code again and find out why are XHR logs not visible?
Thanks again
