### ISSUE TITLE
This lib just work properly with Debug JS Remotely activated?

### ISSUE THREAD

**Issue by rodrigofbm** [redux-offline/redux-offline#298]
### Are you using `offline()` or `createOffline()` API?
`createOffline(

### Store config
Please paste your config below.
```js
import { createStore, applyMiddleware } from 'redux';
import storage from 'redux-persist/lib/storage'
import { composeWithDevTools } from 'redux-devtools-extension';
import { persistStore, persistReducer } from 'redux-persist';
import thunk from 'redux-thunk';
import reducer from './Reducers';

import { createOffline } from '@redux-offline/redux-offline';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults/index';

const persistConfig = {
  key: 'root',
  storage
};

const {
  middleware: offlineMiddleware,
  enhanceReducer: offlineEnhanceReducer,
  enhanceStore: offlineEnhanceStore
} = createOffline({
  ...offlineConfig,
  persist: false
});

const persistedReducer = persistReducer(
  persistConfig,
  offlineEnhanceReducer(reducer)
);

const store = createStore(
    persistedReducer,
    composeWithDevTools(
      offlineEnhanceStore,
      applyMiddleware(thunk, offlineMiddleware)
    )
  );

  const persistor = persistStore(store);

export { persistor, store };
```

### Offline config
```js
'@redux-offline/redux-offline/lib/defaults/index'
```

All works only with Debug JS Remotely enabled, but when I build an apk and install it, I do not get any data from my API, when I post something in the API, I do not get any msg status. But with Debug JS Remotely enabled these bugs simple disappears.

I do not even know if anyone will respond to this problem (looks like none even respond the others issues), but ok.

**Comment by calumpeak** [comment]
Hi @rodrigofbm can you explain what Debug JS is? It's not something I've come across before.
Can you be more clear about what/how you're posting data also and will do our best to help.

**Comment by rodrigofbm** [comment]
@echoes221 

Hello. Thank you very much for replying, man. In the first image shows only the spin running infinitely, but if you press ctrl + m and activate the Debug JS Remotely option, the data will appear like magic in place of that spin! This should happen even without Debug JS Remotely enabled!

In the second image you can see that Debug JS Remotely is enabled and the data has appeared! The behavior is similar when sending data to the api via a form. With Debug JS Remotely enabled I get the answer if the data has been successfully or unsuccessfully sent, but without Debug JS Remotely I get nothing.

Here they have a similar problem: https://github.com/react-navigation/react-navigation/issues/2201
It seems they resolved by deleting the "console.log ()" from the screen, but in my case did not work;

![](https://i.imgur.com/eGcBsGJ.png)

![img2](https://i.imgur.com/M84wdm3.png)
