### ISSUE TITLE
persist/REHYDRATE isn't overriding initial state

### ISSUE THREAD

**Issue by Falco101** [redux-offline/redux-offline#304]
In both Local Storage and in the payload of the persist/REHYDRATE action, I see the previous state to rehydrate is correct, however the reducer is ignoring everything but the "router" key. Is there any way to change the re-hydrate reducer to override initial state? or is there some configuration that can be changed?

**Rehydrate action**
<a href="https://imgur.com/rmdHSvv"><img src="https://i.imgur.com/rmdHSvv.png" title="source: imgur.com" /></a>

**Diff shows it did not update state from payload**
<a href="https://imgur.com/CcjiTw8"><img src="https://i.imgur.com/CcjiTw8.png" title="source: imgur.com" /></a>

**State is the same as initial state**
<a href="https://imgur.com/UDQlofo"><img src="https://i.imgur.com/UDQlofo.png" title="source: imgur.com" /></a>

### Are you using `offline()` or `createOffline()` API?
**I'm using offline()**

### Store config
```js
import { createStore, applyMiddleware, compose } from "redux";
import { composeWithDevTools } from "redux-devtools-extension";
import thunk from "redux-thunk";
import { createBrowserHistory } from "history";
import { routerMiddleware } from "connected-react-router";
import { offline } from "@redux-offline/redux-offline";
import defaultConfig from "@redux-offline/redux-offline/lib/defaults";
import createRootReducer from "./modules";
import * as serviceWorker from "./serviceWorker";
import { RenderApp } from "./components/App";

// Configure history to route from /App
export const history = createBrowserHistory({
  basename: "/App/"
});

const offlineConfig = {
  ...defaultConfig,
  persistCallback: RenderApp,
  persistOptions: {
    blacklist: ["Error"]    
  }
};

const initialState = {};
const middleware = [thunk, routerMiddleware(history)];
const enhancers = [offline(offlineConfig)];
// If dev tools extension installed in browser, add to enhancers
if (process.env.NODE_ENV === "development") {
  const devToolsExtension = window.__REDUX_DEVTOOLS_EXTENSION__;

  if (typeof devToolsExtension === "function") {
    enhancers.push(devToolsExtension());
  }
}

export const store = createStore(
  createRootReducer(history), // new root reducer with router state
  initialState,
  compose(
    applyMiddleware(...middleware),
    ...enhancers
  )
);
```

### Offline config

```js
const offlineConfig = {
  ...defaultConfig,
  persistCallback: RenderApp,
  persistOptions: {
    blacklist: ["Error"]    
  }
};
```

**Comment by Falco101** [comment]
Looks like I solved my own problem, seems to be a reconciliation issue with a deep state tree. Adding this to the top of one of my reducers caught the payload and populated it. I just need to add this to each reducer to override the whole state tree.

```js
export default (state = initialState, action) => {
  switch (action.type) {
    case REHYDRATE: 
      return {
        ...state,
        ...action.payload.TallyIn.Loads
      };
...
```

**Comment by sorodrigo** [comment]
You shouldn’t need to do that. That’s a workaround but the library should do that for you.

**Comment by sorodrigo** [comment]
I don’t know what the routerMiddleware does. But in some cases it’s necessary to have control of the way middleware a and enhancers are applied. I’d recommend trying out the `createOffline` and be sure to pass the offlineEnhancer as the first param in the compose (like in the docs).

**Comment by Falco101** [comment]
Thanks, when I get a chance I'll try using createOffline instead of offline and see if that solves it. For now I'm just happy I got it working as is.
