### ISSUE TITLE
Proper way of handling auth tokens

### ISSUE THREAD

**Issue by AlbertoLopSie** [redux-offline/redux-offline#305]
I need to implement an API that requires an auth token in every call. The token is got from an API call that returns that token and its expiration.

From that point any other API call should include that token. Failure to do so or used an expired token produces a HTTP 401 error.

With redux-offline, that kind of errors should put the call (and all following it in the outbox queue) in hold, perform a "get a new token" call, replace the token in the held original call and perform a retry.

How would you implement this algorithm with redux-offline?

Any help would be greatly appreciated.

**Comment by calumpeak** [comment]
@AlbertoLopSie 
Your API itself should be responsible for getting the correct token if the user is not authorised, not redux-offline. You can implement your own `effect` handler via the config. I'd recommend your API flow to attempt to fetch, if necessary get a new token, retry the fetch and then resolve. Redux-offline only cares about starting the request (via the effect) and the resolution of that promise.

https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#effect

**Comment by sorodrigo** [comment]
There was a similar request a while back, so we added support for async retries! Now if you need to refresh the token, you can do so within the retry. As for how to provide the token to all actions, a custom effect is probably the best way. Alternatively you could create a middleware that decorates all actions with the token. Or store it inside [redux-thunk extra argument](https://github.com/reduxjs/redux-thunk#injecting-a-custom-argument) if you're using that library.

**Comment by AlbertoLopSie** [comment]
Confused...

The official doc suggest to implement this kind of error handling in a [customized discard](https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/customize-requests.md#example-async-discard) function. The docs says nothing about a Promise-returning retry function.

According to the [doc](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#config), only effect() and discard() appear to accept Promises as return.

Could you expand a little?

Promises/Async are still a little hard to grasp to me (can understand them, not feeling able to create anything on them) Could you give me (point me to) some example code?

Thank guys!!

**Comment by sorodrigo** [comment]
Apologies, I was referring to the discard function. Just as the docs explain you can use it to refresh your token, one disadvantage is that you don’t have access to dispatch. So the token must be stored in a global variable o local storage or something like this.

**Comment by AlbertoLopSie** [comment]
Upps... I already have a [redux-api-middleware](https://github.com/edy/redux-api-middleware) action already in place to refresh the token. I was planning to use [redux-promise-listener](https://github.com/erikras/redux-promise-listener) to produce the return value of discard..

Are you telling that it won't work?

**Comment by AlbertoLopSie** [comment]
This is the code I'm writing (not tested yet)

```
const generatedAsyncFunction = promiseListener.generateAsyncFunction(
  TOKEN_REFRESH_REQUEST, // the type of action to dispatch when this function is called
  TOKEN_REFRESH_SUCCESS, // the type of action that will resolve the promise
  TOKEN_REFRESH_FAILURE // the type of action that will reject the promise
);

// This structure is in the shape:
// {
//   asyncFunction, <--- the async function that dispatches the start action and returns a Promise
//   unsubscribe    <--- a function to unsubscribe from the Redux store
// }

const _refreshAccessToken = async () => {
  // dispatches an action { type: 'START_ACTION_TYPE', payload: values }
  generatedAsyncFunction.asyncFunction(values).then(
    // called with action.payload when an action of
    // type 'RESOLVE_ACTION_TYPE' is dispatched
    resolvePayload => {
      // do happy stuff 😄
      return true;
    },

    // called with action.payload when an action of
    // type 'REJECT_ACTION_TYPE' is dispatched
    rejectPayload => {
      // do sad stuff 😢
      return false;
    }
  )
  // when done, to prevent memory leaks
  generatedAsyncFunction.unsubscribe();
}

const tokenRefreshDiscard = async (error, _action, _retries) => {

  if (!status in error) return false;

  console.log("redux-offline tokenRefreshDiscard. error:", error, " action:", _action, " retries:", _retries);

  // Ver resolver esto con https://github.com/erikras/redux-promise-listener
  // Explicacion: https://medium.com/@erikras/getting-a-promise-from-redux-actions-d92787894368
  const testing = true;

  if (testing || error.status === 401) {
    var refreshed = await refreshAccessToken();
    if(refreshed) {
      var token = store.getState().Sesion.authToken;
      _action.meta.offline.effect.headers.Authorization = `Bearer ${token}`;
    }
    return !refreshed;
  }

  return 400 <= error.status && error.status < 500;
}
```


What do you think?

**Comment by AlbertoLopSie** [comment]
Well... I've got it!!

With some bumps caused by deficient  redux-promise-listener documentation. The only annoying effect is that it causes one retry. 

Here is the code in case someone considered useful

in configureStore.js
```
const reduxPromiseListener = createReduxPromiseListener();

const tokenRefreshDiscard = async (error, _action, _retries) => {
  console.log("redux-offline tokenRefreshDiscard. error:", error, " action:", _action, " retries:", _retries);

  if (error.status === 401) {
    var refreshed = _action.meta.offline.effect.refreshAccessToken(_action);

    return refreshed;
  }

  return error.status >= 400 && error.status < 500;
}

const reduxOfflineConfig = {
  ...offlineConfig,
  persist: false,
  discard: tokenRefreshDiscard,
};

const {
  middleware: offlineMiddleware,
  enhanceReducer: offlineEnhanceReducer,
  enhanceStore: offlineEnhanceStore
} = createOffline(reduxOfflineConfig);

const persistedReducers = persistReducer(
  persistConfig,
  offlineEnhanceReducer(combinedReducers)
);

const devMiddlewares = [...middlewares];

devMiddlewares.push(offlineMiddleware);

devMiddlewares.push(reduxPromiseListener.middleware);

if (__DEV__) {
  devMiddlewares.push(logger);
}

const configureStore = initialState => {
  console.log("middlewares:", devMiddlewares);

  const store = createStore(
    persistedReducers,
    initialState,
    composeWithDevTools(
      offlineEnhanceStore,
      applyMiddleware(...devMiddlewares),
    )
  );

  const persistor = persistStore(store);
  return { store, persistor };
};

```

In redux-offline-utils.js
```
import {API_ROOT} from "../constants/ApiRoot";
import store from '../store';
import { promiseListener } from '../store/configureStore';

import {
  TOKEN_REFRESH_REQUEST,
  TOKEN_REFRESH_SUCCESS,
  TOKEN_REFRESH_FAILURE,
} from "../constants/ActionTypes";

import { attemptTokenRefresh } from "../actions/ApiTokens";


const tokenAC = () =>
  attemptTokenRefresh(store.getState().Sesion.SesionID);

const generatedAsyncFunction = promiseListener.createAsyncFunction({
//  start: TOKEN_REFRESH_REQUEST, // the type of action that will resolve the promise
  start: "NO_OP", // the type of action that will resolve the promise
  resolve: TOKEN_REFRESH_SUCCESS, // the type of action that will resolve the promise
  reject: TOKEN_REFRESH_FAILURE, // the type of action that will reject the promise
});

export const _refreshAccessToken = async (action) => {
  // dispatches an action { type: 'START_ACTION_TYPE', payload: values }
  store.dispatch(attemptTokenRefresh(store.getState().Sesion.SesionID)); // the type of action to dispatch when this function is called

//  return generatedAsyncFunction.asyncFunction();

  generatedAsyncFunction.asyncFunction().then(
    (payload) => {
      action.meta.offline.effect.headers.Authorization = `Bearer ${payload.Token}`;
      return false;
    },

    (rejectPayload) => {
      return true;
    }
  );

  // when done, to prevent memory leaks
//  generatedAsyncFunction.unsubscribe();
}

const offlineActionCreator = (url, type, data, checkGUID = null) => {
  // Prepend API base URL to endpoint if it does not already contain a valid base URL.
  if (!/^((http|https|ftp):\/\/)/i.test(url))
    url = `${API_ROOT}${url}`;

//  var headers = { 'Content-Type': 'application/json' };
  var headers = { };

  var testing = false;
  var token = store.getState().Sesion.authToken;
  if(!testing && token && token.length > 0)
    headers.Authorization = `Bearer ${token}`;

  return {
    type: `${type}_REQUEST`,
    payload: data,
    meta: {
      offline: {
        effect: {
          url,
          method: 'POST',
          body: JSON.stringify(data),
          refreshAccessToken: _refreshAccessToken,
          headers,
        },
        commit: {
          type: `${type}_COMMIT`,
          meta: { GUID: checkGUID },
        },
        rollback: {
          type: `${type}_ROLLBACK`,
          meta: { GUID: checkGUID },
        },
      },
      meta: {needsAuth: true},
    },
  };
}

export {
  offlineActionCreator
};

```

**Comment by Romiko** [comment]
Thanks for sharing :)

**Comment by mh4100** [comment]
> Well... I've got it!!
> 
> With some bumps caused by deficient redux-promise-listener documentation. The only annoying effect is that it causes one retry.
> 
> Here is the code in case someone considered useful
> 
> in configureStore.js
> 
> ```
> const reduxPromiseListener = createReduxPromiseListener();
> 
> const tokenRefreshDiscard = async (error, _action, _retries) => {
>   console.log("redux-offline tokenRefreshDiscard. error:", error, " action:", _action, " retries:", _retries);
> 
>   if (error.status === 401) {
>     var refreshed = _action.meta.offline.effect.refreshAccessToken(_action);
> 
>     return refreshed;
>   }
> 
>   return error.status >= 400 && error.status < 500;
> }
> 
> const reduxOfflineConfig = {
>   ...offlineConfig,
>   persist: false,
>   discard: tokenRefreshDiscard,
> };
> 
> const {
>   middleware: offlineMiddleware,
>   enhanceReducer: offlineEnhanceReducer,
>   enhanceStore: offlineEnhanceStore
> } = createOffline(reduxOfflineConfig);
> 
> const persistedReducers = persistReducer(
>   persistConfig,
>   offlineEnhanceReducer(combinedReducers)
> );
> 
> const devMiddlewares = [...middlewares];
> 
> devMiddlewares.push(offlineMiddleware);
> 
> devMiddlewares.push(reduxPromiseListener.middleware);
> 
> if (__DEV__) {
>   devMiddlewares.push(logger);
> }
> 
> const configureStore = initialState => {
>   console.log("middlewares:", devMiddlewares);
> 
>   const store = createStore(
>     persistedReducers,
>     initialState,
>     composeWithDevTools(
>       offlineEnhanceStore,
>       applyMiddleware(...devMiddlewares),
>     )
>   );
> 
>   const persistor = persistStore(store);
>   return { store, persistor };
> };
> ```
> 
> In redux-offline-utils.js
> 
> ```
> import {API_ROOT} from "../constants/ApiRoot";
> import store from '../store';
> import { promiseListener } from '../store/configureStore';
> 
> import {
>   TOKEN_REFRESH_REQUEST,
>   TOKEN_REFRESH_SUCCESS,
>   TOKEN_REFRESH_FAILURE,
> } from "../constants/ActionTypes";
> 
> import { attemptTokenRefresh } from "../actions/ApiTokens";
> 
> 
> const tokenAC = () =>
>   attemptTokenRefresh(store.getState().Sesion.SesionID);
> 
> const generatedAsyncFunction = promiseListener.createAsyncFunction({
> //  start: TOKEN_REFRESH_REQUEST, // the type of action that will resolve the promise
>   start: "NO_OP", // the type of action that will resolve the promise
>   resolve: TOKEN_REFRESH_SUCCESS, // the type of action that will resolve the promise
>   reject: TOKEN_REFRESH_FAILURE, // the type of action that will reject the promise
> });
> 
> export const _refreshAccessToken = async (action) => {
>   // dispatches an action { type: 'START_ACTION_TYPE', payload: values }
>   store.dispatch(attemptTokenRefresh(store.getState().Sesion.SesionID)); // the type of action to dispatch when this function is called
> 
> //  return generatedAsyncFunction.asyncFunction();
> 
>   generatedAsyncFunction.asyncFunction().then(
>     (payload) => {
>       action.meta.offline.effect.headers.Authorization = `Bearer ${payload.Token}`;
>       return false;
>     },
> 
>     (rejectPayload) => {
>       return true;
>     }
>   );
> 
>   // when done, to prevent memory leaks
> //  generatedAsyncFunction.unsubscribe();
> }
> 
> const offlineActionCreator = (url, type, data, checkGUID = null) => {
>   // Prepend API base URL to endpoint if it does not already contain a valid base URL.
>   if (!/^((http|https|ftp):\/\/)/i.test(url))
>     url = `${API_ROOT}${url}`;
> 
> //  var headers = { 'Content-Type': 'application/json' };
>   var headers = { };
> 
>   var testing = false;
>   var token = store.getState().Sesion.authToken;
>   if(!testing && token && token.length > 0)
>     headers.Authorization = `Bearer ${token}`;
> 
>   return {
>     type: `${type}_REQUEST`,
>     payload: data,
>     meta: {
>       offline: {
>         effect: {
>           url,
>           method: 'POST',
>           body: JSON.stringify(data),
>           refreshAccessToken: _refreshAccessToken,
>           headers,
>         },
>         commit: {
>           type: `${type}_COMMIT`,
>           meta: { GUID: checkGUID },
>         },
>         rollback: {
>           type: `${type}_ROLLBACK`,
>           meta: { GUID: checkGUID },
>         },
>       },
>       meta: {needsAuth: true},
>     },
>   };
> }
> 
> export {
>   offlineActionCreator
> };
> ```

Can you explain more what you done please? What is attemptTokenRefresh and promiseListener  ? Thanks
