### ISSUE TITLE
Async Actions

### ISSUE THREAD

**Issue by maharjanaman** [redux-offline/redux-offline#309]
How do we handle asynchronous actions? For example, if we have to wait for api response for login scenario, can we somehow create async actions or we need to create separate actions with separate api calls?

For this doc https://github.com/redux-offline/redux-offline/blob/develop/docs/basics/commit.md, can hold execution untill commit or rollback?

**Comment by calumpeak** [comment]
Hey @maharjanaman 
Not everything needs to go through redux-offline.
I'd say that if you need to login, then that shouldn't go through redux-offline as the user would have to be online for that to happen and allow your entire application to work anyway. 

If you need to wait for a certain action to complete (either commit or rollback) then I'd definitely look in the direction of middleware/epics/sagas as that will allow you to have side effects from other actions. Redux-offline is only concerned with making requests at the right time (when user is online) and works best for the`CUD` of `CRUD`, which can go into a queue and you can show to the user optimistically via the UI. `GET/READ` requests don't necessarily need to go through redux offline as that's something that can and should only happen when online. GET requests can be done in parallel too - redux-offline processes in serial.

You can also make commit/rollback actions themselves offline actions if absolutely necessary, but that way lies dragons and can make your application harder to reason about.

**Comment by maharjanaman** [comment]
Thanks for replying...

**Comment by betoharres** [comment]
@calumpeak Thanks for the explanation! Somehow I narrowed my mind into only use `redux-offline` to make HTTP calls, which I shouldn't as you explained!

**Comment by calumpeak** [comment]
@betoharres No problem. Redux-offline should only really be used where you actually need to have optimistic UI's where the user is making, editing and deleting entities. There's more than one way to skin a cat, so don't forget all the other ways you can make HTTP requests :D
