### ISSUE TITLE
Usage with non-Immutablejs React-Boilerplate

### ISSUE THREAD

**Issue by richbrill** [redux-offline/redux-offline#31]
Is it possible to use Redux-Offline with the forked version of React-Boilerplate with Immutablejs removed: https://github.com/Dattaya/react-boilerplate-object ? I'm attempting to implement the offline enhancer by adding it to the enhancers array in app/store.js like this:

`const enhancers = [
    applyMiddleware(...middlewares),
    offline(offlineConfig),
  ];`
 
but I get this error:

`Cannot read property 'outbox' of undefined`

After investigation it appears this has something to do with redux-devtools-extension. If I remove all reference to devtools and just use standard redux compose it throws this error:

`Unexpected key "offline" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "routing", "global", "language", "login". Unexpected keys will be ignored.`

Apologies if this isn't the right place to post this but I'm sure many others may have this problem and it might just be a lack of knowledge on my part related to how store enhancers such as redux-offline should be implemented, cheers!

**Comment by wacii** [comment]
The second error is from `Redux.combineReducers()`. It doesn't like us adding additional keys to the state. I'll see if there's anything we can do on our end.

**Comment by wacii** [comment]
This is addressed in #32, so this should be fixed in the next release.
