### ISSUE TITLE
How exactly is the workflow?

### ISSUE THREAD

**Issue by MateusGabi** [redux-offline/redux-offline#313]
I read all the documentation but I didn't understand how exactly is the workflow. I guess that an image could explain how `redux-offline` works (image below).

![image](https://user-images.githubusercontent.com/14940643/56304494-98a98f00-6114-11e9-830d-ff558ad617bd.png)

For example:
- The green dot represents the beginning of the workflow (when an action is dispatched);
- The orange diamond means "is user offline? yes/no";
- The next blue rectangle means "save action in local storage, or, IndexedDB";
- ....

This issue tries to answer all questions presents in #301 #225 #65 #174

**Comment by calumpeak** [comment]
I think this is the clearest and most instructional image that's available - we're just an optimistic middleware is all.
![optimistic](https://user-images.githubusercontent.com/10559737/56536264-8a64d400-6555-11e9-8a93-0b9eb46a0970.gif)
