### ISSUE TITLE
How do I access the commit/rollback metadata in a reducer?

### ISSUE THREAD

**Issue by DianaLaa** [redux-offline/redux-offline#318]
I see plenty of examples such as 

```
const followUser = userId => ({
  type: 'FOLLOW_USER_REQUEST',
  payload: { userId },
  meta: {
    offline: {
      // the network action to execute:
      effect: { url: '/api/follow', method: 'POST', body: { userId } },
      // action to dispatch when effect succeeds:
      commit: { type: 'FOLLOW_USER_COMMIT', meta: { userId } },
      // action to dispatch if network action fails permanently:
      rollback: { type: 'FOLLOW_USER_ROLLBACK', meta: { userId } }
    }
  }
});
```

But how do I access this `userId` in a reducer when a commit or rollback happens? 
I've tried `action.userId`, `action.meta.userId`, `action.payload.userId`, to no avail..

**Comment by DianaLaa** [comment]
Similar question for the error: How to I access the error that occurred that triggered the rollback? Here also I tried `action.error`, `action.meta.error` and `action.payload.error`  but it's always undefined.

**Comment by sorodrigo** [comment]
You should be able to do this:
```js
case FOLLOW_USER_ROLLBACK: {
  const error = action.payload;
  const { userId } = action.meta;
}
```

**Comment by DianaLaa** [comment]
Thanks!

For error it turns out that action,payload is an object with a number of keys like 'name', 'status' and 'response' which is another object with key 'message'. So action.payload.status can be used.
