### ISSUE TITLE
Rollback has a payload with line number and Expo tunnel as failure reason

### ISSUE THREAD

**Issue by DianaLaa** [redux-offline/redux-offline#319]
As you can see, I'm getting started with redux-offline and coming to grips with various aspects of it. It's not going as smoothly as I had hoped.

I have an action I dispatch, like so:
    
    dispatch({
      type: 'SOME_ACTION',
      meta: {
      	offline: {
      		effect: { url: 'https://www.google.com', 
                    method: 'GET',
                  },
      		commit: { type: 'SOME_ACTION_COMMIT', meta: { } },
      		rollback: { type: 'SOME_ACTION_ROLLBACK', meta: { } }
      	}
      }
    });

No matter the URL or POST/GET, I get the `Retrying action SOME_ACTION with delay X` message.

I hacked config.retry to retry just once and then no more. In my reducer, on `SOME_ACTION_ROLLBACK`, I call `console.log(JSON.stringify(action));` to check what's going on. What is returned seem really odd to me:

    {"type":"SOME_ACTION_ROLLBACK",
     "meta":{"success":false,"completed":true},
     "payload":{"line":175497,"column":35,
     "sourceURL":"http://packager.d5-vru.my.app.exp.direct:80/node_modules/expo/AppEntry.bundle?platform=android&dev=true&minify=false&hot=false&assetPlugin=path%5Cto%5Cnode_modules%5Cexpo%5Ctools%5ChashAssetFiles.js"}}

Note that I'm doing a GET from https://www.google.com as a last resort, because a call to my own WebAPI was giving these same results...

How do I figure out what's causing this?

**Comment by sorodrigo** [comment]
Rollback will expose the error returned by the `fetch` defined in the default effect.
If you're trying to redefine the `retry` there's no need to hack it, you can define a custom one passing to the config object of offline.
If you want to debug your network error perhaps the way to do it is to add a breakpoint on the rollback reducer action and inspect the contents of the NetworkError content.

**Comment by DianaLaa** [comment]
Thanks, found it. The reason for this error is that there is an exception occurring in handling of SOME_ACTION by the reducer. That exception is caught and passed on to SOME_ACTION_ROLLBACK.

**Comment by sorodrigo** [comment]
That’s not supposed to happen. What version are you using?

**Comment by DianaLaa** [comment]
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject",
    "test": "node ./node_modules/jest/bin/jest.js --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "2.1.1",
    "babel-plugin-inline-dotenv": "^1.3.3",
    "dotenv": "^8.0.0",
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-masked-text": "^1.12.0",
    "react-native-paper": "^2.15.0",
    "react-navigation": "^3.8.1",
    "react-redux": "^6.0.1",
    "redux": "^4.0.1",
    "redux-offline": "^2.0.0",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0",
    "jest-expo": "^32.0.0"
  },
  "private": true
}

```

**Comment by sorodrigo** [comment]
Yup you’re using the wrong library. Try installing
```
npm i @redux-offline/redux-offline
```

**Comment by DianaLaa** [comment]
Sorry, what? Then what am I using?

**Comment by calumpeak** [comment]
You're using an outdated copy that was initially published but still exists (last update 2 years ago). redux offline has since been namespaced under `@redux-offline/redux-offline`.

Please follow the README setup instructions for installation:  https://github.com/redux-offline/redux-offline#1-install-with-npm-or-yarn

**Comment by DianaLaa** [comment]
Well, that suddenly solved a number of weird problems... Thanks!

**Comment by sorodrigo** [comment]
I reached out to the original creator, he'll include a deprecation notice on the original package to avoid this again.
