### ISSUE TITLE
How to wait until commit has completed before dispatching additional actions?

### ISSUE THREAD

**Issue by benvp** [redux-offline/redux-offline#32]
Is there currently anyway to ensure that the requests in the effect handler are made in series? I have an api where I create multiple resource which depend on another. So I have to ensure to create one entity first before I can add a related resource. 

Any ideas?

**EDIT**: Actually I would need a way to dispatch another action *after* the commit action of a previous has been processed. To clarify further: I have a resource `/categories` , when I add a category on the client, I optimistically generate a temporary `id`, which eventually will be updated after the `commit` action has been dispatched. With the new id, I add a product to `/categories/:id/products` <-- that is why I have to wait until the commit of the `createCategory` action has been dispatched. I need a valid `id` in order to create a product.

**Comment by benvp** [comment]
After digging around some days, I came up with a solution, which is working for me. I will describe shortly what I have done and what the *real* problem was.

So my problem was that I my entities are related and the server is responsible for creating the entities id fields. So I have to generate some kind of a temporary local id if the entities are not synced to the server (I use the lodash uniqueId method for this). 

However, example in the README requires you to know the entities id at the time, when you initially dispatch the action. So for example if you create a new `Category` the endpoint is `POST /categories`.  And you create a related `Product`, which has the path `POST /categories/:categoryId/products`. If the user now creates both entities while being offline, the `categoryId` would end up in our generated local id - this would raise an error in the backend.

So I had to get the actual id of the `category` which has been returned by the server *after* the `CREATE_CATEGORY_COMMIT` action has been dispatched. The reducer will then replace the object with the local id and replace it with the one from the server. Additionally the reducer adds a property `_meta: { localId: 231 }` to the new received object. This is how I can reference the object which has been locally created before.

Having this, I pass a function as the `effect` handler, which will be executed by the reconciler and returning the proper object to pass to my api service. I'm not quite sure if this is a good practice, but this is the only way I could came up to handle these kind of things.

Here is some code:

```javascript
// productActions.js

export const createProduct = categoryId => (dispatch, getState) => {
  const productId = uniqueId(c.NEW_ID_PREFIX);

  const effect = () => {
    const category =
      categorySelectors.findByLocalId(getState(), categoryId) ||
      categorySelectors.byId(getState())[categoryId];

    return {
      method: 'POST',
      path: `/categories/${category.id}/products`,
      schema: schema.CATEGORY,
    };
  };

  return dispatch({
    type: t.CREATE_PRODUCT,
    payload: { /* ...some payloyad */ },
    meta: {
      offline: {
        effect,
        commit: { type: t.CREATE_PRODUCT_COMMIT, meta: { localId: productId } },
        rollback: { type: t.CREATE_PRODUCT_ROLLBACK, meta: { localId: productId } },
      },
    },
  });
};
```

A little note: the `findByLocalId` selector will look up the category by the `_meta:  { localId }` field. If this returns undefined, we can be sure that the passed id can be retrieved from the category state.

@jevakallio You can close this issue if you like or share your thoughts, especially if it's okay to pass a function to the effect.

**Comment by adamjacob** [comment]
@benlime How's this working out for you?  I'm looking to do the same thing, trying to figure out the best approach.

**Comment by benvp** [comment]
@adamjacob it works quite well and gets the job done. But anyway in my opinion it doesn't feel like the right way. I'm looking forward to the changes @jevakallio mentioned in https://github.com/jevakallio/redux-offline/pull/17#issuecomment-292208117 and I think I'll start using sagas then. 

Additionally I'm experiencing the issues from #23. This might not be directly related, but I couldn't find a way yet digging around the redux-offline code to ensure that additional actions are not picked up by the middleware. As a workaround, I'm using a short timeout now.

**Comment by benvp** [comment]
@adamjacob What I haven't tested yet is persisting the state to disk. Due to the architecture of my app, I'm currently not persisting the offline state. I don't know if this is even possible, when there are functions in the effect. Did my solution work for you or did you come up with anything else?

**Comment by anrosent** [comment]
I had the same problem (using a different but conceptually similar offline state management framework), and changing the remote API to accept client-generated UUIDs eliminated this problem of reconciling local/server-assigned IDs. Not sure if you have the latitude to change the API in this way though.

**Comment by benvp** [comment]
@anrosent Thanks for the feedback. I thought about generating id's on the client, too. But I'm not sure if this would be a security risk... additionally it feels kinda odd giving the client the control of generating id's. But yes, this would eliminate the need of having a function in the effect.

What is your experience with letting the client generate the id?

**Comment by anrosent** [comment]
The app I'm developing is internal to our team, so I didn't put *too* much thought into any security concerns. That said, the only thing I can imagine a misbehaving client doing (that isn't also a risk with server-assigned IDs) is intentionally generating a colliding ID. The server would just need to reject such requests to create resources using existing IDs.

Using some kind of UUID (I'm using V4, I think version suitability depends on the use-case) should make the rate of collisions by faithful clients negligible as well.

**Comment by adamjacob** [comment]
@benlime To answer your question above.  I've actually got it working with persisting state.  I went ahead and did it a bit different than how you suggested (but thanks for the starting point).

Objects created on the client have a temporary id assigned to them with the prefix `local_`.  Once that object has been created on the server and returned, I temporary store the previous temporary id on the object in my store as `local_id`.  A hook in my effect method right before the request goes off to the API looks for ids with the prefix `local_`.  If it finds one it will attempt to find an object in my store with that local_id set and replace the id in the request with the proper id.  So far this has been working great and scaling across multiple models for me.  I've been able to create chained objects and everything resolves in order (Root -> Child -> Child).

**Comment by benvp** [comment]
@adamjacob thanks for the insights. Just to make sure I understand correctly, do you use the hook you described in your effects reconciler? Or is the effect a method like in my example? The hook iterates through the full store and searches for objects with local ids?

I'm really considering to let the client generate the id, as my app has a lot of crud actions which can potentially be done offline. I would have to track quite a lot with that local ids...

**Comment by adamjacob** [comment]
@benlime Yeah I'm doing the hook in the effect reconciler.  So I pass a type in the meta so the reconciler knows where in the store to look for the object via local ID.

**Comment by mwakerman** [comment]
@benlime - Thanks for your write up, coming up against the same problem and your summary was really helpful. After a bit of consideration, we've decided that we are going to trust client generated IDs, the [JSON API](http://jsonapi.org/format/#crud-creating-client-ids) spec says:

> A server MAY accept a client-generated ID along with a request to create a resource. An ID MUST be specified with an id key, the value of which MUST be a universally unique identifier. The client SHOULD use a properly generated and formatted UUID as described in RFC 4122 [RFC4122].

Our ID generation method is RFC 4122 compliant meaning we can safely assume we will never accidentally generate the same ID. In the case of a malicious client that intentionally creates a resource with an existing ID, the server will reject the request and all dependent requests will fail. Long story short: we don't really care if failures happen all over the place for someone being malicious.

**Comment by tadeo** [comment]
@adamjacob I'm facing this same issue and it seems your custom effect reconciler approach is the way to go. I know it's been a year since your last comment but could you please copy the code you use there?
My main doubt to implement it myself is how to access the store from the custom effect to look for the object via local ID.
Thank you very much!

**Comment by adamjacob** [comment]
@tadeo you can simply use `const state = store.getState()`, patch your effect object with your actual id in state and then fire off your network request.

**Comment by tadeo** [comment]
@adamjacob thanks for your help.
For some mistake of mine I can't import `store` from the main App component in my initial implementation.
I got a dirty working work around using a global `window.store` variable.
Now, after your answer, I retried and I got it working in a cleaner export/import way. I leave here some pseudo-code hoping it helps someone else.
Thanks again!


```javascript
// App.jsx
...
export const store = configureStore()
...
```

```javascript
// effect.js
import { store } from './App'
...

const updateLocalIdURL = (url, action) => {
  const state = store.getState()
  ...
}

export default (effect, _action) => {
  let { url } = effect
  if (_action.meta.related) {
    url = updateLocalIdURL(url, _action)
  }
  const updatedEffect = {...effect, url}
  return defaultEffect(updatedEffect, _action)
}
```

```javascript
// store.js
import { createStore, applyMiddleware, compose } from 'redux'
import { offline } from '@redux-offline/redux-offline'
import defaultOfflineConfig from '@redux-offline/redux-offline/lib/defaults'
import thunk from 'redux-thunk'
import reducer from './reducer'
import effect from './effect'

export default function configureStore( initialState = {} ) {
  const offlineConfig = {...defaultOfflineConfig, effect}
  const enhancer = compose(applyMiddleware(thunk), offline(offlineConfig))
  const store = createStore(reducer, initialState, enhancer)
  return store
}
```

**Comment by bendelonlee** [comment]
@benvp Having this same problem.

In your code for createProduct, what's preventing the product POST request from being sent with the local category id before the commit?  

```
export const createProduct = categoryId => (dispatch, getState) => {
  const productId = uniqueId(c.NEW_ID_PREFIX);

  const effect = () => {
    const category =
      categorySelectors.findByLocalId(getState(), categoryId) ||
      categorySelectors.byId(getState())[categoryId];

    return {
      method: 'POST',
      path: `/categories/${category.id}/products`,
      schema: schema.CATEGORY,
    };
  };

  return dispatch({
    type: t.CREATE_PRODUCT,
    payload: { /* ...some payloyad */ },
    meta: {
      offline: {
        effect,
        commit: { type: t.CREATE_PRODUCT_COMMIT, meta: { localId: productId } },
        rollback: { type: t.CREATE_PRODUCT_ROLLBACK, meta: { localId: productId } },
      },
    },
  });
};
```

Does wrapping the effect in a function somehow guarantee it won't be run until CREAT_CATEGORY_COMMIT has completed? 

Not sure what I'm missing.

I know it's been more than a year, but any assistance is sincerely appreciated!

**Comment by benvp** [comment]
Iirc (it has been four years) then the effect as a function does allow you to get the correct element based on either the local id or the actual id when the effect runs. That way, sending incorrect ids would be prevented.

**Comment by bendelonlee** [comment]
After four years, it's a minor miracle you responded at all haha...

Still not 100% clear on this.  Getting the correct element is good, but if the server response with the server-generated id hasn't come back yet, you'll still only be able to send the client-generated temporary id. Are you saying you set up the server to accept this client id?

Thanks!
