### ISSUE TITLE
Cannot work with react-native 0.60.0-rc.0

### ISSUE THREAD

**Issue by bthuan** [redux-offline/redux-offline#323]
Hi,
I tried to upgrade react-native lib to version 0.60.0-rc.0 and it breaks the build. I think the reason is they removed **NetInfo** out of RN completely so this line will break: https://github.com/redux-offline/redux-offline/blob/9e84f38be0720a069d47487eb0717b00ada11843/src/defaults/detectNetwork.native.js#L2
I am not sure what the solution for this is so I just posted it here. Thank you for any advice

**Comment by calumpeak** [comment]
Hi @bthuan - has it been replaced by another API? You can also roll your own network detect in the meantime.

**Comment by bthuan** [comment]
@calumpeak the API is migrated out of RN core to **react-native-community/react-native-netinfo**: https://facebook.github.io/react-native/docs/netinfo.html
In order to use my own network detect, I guess I have to fork the project. I hope the authors of redux-offline, which is a cool library, be aware of this and have a new release that can support the upcoming RN release

**Comment by calumpeak** [comment]
@bthuan, I’m one of the maintainers so I’ll take a look at patching this. It’s in release candidate though so it’s not in prime time. Will have to be handled so it’s backward compatible with pre-existing versions of RN. 

You shouldn’t need to fork the repo, you can provide your own implementation via the config, please take a look through our docs.

**Comment by bthuan** [comment]
@calumpeak it will be great! I'll take a look at the docs to use my own network detect in the meantime. Thank you for working on this awesome library!

**Comment by ryanlntn** [comment]
#333 addresses this.

**Comment by usrbowe** [comment]
###  ℹ️ For those, who want temporary fix, before releasing the #333 :

1. Install `patch-package` & `@react-native-community/netinfo`
2. Update those two files:
```js
// FILE: node_modules/@redux-offline/redux-offline/lib/defaults/detectNetwork.native.js
// on top
var _netInfo = require('@react-native-community/netinfo');
// find&replace: "_reactNative.NetInfo" with "_netInfo"
```
```js
// FILE: node_modules/@redux-offline/redux-offline/lib/defaults/detectNetwork.native.legacy.js
// on top
var _netInfo = require('@react-native-community/netinfo');
// find&replace: "_reactNative.NetInfo" with "_netInfo"
```
3. This works as temporary hotfix, without forking the package&building the source files

**Comment by sorodrigo** [comment]
Fixed in https://www.npmjs.com/package/@redux-offline/redux-offline/v/2.5.2-native.0

**Comment by bthuan** [comment]
I just upgraded my app to RN 0.60.4 + redux-offline v.2.5.2-native.0. it worked for me. thank you for working on this
