### ISSUE TITLE
Getting Started Documentation - config import

### ISSUE THREAD

**Issue by cindyyu** [redux-offline/redux-offline#324]
In the Getting Started part of the [documentation](https://github.com/redux-offline/redux-offline/blob/develop/docs/basics/getting-started.md), it says to use

```import config from '@redux-offline/redux-offline/lib/config';```

I get Typescript errors when I use this import, but when I use the import suggested in the entry level [Readme](https://github.com/redux-offline/redux-offline/blob/develop/README.md) 

```import offlineConfig from '@redux-offline/redux-offline/lib/defaults';```

It works fine for me. I think it'd be helpful to make the two pieces of documentation consistent (they both seem like getting started guides) or if there is a difference between config and defaultConfig, clarify the difference. I poked around very briefly and did not see lib/config defined in the `typings.d.ts` file.

### Are you using `offline()` or `createOffline()` API?
n/a 

### Store config
n/a

### Offline config
n/a

### Are you reporting a bug?
No.

**Comment by calumpeak** [comment]
Thanks for the heads-up. Would you be able to raise a PR for this, please?
