### ISSUE TITLE
Best way to change HTTP Status code handling?

### ISSUE THREAD

**Issue by DianaLaa** [redux-offline/redux-offline#325]
When a 4xx statuscode occurs, I want to not discard an action, but keep it in the queue. (I will be pausing the queue until the error is / seems resolved)

What's the best way to achieve this?

**Comment by calumpeak** [comment]
You can provide your own version of `discard` via the config which sets whether to remove the action or allow it to be retried. Currently, it will be using[ our default](https://github.com/redux-offline/redux-offline/blob/develop/src/defaults/discard.js). 

Please check the [docs](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#discard) for more information 😄

**Comment by DianaLaa** [comment]
Oh, thanks!
