### ISSUE TITLE
Reorder the queue if a request fails? Try to run actions that haven't been tried yet

### ISSUE THREAD

**Issue by DianaLaa** [redux-offline/redux-offline#326]
Suppose there are three actions enqueued. Each of them does a web request, for example all three post some data. If the first action in the queue fails, it will be retried later. This may take up to an hour. It seems the other actions in the queue are all blocked too, because of it.

Now, efficient scheduling is a whole field of its own.. I'm not pretending to know the answer, but would there be some way that if an action fails, _meanwhile_, trying to run actions that haven't been tried yet?

Kind of like `[{ ...action1, retries: 1}, { ...action2, retries:0 }, { ...action3, retries: 0 }]` that once it failed `action1`, it will set a timer for a second attempt but meanwhile it can try `action2` because it may succeed. This may have its own problems, I don't know. But suppose that with a timer, you set a retry-"level". So in one minute, we'll retry all actions that have been tried once before? (To avoid having too many timers?)

Just brainstorming :)

**Comment by calumpeak** [comment]
The simple solution would be to implement your own version of queue.peek via the config. Peek is responsible for returning the next item in the outbox. So if an Item has a retry on, simply return one that doesn’t. 

Just be wary of a) the order in which your requests need to be made (e.g. entity creation must come before entity update else you’ll error on your server). b) how redux online handles retries itself.

**Comment by DianaLaa** [comment]
Hi @calumpeak, thanks for your response.
I wasn't too sure about peek, because of [this line here](https://github.com/redux-offline/redux-offline/blob/01d55c26157387acc93a5e7e73df2eee4b116c24/src/middleware.js#L15). It seems as if the middleware receives the original action. 

If, [a little further down](https://github.com/redux-offline/redux-offline/blob/01d55c26157387acc93a5e7e73df2eee4b116c24/src/middleware.js#L22), peek returns a different action, I'm not sure what the effect would be, since the original action [is used as well](https://github.com/redux-offline/redux-offline/blob/01d55c26157387acc93a5e7e73df2eee4b116c24/src/middleware.js#L41)

**Comment by calumpeak** [comment]
@DianaKoenraadt You're safe to change peek. Peek only sets the `offlineAction` portion and is only used in that `if` statement on L32. It also has no connection to the current action passing through the middleware. The `next(action)` just allows the action to propagate to the next middleware in the chain and redux-offline runs afterwards. 
The original action you're flagging in your last link is just to check for retry's etc, it's not connected to the offlineAction. 
Play around with it some, but it won't affect the flow of the other actions.
