### ISSUE TITLE
Typescript signature wrong for offline & createOffline

### ISSUE THREAD

**Issue by mavarazy** [redux-offline/redux-offline#327]
### Problem

Source code applies default on creation

[offline](https://github.com/redux-offline/redux-offline/blob/develop/src/index.js#L30)
```js
export const offline = (userConfig: $Shape<Config> = {}) => (
  createStore: any
) => (reducer: any, preloadedState: any, enhancer: any = x => x) => {
  const config = applyDefaults(userConfig);
```
[createOffline](https://github.com/redux-offline/redux-offline/blob/develop/src/index.js#L88)
```js
export const createOffline = (userConfig: $Shape<Config> = {}) => {
  const config = applyDefaults(userConfig);
```

But TypeScript signature is

[offline](https://github.com/redux-offline/redux-offline/blob/develop/typings.d.ts#L132)
```ts
  export const offline: (userConfig: Config) => (createStore: typeof createReduxStore) =>
```
[createOffline](https://github.com/redux-offline/redux-offline/blob/develop/typings.d.ts#L139)
```ts
  export const createOffline: (userConfig: Config) => ({
```

### Solution

Change Config to Partial
[offline](https://github.com/redux-offline/redux-offline/blob/develop/typings.d.ts#L132)
```ts
  export const offline: (userConfig: Partial<Config>) => (createStore: typeof createReduxStore) =>
```
[createOffline](https://github.com/redux-offline/redux-offline/blob/develop/typings.d.ts#L139)
```ts
  export const createOffline: (userConfig: Partial<Config>) => ({
```

**Comment by calumpeak** [comment]
Thanks for catching this @mavarazy. We will be migrating the project to TS in the future so we should have less of these issues. In the meantime I'll approve your PR  😄
