### ISSUE TITLE
Action for triggering retry of outbox items

### ISSUE THREAD

**Issue by ChrisKG32** [redux-offline/redux-offline#331]
### Are you using `offline()` or `createOffline()` API?
I use the offline() API.

### Offline config
I use the default config besides this detect network config.
```js
detectNetwork: callback => {
    Meteor.ddp.on('connected', () => {
      console.log('Network Detected');
      return callback(true);
    });
    Meteor.ddp.on('disconnected', () => {
      console.log('Network Disconnected');
      return callback(false);
    });
  }
```

### Issue
On rare occasions where the app has not had connectivity for some time, even after it regains connectivity it will not send outbox items, and will just continue to store them until the next time the store is replenished.

I have dug through the redux-offline source code in an attempt to find a way to trigger a retry attempt at sending outbox items without success.

Is there an action I may dispatch to do this? I have tried:
```
OFFLINE_SCHEDULE_RETRY
OFFLINE_SEND
ddp.reconnect()
Meteor.reconnect()
```
But outbox items remain to pile up until the app is restarted and the store is completely replenished which triggers the outbox peek and queue.

**Comment by calumpeak** [comment]
When the network reconnects, is the offline/STATUS_CHANGED action getting triggered?

**Comment by ChrisKG32** [comment]
@calumpeak I just realized from your comment that the action names are not equivalent to the action constant names. ```OFFLINE_STATUS_CHANGED = "Offline/STATUS_CHANGED";``` for instance.

I shall try redoing all of these previous attempts but this time with the proper action names :)

**Comment by calumpeak** [comment]
The outbox should automatically start to clear when online = true, so I'm just wondering if there is another issue in your setup is all. Redux offline will start to process the outbox on any action that gets passed through it's middleware. The fact that it's not suggests that it still thinks it's offline...

I think reason being is that your custom network detect is calling the callback incorrectly. You're calling `callback(true)`, when it should be `callback({online: true})`. Though that should be handled automatically by the action creator, so there still shouldn't be an issue... Please double check the docs https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#detectnetwork

**Comment by ChrisKG32** [comment]
@calumpeak Here is the code for the redux-offline action for Status Changes.
```
export const networkStatusChanged = params => {
  let payload;
  if (typeof params === 'object') {
    payload = params;
  } else {
    payload = { online: params };
  }
  return {
    type: OFFLINE_STATUS_CHANGED,
    payload
  };
};
```
You may either pass ```true``` or ```{ online: true }```
Nonetheless my previous attempts at fixing it were to dispatch a "Schedule Retry" or "Send" action in order to jumpstart the process if it had timed-out. After reading your post I can now see that I was passing the actions: 
```
{
type: 'OFFLINE_STATUS_CHANGED',
...
}
```
instead of:
```
{
type: 'Offline/STATUS_CHANGED',
...
}
```
etc.

Therefore it's obvious why none of these proposed solutions worked, as the actions weren't even being dispatched. I shall retry with the proper action types and reopen this issue if it is not resolved.

**Comment by calumpeak** [comment]
You shouldn’t need to dispatch your own offline action. It should be automatic...

**Comment by stvmachine** [comment]
I got the same problem on React Native, the connectivity changes trigger the `Offline/STATUS_CHANGED` action but the outbox doesn't progress until a new item is added to the outbox.

**Comment by calumpeak** [comment]
@stvmachine the action is definitely dispatched?

**Comment by hellogbg** [comment]
> You shouldn’t need to dispatch your own offline action. It should be automatic...

I have this problem, and I can see several people has: When I turn off my WiFi (on mac) action Offline/STATUS_CHANGED is called and I can see state online: false, but when I turn WiFi on again, no action is triggered. "online" state remains false. Nothing from "outbox" is being called.

I am using:     "@redux-offline/redux-offline": "^2.5.1",
on React Native 0.59

This is my store:
`
const effect = (effect, _action) => 
    axiosApi.get("/list/allpermitlist/")
    .then(response=>console.log(response));

const svebraOfflineConfig = {
    ...defaultConfig,
    // retry: ( OfflineAction, number) => number? number : number,
    effect,
    rehydrate: true,
    persist: false,
}
const initialState = {};
const offlineEnhancer = createOffline(svebraOfflineConfig);


const middleware = []
if (process.env.NODE_ENV === 'development') {
    middleware.push(logger)
}

const store = createStore(
    offlineEnhancer.enhanceReducer(reducers), 
    initialState,
    compose(
        offlineEnhancer.enhanceStore,
        applyMiddleware(offlineEnhancer.middleware, ...middleware)
    )
)
`
