### ISSUE TITLE
[Request] Cutting a patch release

### ISSUE THREAD

**Issue by lukyth** [redux-offline/redux-offline#335]
I noticed that it's been 7 months since the latest release. Is it a good time now to cut a new patch release? There're many changes that haven't been released yet.

- Fix: adds support for capitalized Content-Type header https://github.com/redux-offline/redux-offline/pull/289
- Doc: add troubleshooting guideline for "Offline queue doesn't trigger on network status change" https://github.com/redux-offline/redux-offline/pull/300
- Typing: added constants type https://github.com/redux-offline/redux-offline/pull/290
- Doc: fix `enqueue` doc https://github.com/redux-offline/redux-offline/pull/315
- Typing: fix `offline` & `createOffline` type https://github.com/redux-offline/redux-offline/pull/328
- Typing: add missing config type https://github.com/redux-offline/redux-offline/pull/307

I personally want the typing fixes, that's why I'm asking for this 😅

**Comment by sorodrigo** [comment]
you're right, I make some time this week.

**Comment by sorodrigo** [comment]
sorry for the delay, latest version is up!
