### ISSUE TITLE
Deprecation of  react native NetInfo

### ISSUE THREAD

**Issue by ulziiburend** [redux-offline/redux-offline#340]
Hello. I guess on your compiled library there is deprecation on method NetInfo.getConnectionInfo
Could you please update your dependency? 

```js
// detectNetwork.native.js
var isLegacy = typeof _reactNative.NetInfo.getConnectionInfo === 'undefined';
exports.default = function (callback) {
  return isLegacy ? new _detectNetworkNative2.default(callback) : new DetectNetwork(callback);
};
```
Related link
[https://github.com/react-native-community/react-native-netinfo](https://github.com/react-native-community/react-native-netinfo)

**Comment by sorodrigo** [comment]
https://github.com/redux-offline/redux-offline/pull/339#issuecomment-514289256

**Comment by usrbowe** [comment]
@sorodrigo can this be mentioned somewhere in README. Would help to navigate folks upgrading to RN60. 
I actually myself blindly update to latest version, when I saw new release, and later figure out I need to be on `yarn add @redux-offline/redux-offline@native.0` version.

**Comment by calumpeak** [comment]
@usrbowe If you have a spot of time a PR wouldn't go amiss for this!

**Comment by anupgusain** [comment]
Hi friends quick fix for Net Info error with redux offline
use redux-offline version @redux-offline/redux-offline: "2.5.2-native.0" 

and if you get error handler is not a function, handler is "change" then use
@react-native-community/netinfo: "4.7.0"

read [#339 (comment)](https://github.com/redux-offline/redux-offline/pull/339#issuecomment-514289256) of @sorodrigo
