### ISSUE TITLE
Network status online but items never leave outbox

### ISSUE THREAD

**Issue by connercms** [redux-offline/redux-offline#345]
### Are you using `offline()` or `createOffline()` API?
createOffline() 

### Store config

```js
const persistConfig = {
  key: "root",
  version,
  storage,
  migrate: createMigrate(migrations, { debug: false })
};

const persistedReducer = persistReducer(
  persistConfig,
  offlineEnhanceReducer(reducers)
);

const middlewares = [logger, thunk, reduxObserver, offlineMiddleware];
// reduxObserver is just a custom middleware that writes values to Firebase when certain actions occur

export default function configureStore() {

  let store = createStore(
    persistedReducer,
    compose(
      offlineEnhanceStore,
      applyMiddleware(...middlewares)
    )
  );

  const persistor = persistStore(store);

  // persistor.purge();

  return { store, persistor };
}
```

### Offline config

Are you using a custom configuration? If you are please paste your config below.
```js
const {
  middleware: offlineMiddleware,
  enhanceReducer: offlineEnhanceReducer,
  enhanceStore: offlineEnhanceStore
} = createOffline({
  ...offlineConfig,
  persist: false,
  effect: effect => axios(effect).then(response => response.data),
  discard: (error, _action, _retries) =>
    new Promise(resolve => {
      const { request, response } = error;
      if (!request) throw error; // There was an error creating the request
      if (!response) return false; // There was no response

      let discard = response.status >= 400 && response.status <= 500;

      // Alert the user that the action has failed. Must return a promise that resolves to a boolean
      Alert.alert(
        "Error",
        "There was an issue " +
          _action.type.toLowerCase() +
          ". Please try again or report this error. We apologize for the inconvenience.",
        [
          {
            text: "Ok",
            onPress: () => resolve(discard)
          }
        ],
        {
          cancelable: false
        }
      );
    })
});
```

### Are you reporting a bug?
No, most likely a setup issue 

When I toggle my wifi offline, the Offline/STATUS_CHANGED action is dispatched correctly, and the online value is set to false. However, when I toggle my wifi back online, no action is ever dispatched to set online back to true, and if anything was in my outbox, it is never retried, and all further actions are piled up in the outbox as well.

**Comment by calumpeak** [comment]
Hi 👋 
Are you doing the setup with persist v5 here also?

Just to confirm, when you change network connectivity (e.g. in the network tab of dev tools) you don't see ` Offline/STATUS_CHANGED` get re-dispatched again?

**Comment by connercms** [comment]
Hi, yes I am using persist v5. 

One of two things happens: Offline/STATUS_CHANGED doesn't get re-dispatched and items never leave queue, but sometimes Offline/STATUS_CHANGED does get re-dispatched but still items don't leave the outbox.

**Comment by connercms** [comment]
The former happens when testing on simulator. In this case, if I refresh the application it sets the network status correctly and also empties the outbox. I am toggling the wifi on my Mac to simulate network disconnect (checking the Offline option in dev tools doesn't seem to work for me). 

The latter happens on a physical device. Same thing though, if I completely close the application and then reopen it, the items will leave the outbox.

**Comment by connercms** [comment]
I think the first issue above (not dispatching Offline/STATUS_CHANGED) is probably to do with Expo offline capabilities in the simulator, so I believe what is actually happening is [this issue](https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/troubleshooting/offline-queue-trigger.md). However, I do have my offline enhancer coming first. Do you see any issues with my store setup?

**Comment by connercms** [comment]
I am using custom effect reconciler to use axios, and per [this comment](https://github.com/redux-offline/redux-offline/issues/165#issuecomment-357271424) on an issue a while back I thought it was not necessary to stringify data if using axios vs fetch. 

Changing my action creator to JSON.stringify the data key seems to be working for me so far - items are again leaving the queue. 

```
export const createCallLog = log => {
  const uid = uuidv1();
  return {
    type: DispatchTypes.CREATE_CALL_LOG,
    uid,
    log,
    meta: {
      offline: {
        effect: {
          url: "dispatch/create_call_log",
          method: "POST",
          data: JSON.stringify(log)
        },
        commit: { type: DispatchTypes.CREATE_CALL_LOG_COMMIT, log },
        rollback: { type: DispatchTypes.CREATE_CALL_LOG_ROLLBACK, uid, log }
      }
    }
  };
};
```

My understanding of the whole subject might not be the best. Is there a reason why this change allows it to work?

**Comment by calumpeak** [comment]
When using the custom version, can you see retry actions happening? If that's the case it's likely that your data is malformed and you're getting error codes back from the server and the items are getting retried on the decay scale. if you've changed your reconciler and it's working again, this is possibly what's happening. I'd need more info to debug this further though/sandbox if you have one.

**Comment by stvmachine** [comment]
I got the same problem on React Native, the connectivity changes trigger the `Offline/STATUS_CHANGED` action but the outbox is just stuck until a new item is added. I can see retries only when the server is not available.

**Comment by calumpeak** [comment]
@stvmachine can you send me an example of your setup please. I'm not familiar with react native, but I'll do my best to take a look into it for you.

**Comment by stvmachine** [comment]
Sure @calumpeak. Sorry, if it's doesn't look to simple to debug. I'm combining with `redux-starter-kit` and `redux-persist@5`. 

Not sure what could be the source of the problem because it's still detecting network status changes and updating the redux state, but it's not resuming the queue automatically.

```javascript
import { configureStore } from 'redux-starter-kit';
import { persistStore, persistReducer } from 'redux-persist';
import { createLogger } from 'redux-logger';
import createSagaMiddleware from 'redux-saga';
import { createOffline } from '@redux-offline/redux-offline';
import storage from 'redux-persist/lib/storage';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults/index';
import { rootReducer } from '../reducers';
import sagas from '../sagas';

const persistConfig = {
  key: 'root',
  storage,
  transforms: [blacklistParamsTransform],
};

// we are using redux-persist to persist data directly,
// so we have to disable the default option on redux-offline
const customOfflineConfig = {
  ...offlineConfig,
  persist: false,
};

const middlewareList = [];
const sagaMiddleware = createSagaMiddleware();

middlewareList.push(sagaMiddleware);

if (__DEV__) {
  middlewareList.push(createLogger());
}

const {
  middleware: offlineMiddleware,
  enhanceReducer: offlineEnhanceReducer,
  enhanceStore: offlineEnhanceStore,
} = createOffline(customOfflineConfig);

const persistedReducer = persistReducer(
  persistConfig,
  offlineEnhanceReducer(rootReducer),
);

const store = configureStore({
  reducer: persistedReducer,
  devTools: true,
  enhancers: [offlineEnhanceStore],
  middleware: [...middlewareList, offlineMiddleware],
});

const persistor = persistStore(store);

sagas.forEach(saga => sagaMiddleware.run(saga));

export { store, persistor };
```

**Comment by stvmachine** [comment]
So, I was checking the troubleshooting guide about the [offline queue trigger](https://github.com/redux-offline/redux-offline/blob/develop/docs/recipes/troubleshooting/offline-queue-trigger.md) and I compared with the `compose` logic used internally on `redux-starter-kit` and it uses different order to set up the enhancers. I created a link on that repo too: https://github.com/reduxjs/redux-starter-kit/issues/184#issue-488168726. But I fixed using`createStore`. Thanks for everything!


This works for me:

```javascript
import { applyMiddleware, createStore } from 'redux';
import { composeWithDevTools } from 'redux-devtools-extension/developmentOnly';
import { persistStore, persistReducer } from 'redux-persist';
import { createLogger } from 'redux-logger';
import createSagaMiddleware from 'redux-saga';
import { createOffline } from '@redux-offline/redux-offline';
import storage from 'redux-persist/lib/storage';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults/index';
import { rootReducer } from '../reducers';
import sagas from '../sagas';
import { effect, discard } from './offlineConfig';

const persistConfig = {
  key: 'root',
  storage,
};


const sagaMiddleware = createSagaMiddleware();
const middlewareList = [sagaMiddleware];

if (__DEV__) {
  middlewareList.push(createLogger());
}

const {
  middleware: offlineMiddleware,
  enhanceReducer: offlineEnhanceReducer,
  enhanceStore: offlineEnhanceStore,
} = createOffline(customOfflineConfig);

const persistedReducer = persistReducer(
  persistConfig,
  offlineEnhanceReducer(rootReducer),
);

const middlewareEnhancer = applyMiddleware(
  ...middlewareList,
  offlineMiddleware,
);
const composedEnhancers = composeWithDevTools(
  offlineEnhanceStore,
  middlewareEnhancer,
);

const store = createStore(persistedReducer, composedEnhancers);
const persistor = persistStore(store);

sagas.forEach(saga => sagaMiddleware.run(saga));

export { store, persistor };

```

**Comment by calumpeak** [comment]
Glad you found the solution
