### ISSUE TITLE
Redux Offline & Connected Router

### ISSUE THREAD

**Issue by grantmac** [redux-offline/redux-offline#346]
### Are you using `offline()` or `createOffline()` API?
offline()

### Store config
Please paste your config below.
```js
const store = createStore(
  RootReducer(history),
  composeEnhancer(
    applyMiddleware(routerMiddleware(history), thunk),
    offline(offlineConfig)
  )
);
```

### Offline config

Are you using a custom configuration? If you are please paste your config below.
```js
@redux-offline/redux-offline/lib/defaults
```

I am building a react web app with both connected router and redux-offline. Redux Offline works perfectly but the issue is that it is persisting the router store also. This means that if you load domain.com/thing and then try to load domain.com/ you will automatically be pushed back to domain.com/thing as the router reducer is being hydrated. Is there a way to exclude the exclude the router reducer from redux-offline?

**Comment by calumpeak** [comment]
Hi @grantmac as redux-offline uses redux-persist under the hood, please configure your [persist options](https://github.com/redux-offline/redux-offline/blob/develop/docs/api/config.md#persistoptions) as specified in the docs and provide a [blacklist of reducer keys](https://github.com/rt2zz/redux-persist/tree/v4#persiststorestore-config-callback) that you don't want to be persisted.

That should fix your issue 😄

**Comment by grantmac** [comment]
Thank you @calumpeak
