### ISSUE TITLE
Update AsyncStorage to community packager for RN60

### ISSUE THREAD

**Issue by usrbowe** [redux-offline/redux-offline#349]
Not sure if I'm missing something, but how come there is still AsyncStorage imported directly from `react-native` in `@redux-offline/redux-offline@native.0` tag?

Referencing to: https://github.com/redux-offline/redux-offline/blob/bf950fddab91fe55e41dc0084a51c5d70806a7cc/src/defaults/persist.native.js#L4

Shouldn't that be imported from community package, since it was extracted in RN60?

So instead of
```
import { AsyncStorage } from 'react-native';
```
should be like
```
import AsyncStorage from '@react-native-community/async-storage';
```

**Comment by sorodrigo** [comment]
That branch currently only contains the fix for `NetInfo` if you make a PR I'm happy to merge the `AsyncStorage` fix.

**Comment by usrbowe** [comment]
Solved in latest release in **native** branch: https://www.npmjs.com/package/@redux-offline/redux-offline/v/2.5.2-native.1
