### ISSUE TITLE
Access to dispatch

### ISSUE THREAD

**Issue by n-sviridenko** [redux-offline/redux-offline#35]
Is it possible to add access to `dispatch` from `EffectsReconciler`?

```diff
-type EffectsReconciler = (effect: any, action: OfflineAction) => Promise<any>
+type EffectsReconciler = (effect: any, action: OfflineAction, { dispatch }) => Promise<any>
```

**Comment by jbovenschen** [comment]
You can already access the store.dispatch if you have setup redux.
It will look something like the following: 

```js
import { applyMiddleware } from 'redux';
import { createOfflineStore } from 'redux-offline';
import offlineConfig from 'redux-offline/lib/defaults';

const store = createOfflineStore(
  reducer,
  preloadedState,
  applyMiddleware(middleware),
  {...offlineConfig, {
    effect: (effect, action) => {
      const dispatch = store.dispatch;
      //.... Do your stuff
    }
  }} 
);
```

**Comment by ForumT** [comment]
Hi.. every time I override effect: (effect, action) => { } or effect: (effect, _action) => { } i get the error:

Uncaught TypeError: Cannot read property 'then' of undefined at line:

return config.effect(metadata.effect, action).then(function (result) { }

Can you help me with where I am going wrong?
