### ISSUE TITLE
Cannot read property 'getConnectionInfo' of undefined

### ISSUE THREAD

**Issue by ethanneff** [redux-offline/redux-offline#351]
### Issue

Cannot use `redux-offline` with `react-native 0.60.5`

### Are you using `offline()` or `createOffline()` API?
`offline()`
_If you're using `createOffline()` API, be sure to use `compose()` in the right order._

### Store config
Please paste your config below.
```js
import { offline } from "@redux-offline/redux-offline";
import offlineConfig from "@redux-offline/redux-offline/lib/defaults";
import {
  applyMiddleware,
  combineReducers,
  compose,
  createStore,
  Middleware
} from "redux";
import thunk, { ThunkAction } from "redux-thunk";
import { DeepReadonly } from "utility-types";
import {
  ItemActions,
  itemReducer,
  Items,
  ListActions,
  listReducer,
  Lists
} from "../../apps/Checklists/models";
import {
  Choices,
  ChoicesActions,
  choicesReducer,
  Questionnaires,
  QuestionnairesActions,
  questionnairesReducer,
  Questions,
  QuestionsActions,
  questionsReducer,
  Responses,
  ResponsesActions,
  responsesReducer
} from "../../apps/Debug/screens/Questionnaire/models";
import {
  AppActions,
  appReducer,
  AppState,
  AuthActions,
  authReducer,
  AuthState,
  DeviceActions,
  deviceReducer,
  DeviceState,
  Navigation,
  NavigationActions,
  navigationReducer,
  Theme,
  ThemeActions,
  themeReducer
} from "../../models";

/* INTERFACES */
export type RootState = DeepReadonly<{
  app: AppState;
  auth: AuthState;
  device: DeviceState;
  items: Items;
  lists: Lists;
  navigation: Navigation;
  questions: Questions;
  choices: Choices;
  responses: Responses;
  questionnaires: Questionnaires;
  theme: Theme;
}>;

/* REDUCERS */
const reducers = combineReducers<RootState>({
  app: appReducer,
  auth: authReducer,
  choices: choicesReducer,
  device: deviceReducer,
  items: itemReducer,
  lists: listReducer,
  navigation: navigationReducer,
  questionnaires: questionnairesReducer,
  questions: questionsReducer,
  responses: responsesReducer,
  theme: themeReducer
});

/* ACTIONS */
export type RootAction =
  | AppActions
  | DeviceActions
  | AuthActions
  | ListActions
  | ItemActions
  | NavigationActions
  | QuestionnairesActions
  | QuestionsActions
  | ChoicesActions
  | ResponsesActions
  | ThemeActions;
export type RootThunkAction<R> = ThunkAction<R, RootState, {}, RootAction>;

/* CONSTANTS */
const middlewares: Middleware[] = [thunk];
const composers =
  (window as any).__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
const enhancers = composers(
  applyMiddleware(...middlewares)
  offline(offlineConfig)
);

/* STORE */
export const store = createStore(reducers, enhancers);
```

### Offline config
No

### Are you reporting a bug?
Yes

**Comment by yanavozniuk** [comment]
The Same problem.

**Comment by sorodrigo** [comment]
Are u using the native version? `npm i @redux-offline/redux-offline@native`?

**Comment by ethanneff** [comment]
I am not using the native version. I migrated over to [redux-persist](https://github.com/rt2zz/redux-persist) as a short term fix.

**Comment by yanavozniuk** [comment]
> Are u using the native version? `npm i @redux-offline/redux-offline@native`?

Yeap, I using version for react-native 0.60+ 
![image](https://user-images.githubusercontent.com/20224167/64266862-00cf0500-cf3e-11e9-862c-3589fad9dc36.png)

**Comment by ethanneff** [comment]
Likewise, this error came up once I upgraded react-native from 0.59.5 to 0.60.5

**Comment by izkmdz** [comment]
We are also running into this same issue with redux-offline `2.5.2-native.1` while attempting to migrate our project to react-native `0.60.5`.

This is the error:
```
Cannot read property 'getConnectionInfo' of undefined
``` 
It could be related to NetInfo being removed from version `0.60`. Importing [react-native-netinfo](https://github.com/react-native-community/react-native-netinfo) as a package and using `resolutions` as described [here](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/443#issuecomment-515574105) has unfortunately not solved the issue.

**Comment by ethanneff** [comment]
Maybe `redux-offline` needs a limit update like `redux-persist` 6.0.0? https://github.com/rt2zz/redux-persist/releases/tag/v6.0.0

**Comment by sorodrigo** [comment]
Have you tried this? https://github.com/redux-offline/redux-offline/issues/353

**Comment by sorodrigo** [comment]
Using the native version fixes this and theres no migration needed besides installing the extra dependencies

**Comment by yanavozniuk** [comment]
> Using the native version fixes this and theres no migration needed besides installing the extra dependencies

We was importing `react-native-netinfo` package, and tested this package. It works (`react-native-netinfo`) But its not help resolve problem with `redux-offline`

**Comment by calumpeak** [comment]
@yanavoznuk do you have `@react-native-community/netinfo` in your dependencies?

**Comment by yanavozniuk** [comment]
Yeap - http://joxi.ru/823WWnji9Y7vy2

**Comment by calumpeak** [comment]
Ah, I see the issue. the community package is a stripped down version of the original net info package and there are a couple of methods that do not exist anymore. I think it may also be getting confused between the pre-existing legacy (the legacy, legacy) implementation.

I'm going to take a little dive into this, bare with me though as even though I'm a maintainer I've not touched the native side of the code yet/used RN. I think this should be simple to fix though (hopefully) - but I've got to bootstrap that environment first.

In the mean time you might be able to roll your own network detect (copy the existing in src and make the necessary changes).

**Comment by yanavozniuk** [comment]
> Ah, I see the issue. the community package is a stripped down version of the original net info package and there are a couple of methods that do not exist anymore. I think it may also be getting confused between the pre-existing legacy (the legacy, legacy) implementation.
> 
> I'm going to take a little dive into this, bare with me though as even though I'm a maintainer I've not touched the native side of the code yet/used RN. I think this should be simple to fix though (hopefully) - but I've got to bootstrap that environment first.
> 
> In the mean time you might be able to roll your own network detect (copy the existing in src and make the necessary changes).

We can postpone work with the `redux-offline` package.... and wait u updating

**Comment by calumpeak** [comment]
@yanavoznuk @ethanneff  @izkmdz Are you seeing this issue with iOS or android?

I have my development environment set up (iOS) and I'm seeing no issues with the current package.
My setup: 
![image](https://user-images.githubusercontent.com/10559737/64414459-48af7280-d08b-11e9-9cbb-4cf5d6a696dd.png).


When I log the netinfo package in my environment I see all methods available for use:
![image](https://user-images.githubusercontent.com/10559737/64414575-814f4c00-d08b-11e9-828d-9e5020500b4f.png)
Even though some methods are deprecated, they haven't been removed from use just yet.

@yanavoznuk your error is coming from `_reactNative.NetInfo.getConnection`, if I force mine to error it comes straight from `_netInfo.methodName` which leads me to believe that your node_modules file isn't quite clean/up to date since it looks like it's pulling from RN directly, not the community package. Can you clean and re-install your node modules, make sure that you have run a `react-native link @react-native-community/netinfo` if necessary and run a `pod install` in the relevant directory.

**Comment by ebeltran1981** [comment]
@calumpeak I did follow your suggestion and still having the `NetInfo` undefined issue... See the attached project... it is a brand new `react-native init NetInfoDemo` project showing the problem...

[NetInfoDemo.zip](https://github.com/redux-offline/redux-offline/files/3613635/NetInfoDemo.zip)

@yanavoznuk besides @calumpeak suggestion, did you do something else?

**Comment by calumpeak** [comment]
@ebeltran1981 I'm not sure what was quite up with your package json. But upon the first install, it installed the none-native version of the package (was still relying on NetInfo from React-Native). 
I removed `@redux-offline` from your dependencies, ran Yarn again to make sure it was removed from node-modules without then I reinstalled `yarn add @redux-offline/redux-offline@native` and it was fine (maybe a case of your yarn/package lock json as well). 
(Btw, I'm on a brand new machine, so I don't have redux-offline linked etc).

I'm going to take a little look further - but I could get it to install correctly.

**Comment by ebeltran1981** [comment]
@calumpeak question... how can I identify which is the correct package that should be installed? also, can you post here your `yarn.lock` or `package-lock.json`? I would like to compare what's the difference from mine.

**Comment by calumpeak** [comment]
@ebeltran1981 I check `node_modules/@redux-offline/redux-offline/package.json` version. You can also check `node_modules/@redux-offline/redux-offline/src/defaults/detectNetwork.native.js` and see that it contains `import NetInfo from '@react-native-community/netinfo';`

From my yarn.lock

```
"@redux-offline/redux-offline@^2.5.2-native.1":
  version "2.5.2-native.1"
  resolved "https://registry.yarnpkg.com/@redux-offline/redux-offline/-/redux-offline-2.5.2-native.1.tgz#87603a0758191f57a7fc2112839a88b1c9534963"
  integrity sha512-<NOISE>
  dependencies:
    "@babel/runtime" "^7.5.5"
    redux-persist "^4.6.0"
```

**Comment by ebeltran1981** [comment]
@calumpeak just want to update you what is the latest. I am still getting the wrong package from NPM. To bypass the issue and continue with the upgrade to `react-native@0.60.5` I did pull the source code and packed the code from `2.5.2.native.1` and installed it directly from the tarball and it is working.

I did ask you for the lock file to compare the hashing of the packages and see if we are getting different files from the same tag at NPM. Anyways, I will revisit this topic when I am done fixing other issues related to the upgrade.

**Comment by calumpeak** [comment]
@ebeltran1981 I dropped a segment of my lockfile in the above post.

**Comment by ebeltran1981** [comment]
> @ebeltran1981 I dropped a segment of my lockfile in the above post.

thanks @calumpeak. I did not do anything and NPM started serving the right package now. Who knows what the issue was! Thanks for the willingness to help...

**Comment by calumpeak** [comment]
@ebeltran1981 my pleasure, glad I could help 👍
