### ISSUE TITLE
Unable to resolve module @react-native-community/netinfo

### ISSUE THREAD

**Issue by timwco** [redux-offline/redux-offline#353]
I know this has been addressed #340, and #323, but I'm still having issues.

The error:

```
Error: Unable to resolve module `@react-native-community/netinfo` from `/Users/.../node_modules/@redux-offline/redux-offline/lib/defaults/detectNetwork.native.js`: Module `@react-native-community/netinfo` does not exist in the Haste module map
```

"react": "16.8.6",
"react-native": "0.60.5",
"@redux-offline/redux-offline": "2.5.2-native.1"
"redux": "4.0.4",
"redux-persist": "5.10.0"

I had no problems until upgrading to React Native `0.60`.

**Comment by sorodrigo** [comment]
You need to install the @react-native-community/netinfo npm package.
