### ISSUE TITLE
NativeModule: AsyncStorage is null (Expo & Redux-Offline)

### ISSUE THREAD

**Issue by Bilal-Abdeen** [redux-offline/redux-offline#354]
I had a working app, which was built using Expo and uses Redux & Redux-Persist. I wanted to add Redux-offline to it. It stopped working and gave the following error message. 

```[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.```

I suspect the problem is related to a conflict between **Redux-offline, which uses Redux Persist v4 (and I think "storage"),** and **Expo (or my code), which uses Redux-persist v6 and "ExpoFileSystemStorage".** I tried to remove every reference in my code to Redux-Persist. However, this did not help. Following is my old, working code and the non-working statements. 

```
import { createStore, compose, applyMiddleware } from 'redux';
import thunk from 'redux-thunk';

import { persistStore, persistReducer } from 'redux-persist'; 
import ExpoFileSystemStorage from "redux-persist-expo-filesystem"; 

// Additional statements, which I added to support Redux-offline. 
// These (along with the statement below) caused the error. 
// import { offline } from '@redux-offline/redux-offline';
// import offlineConfig from '@redux-offline/redux-offline/lib/defaults';

import reducers from '../reducers';

const persistConfig = {
	key: 'root',
	storage: ExpoFileSystemStorage
};

const newPersistedReducer = persistReducer(persistConfig, reducers);

export const store = createStore(
	newPersistedReducer, 
	{},
	compose(
		applyMiddleware(thunk), 

		// An additional statement, which I added to support Redux-offline. 
		// This (along with the 2 statements above) caused the error. 
		// offline(offlineConfig)
	)
);

export const persistor = persistStore(store);
```

My package.json file follows: 

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.1",
    "@redux-offline/redux-offline": "^2.5.2-native.1",
    "axios": "^0.19.0",
    "expo": "^34.0.1",
    "expo-contacts": "^6.0.0",
    "expo-permissions": "^6.0.0",
    "firebase": "^6.5.0",
    "lodash": "^4.17.15",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-elements": "^1.2.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-modal-datetime-picker": "^7.5.0",
    "react-native-multiple-select": "^0.5.3",
    "react-native-multiple-select-list": "^1.0.4",
    "react-native-numeric-input": "^1.8.3",
    "react-native-offline": "^5.0.0",
    "react-native-reanimated": "^1.1.0",
    "react-native-screens": "1.0.0-alpha.22",
    "react-native-selectmultiple-button": "^0.1.105",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-textinput-effects": "^0.5.1",
    "react-native-web": "^0.11.4",
    "react-navigation": "^4.0.0",
    "react-navigation-stack": "^1.5.1",
    "react-navigation-tabs": "^2.4.0",
    "react-redux": "^7.1.1",
    "realm": "^3.0.0",
    "redux": "^4.0.4",
    "redux-persist": "^6.0.0",
    "redux-persist-expo-filesystem": "^2.0.0",
    "redux-thunk": "^2.3.0",
    "xdate": "^0.8.2"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0"
  },
  "private": true
}
```

**Comment by calumpeak** [comment]
@Bilal-Abdeen Expo currently does not work with `@react-native-community` modules, see [this issue](https://github.com/react-native-community/async-storage/issues/72) for more details. 
Since Expo is not on 0.60 of react-native yet, you should be fine to use the non-native package of redux offline which still relies on Async Storage from React-Native.

Modularity is something we're looking at for redux offline and how we can solve these issues going forward as react-native is in a bit of a transition right now.

**Comment by Bilal-Abdeen** [comment]
@calumpeak Thank you very much for taking the time to answer my question. I am sorry for the naive question, I am trying to build my 1st React-Native app. 

So, what is the common denominator for using Expo and Redux-offline? It would be highly appreciated if you can provide me with the necessary packages. As demonstrated in my code (above), currently, I am trying to use the following. 

import ExpoFileSystemStorage from "redux-persist-expo-filesystem"; 
import { offline } from '@redux-offline/redux-offline';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults';

**Comment by calumpeak** [comment]
@Bilal-Abdeen You should be fine with that setup - but you'll need to change the version of redux-offline. See the readme[ here ](https://github.com/redux-offline/redux-offline#for-react-native--059) for React Native <= 0.59. That should sort you out (You may need to remove the current entry from your package.json and re-install your node-modules)

**Comment by Bilal-Abdeen** [comment]
@calumpeak Thank you very much. This worked. 
I uninstalled: @redux-offline/redux-offline@native 
and installed: @redux-offline/redux-offline
