### ISSUE TITLE
Unable to resolve module @react-native-community/async-storage

### ISSUE THREAD

**Issue by Bilal-Abdeen** [redux-offline/redux-offline#355]
I had a working app, which uses Redux & Redux-Persist. I wanted to add Redux-offline to it. It stopped working and gave the following error message. 

```error: bundling failed: Error: Unable to resolve module `@react-native-community/async-storage` from `<My_Proj_Folder>\node_modules\@redux-offline\redux-offline\lib\defaults\persist.native.js`: Module `@react-native-community/async-storage` does not exist in the Haste module map```

Following is my old, working code and the non-working statements. 

```
import { applyMiddleware, createStore, compose } from 'redux';
import thunk from 'redux-thunk';

import { persistStore, persistReducer } from 'redux-persist'; 

import { AsyncStorage } from 'react-native';
// While troubleshooting, I tried the following, instead of the above. It still did NOT work. 
// import AsyncStorage from '@react-native-community/async-storage'; 

// Additional statements, which I added to support Redux-offline. 
// These (along with the statement below) caused the error. 
// import { offline } from '@redux-offline/redux-offline';
// import offlineConfig from '@redux-offline/redux-offline/lib/defaults';

import reducers from '../reducers';

const persistConfig = {
	key: 'root',
	storage: AsyncStorage, 
};

const newPersistedReducer = persistReducer(persistConfig, reducers);

export const store = createStore(
	newPersistedReducer, 
	{},
	compose(
		applyMiddleware(thunk), 

		// An additional statement, which I added to support Redux-offline. 
		// This (along with the 2 statements above) caused the error. 
		// offline(offlineConfig) 
	)
);

export const persistor = persistStore(store);
```

My package.json file follows: 

```
{
  "name": "myapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@redux-offline/redux-offline": "^2.5.2-native.1",
    "axios": "^0.19.0",
    "firebase": "^6.6.1",
    "lodash": "^4.17.15",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-elements": "^1.2.0",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.1",
    "react-native-modal-datetime-picker": "^7.5.0",
    "react-native-multiple-select": "^0.5.3",
    "react-native-multiple-select-list": "^1.0.4",
    "react-native-numeric-input": "^1.8.3",
    "react-native-offline": "^5.0.0",
    "react-native-reanimated": "^1.2.0",
    "react-native-screens": "^2.0.0-alpha.3",
    "react-native-selectmultiple-button": "^0.1.105",
    "react-native-simple-radio-button": "^2.7.3",
    "react-native-textinput-effects": "^0.5.1",
    "react-native-vector-icons": "^6.6.0",
    "react-navigation": "^4.0.5",
    "react-navigation-stack": "^1.8.0",
    "react-navigation-tabs": "^2.5.3",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-persist": "^6.0.0",
    "redux-thunk": "^2.3.0",
    "xdate": "^0.8.2"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/runtime": "^7.6.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.4.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by calumpeak** [comment]
Is this duplicate?

**Comment by Bilal-Abdeen** [comment]
No, this is not a duplicate. 

On your reply to issue #354, you informed me that there are compatibility issues with Expo. While trying to use another library, I had other compatibility issues with Expo. So, I thought it might be a good idea to stop using Expo. 

While re-building my app using React-Native (with no Expo), I came across the error message (above). So, I would appreciate your effort and time in investigating it.

**Comment by calumpeak** [comment]
@Bilal-Abdeen Have you followed all the steps on the package's[ install steps ](https://github.com/react-native-community/async-storage)(install, link, pod install)? 

Also if you're switching tacts and the old issue is no longer needed, please close it.

**Comment by Bilal-Abdeen** [comment]
@calumpeak As usual, your reply is spot on. I did not realize that I need to install other components. I thought that Redux-offline would include whatever it needs. Anyway, I went over those steps. That error message disappeared. However, I got another problem, for which I will create another issue. I think this would make it easier for others to find it. 

I tried to close this issue because there is NOT much in it. However, I could not find a way to do that. Please, feel free to delete it if you can.

**Comment by calumpeak** [comment]
@Bilal-Abdeen I'll update the documentation to flag that these are needed peer dependencies.

**Comment by Bilal-Abdeen** [comment]
@calumpeak  Thank you so much for that. 
It seems that the following is required as well. 
```npm install --save @react-native-community/netinfo```
