### ISSUE TITLE
Updating to React-Native 0.60.5 Causes DetectNetwork.Native.Legacy Error

### ISSUE THREAD

**Issue by cookiekitty** [redux-offline/redux-offline#357]
This error is happening when I attempt to use 'react-native run-ios'. It appears that these files were removed in a previous commit, what is still trying to access them?

### Are you using `offline()` or `createOffline()` API?
createOffline

### Store config
```
import { Store, createStore, compose, StoreEnhancer, applyMiddleware, Reducer, AnyAction} from 'redux';
import thunk from 'redux-thunk';
import { IApplicationState, createRootReducer } from './store/index';
import { createOffline } from '@redux-offline/redux-offline';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults';
import createSagaMiddleware from 'redux-saga';
import { rootSaga } from './store/sagas/AppSagas';

// Redux-Persist options
// Blacklist means the items will not be kept in memory.
offlineConfig.persistOptions = {
    blacklist: ['passport'],
};

const offlineEnhancer = createOffline(offlineConfig);
const initialState = {};
const sagaMiddleware = createSagaMiddleware();

export function configureStore() {
    const store: Store<IApplicationState> = createStore(
        offlineEnhancer.enhanceReducer(createRootReducer()) as Reducer<IApplicationState, AnyAction>,
        initialState,
        compose(
            offlineEnhancer.enhanceStore as StoreEnhancer,
            applyMiddleware(offlineEnhancer.middleware, thunk, sagaMiddleware),
        ),
    );

    // Turn on this function for debugging the state while the app is running
    sagaMiddleware.run(rootSaga);

    return store;
}

```

Dependencies:
"@react-native-community/async-storage": "^1.6.1",
"@react-native-community/cli": "^2.9.0",
"@react-native-community/netinfo": "^4.2.2",
"@redux-offline/redux-offline": "^2.5.2-native.1",
"react": "16.8.6",
"react-native": "0.60.5",
"react-redux": "^7.1.0",
"redux": "^4.0.1",
"redux-saga": "^1.1.1",
"redux-thunk": "^2.3.0"

Error: 
error: bundling failed: Error: Unable to resolve module `./detectNetwork.native.legacy` from `/Users/****/appname/node_modules/@redux-offline/redux-offline/lib/defaults/detectNetwork.native.js`: The module `./detectNetwork.native.legacy` could not be found from `/Users/****/appname/node_modules/@redux-offline/redux-offline/lib/defaults/detectNetwork.native.js`. Indeed, none of these files exist:
  * `/Users/****/appname/node_modules/@redux-offline/redux-offline/lib/defaults/detectNetwork.native.legacy(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/****/appname/node_modules/@redux-offline/redux-offline/lib/defaults/detectNetwork.native.legacy/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/****/appname/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/****/appname/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/****/appname/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/****/appname/node_modules/metro/src/lib/transformHelpers.js:264:42)
    at /Users/****/appname/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/****/appname/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/****/appname/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/****/appname/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by calumpeak** [comment]
Looks like you're pulling an old version. Please clean and install your node modules again. Please see similar issue here: https://github.com/redux-offline/redux-offline/issues/351#issuecomment-531697063

**Comment by cookiekitty** [comment]
After removing and re-installing my node_modules folder about 10 times...
I had to clear my npm cache with npm -- --reset-cache
and it finally worked
