### ISSUE TITLE
Can't get persistOptions to work

### ISSUE THREAD

**Issue by ChrisWiles** [redux-offline/redux-offline#359]
### Are you using `offline()` or `createOffline()` API?
Using createOffline

### Store config
```js
import { applyMiddleware, createStore } from 'redux';
import { compose } from 'recompose';
import { createOffline } from '@redux-offline/redux-offline';
import createSagaMiddleware from 'redux-saga';
import defaultConfig from '@redux-offline/redux-offline/lib/defaults';
import defaultQueue from '@redux-offline/redux-offline/lib/defaults/queue';
import persist from '@redux-offline/redux-offline/lib/defaults/persist';
import Reactotron from './ReactotronConfig';
// import enqueue from './enqueue';
import rootReducer from '../root';
import rootSaga from '../rootSaga';

const offlineConfig = {
  ...defaultConfig,
  queue: {
    ...defaultQueue,
    // enqueue,
  },
  persistOptions: {
    // blacklist: [],
    whitelist: ['nothing'],
  },
};

const { middleware: offlineMiddleware, enhanceReducer, enhanceStore } = createOffline(
  offlineConfig,
);

let sagaMiddleware;
let middleWare;

if (__DEV__) {
  const sagaMonitor = Reactotron.createSagaMonitor();
  sagaMiddleware = createSagaMiddleware({ sagaMonitor });
  middleWare = compose(
    applyMiddleware(sagaMiddleware, offlineMiddleware),
    Reactotron.createEnhancer(),
  );
} else {
  sagaMiddleware = createSagaMiddleware();
  middleWare = compose(applyMiddleware(sagaMiddleware, offlineMiddleware));
}

const store = createStore(
  enhanceReducer(rootReducer),
  compose(
    enhanceStore,
    middleWare,
  ),
);

sagaMiddleware.run(rootSaga, store.dispatch);

global.purgeRedux = persist(store).purge;

export default store;

```

I have tried multiple persistOptions and my store state is always the same, any ideas?

**Comment by calumpeak** [comment]
Yup - you’re using redux persist and redux offline here. Redux offline currently uses redux persist v4 - on our homepage there is the [documentation](https://gist.github.com/jarvisluong/f14872b9c7ed00bc2afc89c4622e3b55) to set this up with a newer version of redux persist. You need to set redux offline to persist:false and pass your persist options directly to redux persist.

**Comment by ChrisWiles** [comment]
> Yup - you’re using redux persist and redux offline here. Redux offline currently uses redux persist v4 - on our homepage there is the [documentation](https://gist.github.com/jarvisluong/f14872b9c7ed00bc2afc89c4622e3b55) to set this up with a newer version of redux persist. You need to set redux offline to persist:false and pass your persist options directly to redux persist.

this worked for redux persist v5 but not v6
