### ISSUE TITLE
Shows this warning -> "Warning: RNCNetInfo - You are using the deprecated API..." even with latest version

### ISSUE THREAD

**Issue by phuongwd** [redux-offline/redux-offline#361]
`YellowBox.js:71 Warning: RNCNetInfo - You are using the deprecated API. It will still work, but you must upgrade to the new API to receive the new features. The old API will be removed in the future`

refer https://github.com/react-native-community/react-native-netinfo/issues/123

**Comment by calumpeak** [comment]
https://github.com/redux-offline/redux-offline#for-react-native-060 Please use the net info & storage community packages for newer versions of react-native.
