### ISSUE TITLE
Unable to resolve module detectNetwork.native.legacy for @redux-offline/redux-offline 2.5.2-native.1

### ISSUE THREAD

**Issue by AlfBohra** [redux-offline/redux-offline#363]
<img width="404" alt="Screenshot 2019-10-18 at 7 59 50 PM" src="https://user-images.githubusercontent.com/56730886/67102973-fad96e80-f1e1-11e9-840e-52a9c5f0532e.png">

Package.json
 "@react-native-community/netinfo": "^4.4.0",
    "@redux-offline/redux-offline": "^2.5.2-native.1",
    "@sentry/react-native": "^1.0.9",
    "axios": "^0.18.0",
    "core-js": "^3.3.2",
    "deprecated-react-native-listview": "0.0.6",
    "lottie-react-native": "^2.5.10",
    "moment": "^2.22.2",
    "react": "16.8.6",
    "react-native": "0.60.5"

The dependency for the file detectNetwork.native.legacy.js has been removed in current version, so the error that I am getting is not justified. Please check the attached image.

Please help me resolve it as I am stuck on this issue for a few days now.

**Comment by sorodrigo** [comment]
Try this #357

**Comment by AlfBohra** [comment]
"npm start -- --reset-cache" worked for me. Thanks!
