### ISSUE TITLE
undefined is not an object  _reactNative.NetInfo.getConnectionInfo

### ISSUE THREAD

**Issue by Usamaliaquat123** [redux-offline/redux-offline#367]
![Bug](https://user-images.githubusercontent.com/33973828/68293825-9444c380-00b0-11ea-9986-650b995ed0cc.png)

### Configure Store
```
const store = createStore(
  reducers,
  {},
  compose(
    applyMiddleware(thuck),
    offline(offlineConfig),
  ),
);

```
### Run app
`react-native run-android`

### Error 
**undefined is not an object  _reactNative.NetInfo.getConnectionInfo**

**Comment by calumpeak** [comment]
Duplicate of #351
