### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by fossage** [redux-offline/redux-offline#37]
Hi there,

Really cool library!  I was curious if you have any plans on adding tests in the future.  I would love to be able to contribute and I generally find a good entry point for me into a new codebase is writing  some tests, so if it's something you're interested in, I would be happy to start putting some together.

**Comment by jevakallio** [comment]
Hi @fossage! I've [added jest](https://github.com/jevakallio/redux-offline/commit/3363fe44d83f8724dfc05c821efdb38819894fde) to the project, but am currently struggling finding time to contribute. Tests are more than welcome!

However please be aware that some [breaking changes](https://github.com/jevakallio/redux-offline/pull/17) are coming soon, so any tests for createOfflineStore are not necessary.

**Comment by fossage** [comment]
@jevakallio , okay great. I'll start putting some together and hopefully have a PR ready in the near future.  Aside from Jest, do you have any other testing utilities you prefer and/or want to avoid?  Lately I've been using a combination of jest and [redux-mock-store](https://github.com/arnaudbenard/redux-mock-store) for reducer testing which seems to be working pretty well.

**Comment by jevakallio** [comment]
@fossage redux-mock-store is great! I hadn't decided if I wanted to run store reducer tests as snapshot tests or regular chai assertions - either is fine.

**Comment by fossage** [comment]
@jevakallio , Cool yea I'm ambivalent on snapshots as well so I'll try to keep them to a minimum.  Do you want the tests to be set up to run on any Git hooks?

**Comment by jevakallio** [comment]
@fossage let's set up any git hooks separately if necessary I'd generally prefer to run the tests on Travis, so hooks may be overkill.
