### ISSUE TITLE
Good First Issue Suggestions

### ISSUE THREAD

**Issue by nickineering** [redux-offline/redux-offline#376]
Hey everyone,

Just curious if the maintainers of this repo have any suggestions as to good first issues for a new contributor to help move the project forward. I've been using redux offline in react native a lot at work and want to try improving it a bit, but don't want to waste my time on something inconsequential, or that will never get merged.

Thanks, this has been a really useful project for me.

**Comment by sorodrigo** [comment]
please give me an email for the slack group

**Comment by nickineering** [comment]
> please give me an email for the slack group

nferrara100@gmail.com
