### ISSUE TITLE
NetInfo deprecated warnings

### ISSUE THREAD

**Issue by jakejackson1** [redux-offline/redux-offline#39]
Just testing out this package and noticed a few deprecated warnings:

`NetInfo.fetch() is deprecated. Use NetInfo.getConnectionInfo() instead`
`NetInfo's "change" event is deprecated. Listen to the "connectionChange" event instead`

**Comment by sorodrigo** [comment]
Thanks! I'm aware of this changes. Will update them asap.

**Comment by kbrandwijk** [comment]
As I read in https://github.com/redux-offline/redux-offline/issues/49 that a new release might be imminent, I submitted a PR to get rid of those pesky warnings.

**Comment by sorodrigo** [comment]
Thanks! 😄
