### ISSUE TITLE
204 status code

### ISSUE THREAD

**Issue by rosskhanas** [redux-offline/redux-offline#39]
204 is a valid status code of a response with no content.

Line 18 in https://github.com/jevakallio/redux-offline/blob/master/src/defaults/effect.js breaks successful responses while trying to get the content.

Not sure what is the best solution for this, but possibly can check for `contentType.indexOf('text')` to do a `res.text()` and return empty response in other cases.

**Comment by jevakallio** [comment]
Good catch!

I think relying on the `text` content type of 204's is not robust enough. I think reading the response body as text, checking if it's not empty, and attempting to parse is the way to go.

Will fix this shortly.

**Comment by jevakallio** [comment]
This should now be fixed by https://github.com/jevakallio/redux-offline/commit/7a0ce8919db160ee4a2ef053fa544ecb90dbf45c

**Comment by rosskhanas** [comment]
@jevakallio actually no. There are no usually 'content-type' specified when you have 204 response, since there are no content. It means that `res.headers.get('content-type');` return a null value. So `contentType.indexOf('json')` throws an error.
