### ISSUE TITLE
Can not setup redux-offline

### ISSUE THREAD

**Issue by lisa-nguyen-goldenowl** [redux-offline/redux-offline#398]
Can you guys help me about question related to setup redux-offline.

my setup:
- expo sdk 37
- React Native 0.61.4
- Redux-offline: 2.5.2-native.3
After i update expo and redux offline. I am having an async store library problem.

<img width="337" alt="Screen Shot 2020-05-08 at 10 54 58" src="https://user-images.githubusercontent.com/52815733/81368617-66514200-911a-11ea-8010-b26aeb69c3e0.png">

 In `redux-offline/src/defaults/persist.native.js` :
i see `import AsyncStorage from '@react-native-community/async-storage'; // eslint-disable-line
`. but for expo they don't use it. They use `import { AsyncStorage } from 'react-native';`

Can you guys show me how to fix it 🙏 🙏 🙏 . Thank you !!!
<img width="692" alt="Screen Shot 2020-05-08 at 10 39 19" src="https://user-images.githubusercontent.com/52815733/81367769-4882dd80-9118-11ea-9f93-ed9c21146d9d.png">

<img width="982" alt="Screen Shot 2020-05-08 at 10 14 34" src="https://user-images.githubusercontent.com/52815733/81367578-dc07de80-9117-11ea-91bc-b2a788f4e817.png">

**Comment by sorodrigo** [comment]
yarn add @redux-offline/redux-offline@expo
