### ISSUE TITLE
Offline outbox not restored from redux-persist

### ISSUE THREAD

**Issue by sorodrigo** [redux-offline/redux-offline#4]
Hello!! I know that in the original repo [this](https://github.com/jevakallio/redux-offline/pull/70) issue is affecting a lot of users. In this fork we never got to merge the PR into our code, this was because we never got around to test it. And we weren't able to replicate it. I suppose that in our app we never met the necessary conditions.

Moreover, I think that this is a BIG issue and a lot of people are waiting for it to be merged in the original repo. I think we should test the PR and if everything seems to be ok, we should merge it into our codebase.
What do you guys think? @bsouthga @wacii @sebasgarcep @j8seangel

**Comment by sebasgarcep** [comment]
@McPo's solution is working fine for me in a medium-sized project and it's a one-line fix. Why don't we apply it?

**Comment by sorodrigo** [comment]
could make the PR?

**Comment by wacii** [comment]
I agree. Created the PR.

**Comment by sorodrigo** [comment]
Awesome thanks!!

**Comment by sebasgarcep** [comment]
Thanks @wacii !
