### ISSUE TITLE
conceptual question

### ISSUE THREAD

**Issue by rileylnapier** [redux-offline/redux-offline#40]
hi friends.  i've just gotten into using redux-localstorage and redux-persist.

redux-offline has peaked my interest but i have a question to see if it could solve this problem.

if i dispatch an async api action... optimistically update my state before the api returns and refresh the page before the api responds, will redux-offline, when the page is refreshed have context on this request not being fulfilled?  will it retry?  will it rollback?

right now i have a problem in which my remote and local state get out of sync and then refreshing the page, my local stage gets overriden by remote state and my page flashes.

**Comment by wacii** [comment]
It will retry. The main benefit of the library is that it retries requests across sessions. It will not, however, know whether the original request was successful, so you might get duplicate requests.

**Comment by wacii** [comment]
If you still have questions, feel free to open new issues on the main repo.
