### ISSUE TITLE
Not able to rollback in case of no connectivity

### ISSUE THREAD

**Issue by ankit07683** [redux-offline/redux-offline#407]
Hi, I am very new to this package. Please help me.
As discussed in issue 180 you have stated that returning null | undefined from retry() will stop from retrying and will immediately call rollback.
when i am trying this in latest version it do not call rollback, it always wait for connectivity.

here is my retry function:
```
const retry = (_action, retries) => {
  return null;
};

const config = {
  ...defaultConfig,
  retry,
  returnPromises: true
};

const store = createStore(
  reducer,
  compose(
    offline(config), 
    applyMiddleware(tickMiddleware)
  )
);
```

**Comment by sorodrigo** [comment]
hello, could you share a reproduction of the bug

**Comment by sobrinho** [comment]
Just tested with latest version and it worked with the retry you provided by returning null.
