### ISSUE TITLE
Unexpected key offline in preloaded state

### ISSUE THREAD

**Issue by BlakeRxxk** [redux-offline/redux-offline#41]
I've got this error with react-native app and HMR:
Unexpected key "offline" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: "user". Unexpected keys will be ignored.

my configureStore.js
```js
/* global __DEV__ */
import { applyMiddleware, createStore, compose } from 'redux';
import { offline } from '@redux-offline/redux-offline';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults';

const createStoreWithMiddleware = compose(
  applyMiddleware(
    ...middlewares,
  ),
  offline({
    ...offlineConfig,
    persistOptions: {
      whitelist: ['user'],
    },
  }),
)(createStore);
const store = createStoreWithMiddleware(reducers);


if (module.hot) {
  module.hot.accept(() => {
    const nextRootReducer = require('../modules/index').default; // eslint-disable-line
    store.replaceReducer(nextRootReducer);
  });
}

export default store;
```

something wrong with my code or is there bug in redux-offline

**Comment by wacii** [comment]
It's a bug with redux-offline. Issue #31 reports the same issue. This should be addressed by PR #32.

**Comment by BlakeRxxk** [comment]
My bad, didn't noticed PR, i think issue could be closed as duplicate

**Comment by wacii** [comment]
#32 has been merged so this should be fixed in the next release.
