### ISSUE TITLE
Using redux-offline with Vue

### ISSUE THREAD

**Issue by ibarral** [redux-offline/redux-offline#42]
Hello,

Is there a guide to use this library with Vue?

I read on the blog post that Vue is supported, but i can't find a mention or a guide for this on the docs. 

I'm using Vue with Vuex (a state manager like Redux). It's possible to use this library with Vuex?

Thanks, and great work!!!

**Comment by jevakallio** [comment]
@ibarral I have not tried to use this library with Vue, but my assumption was that you'd be able to use a Redux store with Vue with or without Vuex. 

In retrospect, the createOfflineStore API makes this hard. Once I'm able to land https://github.com/jevakallio/redux-offline/pull/17, I think it should get easier.

Is there a simple Vuex sample repo I could try this in?
