### ISSUE TITLE
When are actions added to the outbox queue?

### ISSUE THREAD

**Issue by jthegedus** [redux-offline/redux-offline#43]
Which determines whether an action is added to the outbox queue, the Promise result from ``meta.offline.effect`` or the network status from ``state.offline.online``? If the latter when is the enqueue decision made, before the effectReconciler is fired?

**Comment by benvp** [comment]
@jthegedus  As for my understanding of the code base, the action is enqueued if it has the `action.meta` and the `action.meta.offline` key. Actions with an `offline` key are always enqueued in the outbox. The reconciler should run afterwards. Have a look: https://github.com/jevakallio/redux-offline/blob/master/src/updater.js#L70

**Comment by jthegedus** [comment]
@benlime Thanks for the direct link. I was having trouble discerning whether the ``state.offline.online`` was the only factor stopping the effectsReconciler from firing an enqueued action, which raised the question of the outbox/effectsReconciler order.

The section in the docs about retrying
>we will always retry the first message in the queue when the network detector reports a change from offline to online

and the section about network availability
> It can also be "Yes, but not really". The network receiver on your mobile device may report connectivity, but if you can't reach the remote server, are we really connected?

made me wonder whether this library was being tricky and attempting to perform the ``effect`` in the case that the network availability was unstable, but where success possible. Having read this <https://github.com/jevakallio/redux-offline/blob/master/src/middleware.js#L62> I now have my answer. It does the thing you want and expect ;) A mark of a good library.

A suggestion to the docs would be to emphasize that the ``state.offline.online`` is the gatekeeper to stop the ``effect``s occurring. And that to get to the ``effectsReconciler`` the action **must** go through the ``outbox``.  Maybe I've just read, re-read and thought about the docs so many times I've confused myself.

EDIT: Not sure what the etiquette is with closing my own issue, but since my question was answered I will just do it and hope nothing catches fire :sweat_smile:
