### ISSUE TITLE
Override queue?

### ISSUE THREAD

**Issue by piranna** [redux-offline/redux-offline#45]
How can I be able to override the requests queue? I would allow to the user to do logout and some time later login again, but if there has been some conectivity errors in the past and the requests queue is not empty, then login will be delayed until all previous requests have been commited instead of allowing to do login and keep doing them in background. Is it possible to override the requests queue abd do this someway?

**Comment by wacii** [comment]
You could fiddle with the request queue. Move the last item in `state.offline.outbox`, the most recent request, into the second position. That would probably work.

Other solutions include implementing parallel resolution or priorities. Neither of which I am interested in at the moment. Otherwise you could just reset the requests queue. This has been asked before and is something I might tackle in the near future. It is, however, a little more involved than just `state.offline.outbox = []`.

**Comment by sorodrigo** [comment]
The reset outbox feature is implemented. You can just import and dispatch the action

**Comment by wacii** [comment]
So it is... 

If you send a request, then reset and add an offline action before the request resolves, you will end up losing that new action. That said, I don't think this can actually happen in practice. So I suppose it is as simple as `state.offline.outbox = []`.

**Comment by piranna** [comment]
> Other solutions include implementing parallel resolution or priorities

Priorities support is just what my boss asked me to investigate for, just only I wanted to know if there was another alternative implemented that I could use like for example be able to do out-of-queue requests for some specific storage namespace. If you are interested, I can be able to take a look about replacing the outbox queue by a priority queue...

**Comment by wacii** [comment]
Thanks for the offer, but I don't want to do that yet. There are enough things to do to get the current  implementation working properly before adding more features.

**Comment by jaulz** [comment]
@sorodrigo how can we use the reset outbox feature? Thanks! :)

**Comment by wacii** [comment]
Ah, looks like that hasn't made it into the readme. I'll have to add that.

```js
import { RESET_STATE } from "@redux-offline/redux-offline/lib/constants";
store.dispatch({ type: RESET_STATE });
```

**Comment by jaulz** [comment]
Thanks! :-)

**Comment by piranna** [comment]
I have somewhat implemented my boss requeriment by totally ignoring redux-offline and doing my own fetch requests on top of redux-offline. Another solution would have been to use diferent redux-offline instances, but redux-persist don't recomend it and instead propose to use reducers composition. Maybe this could be a posibility, by allowing to have several outbox queues and manage them independently, or maybe full instances of redux-offline. So far they don't use the same reducers (both for data or internal redux-offline status) it should work allright..

**Comment by wacii** [comment]
There is a draft for queue customization at [PR #136](https://github.com/redux-offline-team/redux-offline/pull/136) over in the main repo. Probably a bit late for your purposes though.

**Comment by sorodrigo** [comment]
Awaiting on the official repo. Closing.
