### ISSUE TITLE
Add Changelog

### ISSUE THREAD

**Issue by wacii** [redux-offline/redux-offline#48]
~Probably want to wait for the repos to be merged before going ahead with this~, but as we are adding features a changelog would be useful I think.

**Comment by wacii** [comment]
_As an example..._

Unreleased

- Immutable js root state ([@fabriziomoscon](https://github.com/fabriziomoscon) and [@ashmalech](https://github.com/ashmalech) in [PR#42](https://github.com/redux-offline/redux-offline/pull/42))
- Optional commit/rollback ([@sebasgarcep](https://github.com/sebasgarcep) in [PR#30](https://github.com/redux-offline/redux-offline/pull/30))
- Fix regression in `detectNetwork()` ([@jaulz](https://github.com/jaulz) in [PR#20](https://github.com/redux-offline/redux-offline/pull/20))

2.1.0

...

**Comment by sorodrigo** [comment]
I was thinking the same (keeping redux-offline org name). Maybe in the future then? I really prefer it over redux-offline-team.
Ok let’s do the changelog here.

**Comment by wacii** [comment]
I prefer the name as well, but there are some discussions here I would like to keep around. At least for now.

**Comment by sorodrigo** [comment]
Changelog is now live. Closing.
