### ISSUE TITLE
Redux Offline without Redux

### ISSUE THREAD

**Issue by simonkwesi** [redux-offline/redux-offline#48]
Hello,

Is it possible to use redux offline without redux?
I need to keep a rather huge data set inside my offline cache, so redux is not suitable for my application, as cloning the whole store every time a single data set is changed is not performant enough.
I like redux offline's network monitoring and action queue features though. 
Can I use them without redux?
Thanks!

**Comment by jevakallio** [comment]
Nope, this depends entirely on Redux. 

However, the documentation in the readme describes the general architecture behind the library, which may be helpful if you want to implement similar features without Redux.
