### ISSUE TITLE
Disconnect fork?

### ISSUE THREAD

**Issue by kbrandwijk** [redux-offline/redux-offline#49]
Currently, the code cannot be searched because searching code in a forked repo is not possible on Github. Would you consider 'disconnecting' the fork, so this becomes a stand-alone repo?

**Comment by wacii** [comment]
We have ownership of the original repo and will be merging soon. Which should fix your problem.

**Comment by sorodrigo** [comment]
@wacii I was thinking on opening an issue about this. How would you proceed with the merge? I think the best way to do this is to make a new release with the latest changes (including the CHANGELOG suggested in #48 ) and then merging master.

**Comment by wacii** [comment]
That sounds good.

**Comment by kbrandwijk** [comment]
If you need any help, let me know what I can do to contribute.

**Comment by wacii** [comment]
Closing as the merge has been completed.

**Comment by kbrandwijk** [comment]
So now the 'main' repo 'redux-offline-team/redux-offline' also has `@redux-offline/redux-offline` as package name in package.json.

Can you please elaborate what the main repo (for code and issues) and main package name will be from now on?

**Comment by wacii** [comment]
The main repo is redux-offline-team/redux-offline which is deployed as @redux-offline/redux-offline.
