### ISSUE TITLE
Redux Offline depends on React

### ISSUE THREAD

**Issue by unindented** [redux-offline/redux-offline#50]
I don't think this is right: https://github.com/jevakallio/redux-offline/blob/3bf42d37daa68899bf7528b2b48710c9a0fec2b4/lib/defaults/batch.js#L7

A Redux library shouldn't depend on React, certainly not for `PropTypes`, right?

**Comment by unindented** [comment]
Oh wow, found a file full of `PropTypes` and inlined `require('react')`. What's this all about? https://github.com/jevakallio/redux-offline/blob/3bf42d37daa68899bf7528b2b48710c9a0fec2b4/lib/types.js

**Comment by unindented** [comment]
Ah, it's this Babel plugin: `babel-plugin-flow-react-proptypes`

Can we get rid of it? `PropTypes` are going the way of the dodo anyways.

**Comment by jevakallio** [comment]
@unindented yes! Thanks for catching this, was honestly not aware these were being generated.

Will fix this shortly.

**Comment by unindented** [comment]
Boom! Thank you!
