### ISSUE TITLE
How to implement delayed send

### ISSUE THREAD

**Issue by pke** [redux-offline/redux-offline#50]
I wonder if that lib could be extended by delayed send functionality which would basically allow "undo" action like GMail does. In Gmail when you send an email it is shown to the user as sent, but its not actually send to the server for another 5 seconds. If the users decides to "undo" the send the request to the server is never sent.

Maybe this could be coded as an extension (another middleware) to this lib? I just can not really wrap my head around how the "undo" would be able to work. I think the action would have to contain more info in the metadata for the rollback so that the optimistic UI update can also be reverted properly.

**Comment by wacii** [comment]
This is not a problem I want to address in the library. You're on your own I'm afraid.

**Comment by pke** [comment]
Any ideas though maybe?
