### ISSUE TITLE
Why commit lib folder?

### ISSUE THREAD

**Issue by unindented** [redux-offline/redux-offline#51]
Why do you commit the `lib` folder to git? You can have a `prepublish` step that generates it, and includes it in the files you push to npm, like many other libraries do.

Let me know if you need help with this.

**Comment by jevakallio** [comment]
Thanks for pointing this out @unindented. I rushed to get this library out for a specific time and did not set up a proper release process. I will be fixing this, along with setting up proper tests and CI shortly.

**Comment by unindented** [comment]
Awesome!
