### ISSUE TITLE
redux-offline with angular2 and/or angular-redux/store?

### ISSUE THREAD

**Issue by divramod** [redux-offline/redux-offline#53]
hey, i am trying to get redux-offline running with angular2.

is there a recommended way to make a provider out of redux-offline.

i dont know if this is the right place here. do i have to ask this question here: https://github.com/angular-redux/store ?

are there any disadvantages of using redux-offline in its pure form vs angular-redux/store or can i combine them without problem?

if i see it clear, angular-redux uses redux under the hood just like redux-offline and adds some conviniet wrappers around it. so is it the only thing that has to be changed here 
* https://github.com/angular-redux/store/blob/master/src/components/ng-redux.ts#L91 ? and
* here https://github.com/angular-redux/store/blob/master/src/components/ng-redux.ts#L7
so that i follow the quickstart of redux-offline?

```
- const store = createStore(
+ const store = createOfflineStore(
  reducer,
  preloadedState,
  applyMiddleware(middleware),
+ offlineConfig  
);
```

thx in advance for any hints on the subject. i really like to use redux-offline for offline-first projects but like to able to use the convinience off angluar-redux/store with using observables etc.

**Comment by jevakallio** [comment]
In retrospect, the createOfflineStore API makes integration with non-standard Redux stores harder than it needs to be. If angular-redux supports enhancers, once I'm able to land #17, the integration should get easier.

I don't personally use Angular, so I don't have direct experience. However I am more than happy to improve compatibility and document the usage.

Could you confirm whether the enhancer support in #17 would work?
