### ISSUE TITLE
redux-offline-sauce

### ISSUE THREAD

**Issue by tanhauhau** [redux-offline/redux-offline#55]
Hi there,

Cool library! I was working on [redux-offline-sauce](https://github.com/tanhauhau/redux-offline-sauce) to provide utility function similar to what [reduxsauce](https://github.com/skellock/reduxsauce) provided for redux. It would be great if you could give some opinions/comments about my small library.

Thanks.

**Comment by jevakallio** [comment]
@tanhauhau cool! I'm on easter holidays now, but will gradly give feedback next week!
