### ISSUE TITLE
Pending queue gets rewritten on rehydration

### ISSUE THREAD

**Issue by okjulian** [redux-offline/redux-offline#56]
First of all thanks for such a useful library!

I am having a little problem with actions that get fired before the rehydrate action.

Context:
* I have a request that gets fired before `persist/REHYDRATE` action. It gets added to the pending queue
* `persist/REHYDRATE`gets fired and rehydrates app state, wiping out the pending queue

Problem:
* The request stays in oblivion for the rest of eternity 🎇 

Proposed solution:
* I solved this by [blacklisting](https://github.com/rt2zz/redux-persist#persiststorestore-config-callback) `offline` in my persistOptions. But maybe we should blacklist offline in `redux-offline` `persistOptions`.

```
persistOptions: { blacklist: ["offline"] }
```

With that said, I don't know if blacklisting `offline` in redux-persist will have any negative consequences. If that's the case, does anybody have any other solution?

**Comment by SashaSirotkin** [comment]
Redux-persist has a feature called transforms that you can use in this scenario. You can use [filters](https://github.com/edy/redux-persist-transform-filter) to more finely control what is and isn't persisted.

```js
import { createBlacklistFilter } from 'redux-persist-transform-filter';

const persistConfig = {
  transforms: [
    // This will prevent the online property from being stored.
    createBlacklistFilter('offline', ['online']),
   ],
};
```

I am not sure which pieces should be blacklisted inside `online` or if blacklisting the entire reducer is the right way to go. Still fairly new with the library myself.

**Comment by jevakallio** [comment]
@JulianMayorga look into using an [action buffer](https://github.com/rt2zz/redux-persist#action-buffer), as per redux-persist documentation. This should probably be built into redux-offline, though 🤔
