### ISSUE TITLE
Uncaught TypeError: Cannot read property 'outbox' of undefined

### ISSUE THREAD

**Issue by tribou** [redux-offline/redux-offline#57]
I wasn't sure if this should be reported here or in the https://github.com/zalmoxisus/redux-devtools-extension repo.  However, the stacktrace is directed at the `middleware.js` file from this repo...

When I use `compose` from `redux`, there is no error.  But when I use `composeWithDevTools` from `redux-devtools-extension`, I get this error on the client:

```
middleware.js?1387:29 Uncaught TypeError: Cannot read property 'outbox' of undefined
    at take (eval at <anonymous> (vendor-cba7902….js:6401), <anonymous>:29:38)
    at Object.eval [as dispatch] (eval at <anonymous> (vendor-cba7902….js:6401), <anonymous>:68:23)
    at dispatch (<anonymous>:2:31397)
    at eval (eval at <anonymous> (vendor-cba7902….js:5803), <anonymous>:22:18)
    at eval (eval at <anonymous> (vendor-cba7902….js:1892), <anonymous>:41:20)
    at eval (eval at <anonymous> (vendor-cba7902….js:1899), <anonymous>:14:16)
    at Object.eval [as dispatch] (eval at <anonymous> (vendor-cba7902….js:6352), <anonymous>:68:22)
    at Object.dispatch (<anonymous>:2:1507)
    at handleLocationChange (eval at <anonymous> (vendor-cba7902….js:5810), <anonymous>:99:11)
    at syncHistoryWithStore (eval at <anonymous> (vendor-cba7902….js:5810), <anonymous>:108:5)
take	@	middleware.js?1387:29
(anonymous)	@	middleware.js?1387:68
dispatch	@	VM3243:2
(anonymous)	@	middleware.js?26f3:22
(anonymous)	@	index.js?3a63:41
(anonymous)	@	index.js?f248:14
(anonymous)	@	createEpicMiddleware.js?60f1:59
dispatch	@	VM3243:2
handleLocationChange	@	sync.js?dcab:99
syncHistoryWithStore	@	sync.js?dcab:108
(anonymous)	@	browser.index.js?1ce9:28
429	@	bundle-7125933….js:82
__webpack_require__	@	vendor-cba7902….js:55
1265	@	bundle-7125933….js:9
__webpack_require__	@	vendor-cba7902….js:55
webpackJsonpCallback	@	vendor-cba7902….js:26
(anonymous)	@	bundle-7125933….js:1
```

Which points to the following lines:

![screen shot 2017-04-15 at 11 11 34 pm](https://cloud.githubusercontent.com/assets/1641390/25068673/fcf72140-2230-11e7-850e-b679217cea30.png)

Here is my `redux/store.js`:

```javascript
// @flow
import { applyMiddleware, createStore } from 'redux'
import { createEpicMiddleware } from 'redux-observable'
import thunk from 'redux-thunk'
import promiseMiddleware from 'redux-promise-middleware'
import { routerMiddleware } from 'react-router-redux'
import { offline } from 'redux-offline'
import offlineConfig from 'redux-offline/lib/defaults'
import { composeWithDevTools } from 'redux-devtools-extension/logOnlyInProduction'
import rootEpic from './epics'
import rootReducer from './modules'


function configureStore (
  preloadedState: Object, history: Object,
): Object {

  const epicMiddleware = createEpicMiddleware(rootEpic)

  const middleware = [
    epicMiddleware,
    thunk,
    promiseMiddleware(),
    routerMiddleware(history),
  ]

  // https://github.com/zalmoxisus/redux-devtools-extension
  // https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f
  const enhancer = composeWithDevTools(
    applyMiddleware(...middleware),
    offline(offlineConfig)
  )

  const store = createStore(rootReducer, preloadedState, enhancer)

  return store

}


export default configureStore
```

I'm not sure how to proceed, but let me know if I can provide anything else!

**Comment by jevakallio** [comment]
Thanks for reporting this! I don't think I tested the 2.0.0 release (with the Store Enhancer API) with composeWithDevtools, so will need to dig into this.

> I'm not sure how to proceed, but let me know if I can provide anything else!

I am on holiday until Tuesday. If you are able to find the root cause and submit notes or a PR, that would be great. Otherwise earliest this will get attention is Tuesday evening or Wednesday.

In the meantime you can use [v1.1.0](https://github.com/jevakallio/redux-offline/releases/tag/v1.1.0) which does not depend on compose.

**Comment by tdd** [comment]
Hey all,

FWIW, even when manually composing `window.__REDUX_DEVTOOLS_EXTENSION__` (as provided by the Chrome browser ext), it fails unless the offline enhancer appears **last** in the `compose` arguments.

This should definitely either be addressed, or clearly required by the docs. Personally, I feel I should be able to compose this enhancer anywhere after the middlewares…

Cheers,

**Comment by fossage** [comment]
@tribou ,

I believe this is a problem with redux-devtools-extension.  I have ran into a similar issue before and I solved it by not using the composeWithDevTools helper and instead using something like the following:

```javascript
const enhancer = compose(
  applyMiddleware(...middleware),
  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
  offline(offlineConfig),
)
```

It seems the issue when using the composeWithDevTools helper, the offlineMiddleware is receiving a wrapped version of the state when calling store.getGetState() which has the actual state we are interested in(i.e. the one that contains offline.outbox) within a property called 'computedStates'.  

I ran into the same issue before when hooking up redux-saga, so I just opted for the solution above and it has been working fine ever since:)

[Edit] It also seems it's worth noting that it appears to be an order of operations problem.  If you put the `window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()` statement as the last argument, you run into the same problem, but it seems to work fine as long as as `offline(offlineConfig)` is the last argument.

**Comment by fossage** [comment]
@tribou , upon further investigation, this is a known issue with redux-devtools-extension.  It doesn't look like it's actually a bug, just a result of how it works.  From the troubleshooting section of the docs:

### It doesn't work with other store enhancers 

Usually the extension's store enhancer should be last in the compose. When you're using [`window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`](/README.md#12-advanced-store-setup) or [`composeWithDevTools`](/README.md#13-use-redux-devtools-extension-package-from-npm) helper you don't have to worry about the enhancers order. However some enhancers ([like `redux-batched-subscribe`](https://github.com/zalmoxisus/redux-devtools-extension/issues/261)) also have this requirement to be the last in the compose. In this case you can use it like so:

```js
const store = createStore(reducer, preloadedState, compose(
  // applyMiddleware(thunk),
  window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : noop => noop,
  batchedSubscribe(/* ... */)
));
```

**Comment by tribou** [comment]
Thanks @fossage! Updating my store to just use `devToolsEnhancer` along with redux's `compose` fixed the issue:

```javascript
// @flow
import { applyMiddleware, createStore, compose } from 'redux'
import { createEpicMiddleware } from 'redux-observable'
import thunk from 'redux-thunk'
import promiseMiddleware from 'redux-promise-middleware'
import { routerMiddleware } from 'react-router-redux'
import { offline } from 'redux-offline'
import offlineConfig from 'redux-offline/lib/defaults'
import { devToolsEnhancer } from 'redux-devtools-extension/logOnlyInProduction'
import rootEpic from './epics'
import rootReducer from './modules'


function configureStore (
  preloadedState: Object, history: Object,
): Object {

  const epicMiddleware = createEpicMiddleware(rootEpic)

  const middleware = [
    epicMiddleware,
    thunk,
    promiseMiddleware(),
    routerMiddleware(history),
  ]

  // https://github.com/zalmoxisus/redux-devtools-extension
  // https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f

  const enhancer = compose(  // <-- CHANGED
    applyMiddleware(...middleware),
    devToolsEnhancer(),  // <-- CHANGED
    offline(offlineConfig)
  )

  const store = createStore(rootReducer, preloadedState, enhancer)

  return store

}


export default configureStore
```

**Comment by byzg** [comment]
@tribou example have not worked for me until I replaced 
```javascript
export const store = createStore(
  reducers,
  undefined,
  compose(
    applyMiddleware(...middlewares),
    devToolsEnhancer(),
    offline(customConfig)
  ),
)
```
 to 
```javascript
export const store = createStore(
  reducers,
  undefined,
  window['__REDUX_DEVTOOLS_EXTENSION_COMPOSE__']({
    shouldHotReload: false,
  })(
    applyMiddleware(...middlewares)
  ),
  offline(customConfig)
)
```

maybe it will help for someone

**Comment by LightningK0ala** [comment]
This temporary solution fixed this issue for me:

https://github.com/zalmoxisus/redux-devtools-extension/issues/365

**Comment by wacii** [comment]
The issue integrating with Redux DevTools has been resolved. If you are still seeing this error, please feel free to open a new issue.
