### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by wacii** [redux-offline/redux-offline#60]
I wanted a way for users to provide code reproducing errors in bug reports without creating a new repo, and found some success with https://codesandbox.io.

An example demonstrating the old DevTools issue: [link](https://codesandbox.io/s/2433l5xlj0).
A basic starting point: [link](https://codesandbox.io/s/8xml9l1r0j).

We could provide links to these as well as the example app when a user fails to adequately describe the bug they are reporting.

This should be mentioned in the contributing section, but as we have not discussed this before, I thought I would ask if there's anything else we wanted to add. It might end up saving us a good deal of time in the long run.

**Comment by sorodrigo** [comment]
I agree, this is super useful! I also wanted to talk about the guidelines. I think that we should enforce more the _"create an issue before making a PR that involves big changes or new features"_ . Mainly to not waste people's time and effort.

**Comment by wacii** [comment]
I assume we'll still be doing gitflow on the main repo? Might be something to add to the contributions section. Also I'll need to move my PRs on the main repo over to develop.

**Comment by sorodrigo** [comment]
Yes that’s something I haven’t thought of, thanks!

**Comment by sorodrigo** [comment]
I'll PR you on the official repo to update this things in the README. Closing
