### ISSUE TITLE
Unexpected key "offline" found in previous state received by the reducer. Expected to find one of the known reducer keys instead...

### ISSUE THREAD

**Issue by tribou** [redux-offline/redux-offline#60]
Since #19 and #27 were fixed, I figured this might be a new issue...

![image](https://cloud.githubusercontent.com/assets/1641390/25141314/cc50990a-2428-11e7-9d2d-d8b36bb16afb.png)

I'm using server-side rendering to save the redux initial state and rehydrate on the client which appears to be working:

![image](https://cloud.githubusercontent.com/assets/1641390/25141386/08b23bce-2429-11e7-91eb-b83fab00cb40.png)

And my `@@INIT` state in redux devtools appears to contain the offline key:

![image](https://cloud.githubusercontent.com/assets/1641390/25141448/2ef9dd3c-2429-11e7-95e0-1393c518010a.png)

But then the next action removes the offline key:

![image](https://cloud.githubusercontent.com/assets/1641390/25141521/65a82140-2429-11e7-8572-7f8f5ec6f4c0.png)

`redux-offline@2.0.0`
`redux@3.6.0`

**Comment by jevakallio** [comment]
@tribou can you please show how you configure the Redux store, along with and redux-offline configurations.

**Comment by tribou** [comment]
Ah, my apologies! It's actually the same config that fixed #57:

```javascript
// @flow
import { applyMiddleware, createStore, compose } from 'redux'
import { createEpicMiddleware } from 'redux-observable'
import thunk from 'redux-thunk'
import promiseMiddleware from 'redux-promise-middleware'
import { routerMiddleware } from 'react-router-redux'
import { offline } from 'redux-offline'
import offlineConfig from 'redux-offline/lib/defaults'
import { devToolsEnhancer } from 'redux-devtools-extension/logOnlyInProduction'
import rootEpic from './epics'
import rootReducer from './modules'


function configureStore (
  preloadedState: Object, history: Object,
): Object {

  const epicMiddleware = createEpicMiddleware(rootEpic)

  const middleware = [
    epicMiddleware,
    thunk,
    promiseMiddleware(),
    routerMiddleware(history),
  ]

  // https://github.com/zalmoxisus/redux-devtools-extension
  // https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f

  const enhancer = compose(  // <-- CHANGED
    applyMiddleware(...middleware),
    devToolsEnhancer(),  // <-- CHANGED
    offline(offlineConfig)
  )

  const store = createStore(rootReducer, preloadedState, enhancer)

  return store

}


export default configureStore
```

Also, this is my `combineReducers()`:

```javascript
// @flow
import { combineReducers } from 'redux'
import { routerReducer as routing } from 'react-router-redux'
import { reducer as form } from 'redux-form'

import env from './env'
import request from './request'
import init from './init'
import auth from './auth'

// Examples
import profile from './profile'
import todos from './todos'


const rootReducer = combineReducers({
  env,
  request,
  init,
  auth,

  // Examples
  profile,
  todos,

  // redux-form
  form,
  // react-router-redux
  routing,
})


export default rootReducer
```

**Comment by lifeiscontent** [comment]
@jevakallio any updates on this?

**Comment by guilhermebruzzi** [comment]
@jevakallio @tribou Have you guys managed to do a workaround? My configuration looks like the one @tribou posted and I'm getting: Cannot read property 'outbox' of undefined

**Comment by wacii** [comment]
The issue integrating with Redux DevTools has been resolved. If you are still seeing this error, please feel free to open a new issue.
