### ISSUE TITLE
Commit / rollback never called

### ISSUE THREAD

**Issue by ananth98765** [redux-offline/redux-offline#61]
I am working on React native app , I am trying to use redux-offline lib in my project.

When I tried to add user from offline but  none of actions INSERT_NEW_USER_OFFLINE / INSERT_NEW_USER_FAILURE called, i.e commit or rollback is not calling.It always its call INSERT_NEW_USER

insertNewUserData: (userData) => {
     const effectReconciler = () => {
            return (api.setUsers({
                     user_id: userData.id,
                     user_first_name: userData.firstName,
                     user_last_name: userData.lastName,
                     updated_at: Math.floor(Date.now() / 1000)
            }));
   };
   const commit = () => {
       return { type: 'INSERT_NEW_USER_OFFLINE', payload: userData, meta: { userData } };
   };
   const rollback = () => {
        return { type: 'INSERT_NEW_USER_FAILURE', payload: userData, meta: { userData } };
   };

return {
  type: 'INSERT_NEW_USER',
  payload: userData,
  meta: {
       offline: {
           effect: effectReconciler(),
           commit,
           rollback
       }
  }
};

Let me know if anything need to change in above code..

**Comment by jevakallio** [comment]
Instead of action creators, the `commit` and `rollback` need to be actions:
```diff
- const commit = () => {
+ const commit = {
  return { type: 'INSERT_NEW_USER_OFFLINE', payload: userData, meta: { userData } };
};
- const rollback = () => {
+ const rollback = {
  return { type: 'INSERT_NEW_USER_FAILURE', payload: userData, meta: { userData } };
};
```

**Comment by ananth98765** [comment]
After making above changes still these two actions are not calling . I am using redux-offline 2.0 version.. 
When I add user I was in offline and then changed offline mode to online mode  with the expectation  commit or rollback action will be called.But nothing is happening.. I am using  redux-offline with ignite project. 
```js
import { createStore, applyMiddleware, compose } from 'redux';
import { autoRehydrate } from 'redux-persist';
import Config from '../Config/DebugConfig'
import createSagaMiddleware from 'redux-saga';
import RehydrationServices from '../Services/RehydrationServices'
import ReduxPersist from '../Config/ReduxPersist'

import { offline } from 'redux-offline'
import offlineConfig from 'redux-offline/lib/defaults'

// creates the store
export default (rootReducer, rootSaga) => {
  /* ------------- Redux Configuration ------------- */

  const middleware = [];
  const enhancers = [];

  /* ------------- Saga Middleware ------------- */

  const sagaMonitor = __DEV__ ? console.tron.createSagaMonitor() : null;
  const sagaMiddleware = createSagaMiddleware({ sagaMonitor });
  middleware.push(sagaMiddleware);

  /* ------------- Assemble Middleware ------------- */

  enhancers.push(applyMiddleware(...middleware));

  /* ------------- AutoRehydrate Enhancer ------------- */

  // add the autoRehydrate enhancer
  if (ReduxPersist.active) {
    enhancers.push(autoRehydrate());
  }

  // if Reactotron is enabled (default for __DEV__), we'll create the store through Reactotron
  const createAppropriateStore = Config.useReactotron ? console.tron.createStore : createStore;
//  const store = createAppropriateStore(rootReducer, compose(...enhancers))
  const store = createAppropriateStore(rootReducer, {}, compose(...enhancers), offline({ ...offlineConfig}));
  // configure persistStore and check reducer version number
  if (ReduxPersist.active) {
    RehydrationServices.updateReducers(store);
  }

  // kick off root saga
  sagaMiddleware.run(rootSaga);

  return store;
};
```

**Comment by jevakallio** [comment]
I believe this line is incorrect:
```
const store = createAppropriateStore(rootReducer, {}, compose(...enhancers), offline({ ...offlineConfig}));
```

In Redux Offline 2.x, you should specify the offline enhancer as one of the enhancers inside `compose`, rather than pass it as the 4th argument to createStore as in 1.x.

See release notes and migration guide from 1.x->2.x: https://github.com/jevakallio/redux-offline/releases/tag/v2.0.0

**Comment by ananth98765** [comment]
Thanks. I made appropriate changes to the code  as below,

`  const store = createAppropriateStore(rootReducer, {}, compose(...enhancers, offline(offlineConfig)));
`
Still it calling INSERT_NEW_USER action , not OfflineActions(commit and rollback) even though I am in offline

**Comment by enahum** [comment]
hitting the same issue, and I track it down to `effect` not being called

**Comment by vysakh0** [comment]
@enahum For me too :( , the `effect` does not get triggered but the `redux-persist` works (the offline data)

**Comment by DylanGriffith** [comment]
Just to weigh in on this I think that there may be some confusion about how the `meta.offline` key works. To summarise it seems a few of the commentors are thinking they need to pass functions as the values for `effect`, `commit` and `rollback`, but these are actually all just objects. So to give an example from the docs your actions should look like:

```javascript
{
  type: 'FOLLOW_USER_REQUEST',
  payload: { userId },
  meta: {
    offline: {
      // the network action to execute:
      effect: { url: '/api/follow', method: 'POST', body: { userId } },
      // action to dispatch when effect succeeds:
      commit: { type: 'FOLLOW_USER_COMMIT', meta: { userId } },
      // action to dispatch if network action fails permanently:
      rollback: { type: 'FOLLOW_USER_ROLLBACK', meta: { userId } }
    }
  }
}
```

The effect reconciler (if you want to configure one) needs to be configured when setting up the store.

**Comment by davidsonsns** [comment]
Inserting the sample code, as @DylanGriffith showed, the problem continues

**Comment by chrise86** [comment]
@davidsonsns did you get anywhere with this? Facing the same issue :-/

**Comment by radjivF** [comment]
Can we reopen this issue I have exactly the same, is anyone found a solution?

**Comment by sorodrigo** [comment]
Please open a new issue following our bug report template. Also add an example of how you declare an offline action

**Comment by caleb-harrelson** [comment]
My issue was a PEBKAC problem, but just in case anybody else is stuck, make sure your `commit` and `rollback` properties are on the `offline` object, not that object's `effect` object.
