### ISSUE TITLE
Add `getState` to effect reconciler

### ISSUE THREAD

**Issue by kaelumania** [redux-offline/redux-offline#61]
I would like to retrieve an API access token, that is stored inside redux state, before making any API calls. Thus, I would need to access the state when I issue a remote `fetch` aka effect.

BTW is it a good idea to store credentials (access token) within the persisted redux state?

**Comment by sorodrigo** [comment]
I'd say that the best way to include state data in your offline actions is to use `redux-thunk`. For example: 
```export function getUser() {
  return async (dispatch, getState) => {
      const user = getState().user;
      const url = `${Config.API_URL}/user?access_token=${user.token}`;
      dispatch({
        type: GET_USER_REQUEST,
        meta: {
          offline: {
            effect: { url },
            commit: { type: GET_USER_COMMIT },
            rollback: { type: GET_USER_ROLLBACK }
          }
        }
      });
  };
}```

That said, retrieving the access token for every request is a pain, so in a real life application I created a redux middleware that adds the auth token as a meta in every offline action. And then use a custom effect that adds it as a header in every request. My custom effect just wraps the default implementation.

**Comment by kaelumania** [comment]
@sorodrigo thanks for the answer. I always think about thunk as calling an api. But you are right it's just about using functions as action payload. Thus, one option is to use thunk and another is to use a custom middleware injecting the token to meta data, right? 

Further, is it in general a good practice to store credentials within redux state?

**Comment by sorodrigo** [comment]
I think there’s no problem. You can store a JWT in your store and use it to maintain the user logged in until it expires. You shoukd never store passwords tho.
