### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by piranna** [redux-offline/redux-offline#63]
After upgrade to newer 2.2.0 version we are getting a `Uncaught ReferenceError: regeneratorRuntime is not defined` error after data is fetch from out server, while with 2.1.0 it correctly works. Seems like it's not able to correctly upgrade the UI. This happens both with React 15 and 16.

**Comment by wacii** [comment]
The regenerator runtime is responsible for transforming generators and async functions for environments that do not support them. Depending on your targets you might need to include the runtime to use Redux Offline. The specific change that introduced this dependency was actually yours making `config.discard()` asynchronous.

**Comment by piranna** [comment]
> The specific change that introduced this dependency was actually yours making config.discard() asynchronous.

Lol! X-D So maybe is it an issue of configuring Babel? Could you be able to give me some info towards that? I'm mostly a backend developer, so this kind of things are new to me...

**Comment by manueliglesias** [comment]
@piranna You can also try:

`import 'regenerator-runtime/runtime';`

(It might need to be your very first import)

**Comment by wacii** [comment]
If this is not resolved, feel free to reopen on the main repo.

**Comment by piranna** [comment]
> import 'regenerator-runtime/runtime';

It worked, thanks! :-D Maybe it would make sense to add a note on the readme regarding this?

**Comment by wacii** [comment]
Reopening as this is something we should be dealing with in the library.

Just discovered that Babel makes a tool similar to `babel-polyfill` but is more suitable for libraries, that we should be using.

**Comment by piranna** [comment]
Good to know :-)

**Comment by aislanmaia** [comment]
I'm just using `create-react-app` that by default it not make use of babel and I'm getting the same error regarding regeneratorRuntime. :crying_cat_face:

**Comment by sorodrigo** [comment]
We’re including this patch soon. ;)

**Comment by sorodrigo** [comment]
Merged in the official repo.
