### ISSUE TITLE
Can commit take the response from effect

### ISSUE THREAD

**Issue by pepicrft** [redux-offline/redux-offline#63]
I read on the readme that it's possible to pass data from the effect execution to the commit

> Or sometimes, in order to render the final UI state, you need some data from the server response.

I wonder how that's possible. Is the `Promise` data somehow injected in the commit action?

**Comment by jevakallio** [comment]
@pepibumur it should automatically be set as commit action's payload, see: https://github.com/jevakallio/redux-offline/blob/master/src/middleware.js#L29

**Comment by pepicrft** [comment]
Thank you very much @jevakallio. That answers my question.
