### ISSUE TITLE
Retry action?

### ISSUE THREAD

**Issue by Noitidart** [redux-offline/redux-offline#64]
Is there a way to get a action dispatched when it is retrying? I want to update my GUI to saying it is going to retry in X sec.

I see this logged to console:

> 'Retrying action', 'FETCH_ENTITY', 'with delay', 1000

Is there a way to make it dispatch an action at the same time? Like `*_ROLLBACK` and `*_COMMIT`?

-------

This is an aside, an example of an end goal is:

1. User takes a screenshot
2. Clicks upload to Dropbox
3. It starts the first upload attempt
4. Now different things can happen
    * If this attempt finds it is offline, I want to show "You are currently offline, will upload when get online"
    * If it is succeeding, I want to show % uploaded
    * If it failed and will retry in X seconds I want to show countdown "Failed will retry in Xs"
    * If it is in "retrying" stages or "waiting for offline" I want to offer a button saying "Cancel upload and instead save to disk"

**Comment by benvp** [comment]
You could try implement you own discard handler and dispatch an an action here. https://github.com/jevakallio/redux-offline#change-how-irreconcilable-errors-are-detected

Or you could use something like redux-obversables or redux-saga to listen for the `Offline/SCHEDULE_RETRY` or `Offline/COMPLETE_RETRY` action and dispatch another action to notify the user,

**Comment by Noitidart** [comment]
Ah interesting on the listening to `Offline/*` - I like to avoid dropping libs, especially redux-saga. Doing store.subscribe should be able to listen for this as well huh? I will try that out. Thanks @benlime!

**Comment by benvp** [comment]
@Noitidart Maybe it's better to use a middleware for this, as you don't know the action in the subscribe listener. (see https://github.com/reactjs/redux/issues/1057). If you want to avoid other frameworks, write a middleware which listens for the `Offline/*` actions and dispatch your actions accordingly.

**Comment by Noitidart** [comment]
Oo thanks benlime! Thats very interesting.
