### ISSUE TITLE
network detector is weird / misdocumented

### ISSUE THREAD

**Issue by lsenta** [redux-offline/redux-offline#64]
Thanks for maintaining this project!

The doc says:
> The function is passed a callback, which you should call with boolean true when the app gets back online, and false when it goes offline.
https://github.com/redux-offline/redux-offline#change-how-network-status-is-detected

The code expects an object `{ online: true / false }`
https://github.com/redux-offline/redux-offline/blob/develop/src/defaults/detectNetwork.js#L8

- No error is raised if you pass a boolean, an action `Offline/STATUS_CHANGED` is trigger with an empty payload object.
- I'd expect the code to use a boolean value as documented

I can provide a fix, I guess that'd be a breaking change, let me know if that's fine.

**Comment by sorodrigo** [comment]
Thanks for pointing this out. I’ll have a look at it later today, but quickly eyeballing it I think that the docs are not updated which would be my bad.

**Comment by lsenta** [comment]
Yup, it's either the doc or the code.
What's the rationale behind asking for an `{online: bool}` payload?

**Comment by sorodrigo** [comment]
This is the change that broke this: https://github.com/redux-offline/redux-offline/pull/1/files#diff-7701bf42c0bcc36a1600dd1f7ec16030 as I see it the best solution is to make the action support both an object payload and a boolean one. This should’ve been the original change.

**Comment by sorodrigo** [comment]
Hey @lsenta I merged this on the official repo 👍 . Closing
