### ISSUE TITLE
How to drop "older" actions?

### ISSUE THREAD

**Issue by baba43** [redux-offline/redux-offline#65]
Hi, 

first of all: thank you for this library!

When reading through the docs I was wondering what happens in this scenario:

1. User likes a post
2. User dislikes a post

When this scenario happens while offline, obviously nothing should be send to the server.

How could one implement this in a smart way (if possible for now)?

**Comment by ManAnRuck** [comment]
in this example I manipulate the next actions. perhaps you can try to delete some actions.

https://github.com/ReggaePanda/redux-offline-examples/blob/master/simple-web/src/index.js#L34
https://github.com/ReggaePanda/redux-offline-examples/blob/master/simple-web/src/reducers/offline.js#L4

**Comment by sorodrigo** [comment]
Hey! There’s a new feature incoming that lets you build a custom enqueue and dequeue. So with this, removing repeated actions on enqueue is quite straightforward.

**Comment by prsn** [comment]
Hi @sorodrigo 
Thanks for the awesome library.
Any update on this, in which version this feature will be released?

**Comment by sorodrigo** [comment]
This feature is now available. Its called queue in the offline config.
Actually I’m interested on adding a “smart queue” plugin under the same github/npm org. Here’s a very thorough description on what it should do and how to do it.
https://github.com/redux-offline/redux-offline/issues/90#issuecomment-368298172

If you want to contribute you could develop it yourself and I could guide you through it.

**Comment by prsn** [comment]
Hi @sorodrigo ,
Yes, I am ready to contribute. Please guide me what I need to do.
Thanks for the opportunity.

**Comment by sorodrigo** [comment]
Hey @prsn I’m glad you want to get involved. I made a separate repo with a description of what the smart-queue would need to do. If you have any doubts or questions just ping me in the issues of the queue repo.

You can find it here:
https://github.com/redux-offline/queue/blob/master/smart-queue/README.md

**Comment by prsn** [comment]
Thanks @sorodrigo , surely I will ping you in case I face any doubts.
