### ISSUE TITLE
Effect does not get triggered

### ISSUE THREAD

**Issue by vysakh0** [redux-offline/redux-offline#66]
I'm trying to fix this problem for few days, still couldn't find a fix, so I'm wondering if it's an issue with the library. 

```js
// package.json
    "firebase": "^3.7.6",
    "firebase-functions": "^0.5.5",
    "material-ui": "~0.16.4",
    "react": "~15.4.0",
    "react-dom": "~15.4.0",
    "react-redux": "^5.0.1",
    "react-tap-event-plugin": "~2.0.0",
    "redux-offline": "^2.0.0",
    "redux-saga": "~0.14.2"
```

```js
// customConfig.js
import defaultConfig from 'redux-offline/lib/defaults';
import firebase from './firebase';

const db = firebase.database();

const firebaseAction = (type, { body, resource }) => {
  const { key, ...final } = body;
    switch (type) {
      case 'CREATE_FIREBASE':
        return db.ref(`${resource}/${key}`).set(final);
      case 'UPDATE_FIREBASE':
        return db.ref(`${resource}/${key}`).update(final);
      default:
        return null;
    }
}

export default {
  ...defaultConfig,
  effect: (effect, action) => {
    console.log('executing effect...')
    return firebaseAction(action.type, effect);
  }
}
```
```js
import { offline } from 'redux-offline';
import offlineConfig from './customConfig';

// ...
    const sagaMiddleware = createSagaMiddleware();

    const store = createStore(reducer, undefined, compose(
        applyMiddleware(sagaMiddleware, routerMiddleware(hashHistory)),
        window.devToolsExtension ? window.devToolsExtension() : f => f,
      offline(offlineConfig)
    ));
    sagaMiddleware.run(saga);

```
![screenshot from 2017-04-27 16 49 54](https://cloud.githubusercontent.com/assets/1475197/25481187/ae84c5ac-2b69-11e7-82a0-7baea6fa1640.png)

I also tried with default config but no luck, not even errors (it should throw errors as i don't pass `method`, `URL` params. 

```js
import offlineConfig from 'redux-offline/lib/defaults';
```

So far i thought i missed somewhere or configured wrongly, but seems like I followed just like in the docs. The persist works, even after refresh (after the network is disconnected), the data loads, seems the `meta.offline` thing is not being detected by the middleware?

Someone please help, if there is an example working project i could refer, it'd be helpful

**Comment by 2WheelCoder** [comment]
I'm also having this issue. I believe its related to #57. Whenever I load dev tools before offline as @vysakh0 has done the effect never executes. I've tried loading with `window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : noop => noop` and `devToolsEnhancer()` and I get the same results. If I move it till after I call `offline(offlineConfig)`, then I get the outbox error mentioned in #57. There doesn't seem to be a way to get this configured with redux devtools. Here's what my setup looks like:

```
const offlineConfig = {
  ...defaultOfflineConfig,
  effect: (effect) => {
    console.log('effect GET') // never gets called unless I disable redux devtools
    return surge.get(effect.url)
  }
}

const enhancer = compose(
  applyMiddleware(...middleware),
  createResponsiveStoreEnhancer({
    performanceMode: process.env.NODE_ENV === 'production'
  }),
  devToolsEnhancer(),
  offline(offlineConfig)
)

const store = createStore(
  reducer,
  initialState,
  enhancer
)
```

**Comment by vysakh0** [comment]
@2WheelCoder Thank you, I didn't realize that would be a cause :+1:
