### ISSUE TITLE
offline(offlineConfig) inside compose cause: `Element type is invalid`

### ISSUE THREAD

**Issue by jose920405** [redux-offline/redux-offline#71]
## **This happens when the application is installed and run a second time.**

**My imports:**
```
import { applyMiddleware, createStore, compose } from 'redux';
import { offline } from 'redux-offline';
import offlineConfig from 'redux-offline/lib/defaults';
```

```
const store = createStore(
    rootReducer,
    compose(
      applyMiddleware(thunk),
      offline(offlineConfig) //Error here.. When i comment this line, the error not occur
    )
  );
```

INSIDE `redux-offline/lib/defaults/index.js`

```
exports.default = {
  rehydrate: true,
  persist: _persist2.default, //This line exactly cause the problem
  detectNetwork: _detectNetwork2.default,
  batch: _batch2.default,
  effect: _effect2.default,
  retry: _retry2.default,
  discard: _discard2.default
};
```
**Complete Error:**

`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `NavigationCard``

![screen shot 2017-05-04 at 12 13 39 pm](https://cloud.githubusercontent.com/assets/12536184/25716014/2e88a120-30c3-11e7-9da0-31e6b87c8c22.png)

**Package.json info:**

```
"react": "~15.3.2",
"react-native": "^0.33.0",
```

![screen shot 2017-05-04 at 12 15 27 pm](https://cloud.githubusercontent.com/assets/12536184/25716070/6caf6506-30c3-11e7-917f-490895ace726.png)

**react-native -v:**

> react-native-cli: 1.2.0
> react-native: 0.33.1

# _**UPDATE**_
I'm using `NavigationExperimental` in a react version `15.3.2` when still available, But apparently some of the `redux-persist` tries to read the code where I am using this and causes the error..

**Comment by DylanGriffith** [comment]
I'm assuming your navigation is tracked as a redux store and getting persisted and rehydrated and that's causing your problem. Not all stores are going to play nicely with `redux-persist` by default. An easy way to avoid problems if you don't want to persist specific stores is by configuring a `blacklist` or `whitelist` for what you want to persist. In this case you may wish you blacklist the `nav` store (or whatever it is called in your case). You can add the `persistOptions` key to configure `redux-persist` via `redux-offline`. Described [here](https://github.com/rt2zz/redux-persist#persiststorestore-config-callback) . Then the `blacklist` or `whitelist` options you want are described [here](https://github.com/rt2zz/redux-persist#persiststorestore-config-callback).

Finally you can do something like:

```javascript
const config = {
    ...defaultConfig,
    persistOptions: {
        blacklist: ['nav'],
    }
};
const store = createStore(
  reducer,
  preloadedState,
  middleware
  compose(middleware, offline(config))
);
```
