### ISSUE TITLE
Commit and Rollback should be optional

### ISSUE THREAD

**Issue by McPo** [redux-offline/redux-offline#72]
There is a use-case in which I wish to POST something to the server, but am not concerned about acting on its success or failure (I do however want it to be added to outbox). In such an instance it should be possible to leave the commit and rollback fields undefined.

At the moment if commit is left undefined, the action continually attempts to resolve the 'effect'.

> Retrying action ACTION with delay 1000
> Retrying action ACTION with delay 5000
> ...

Basically the following should all be possible

```
const action = () => ({
    type: '...',
    payload: { ... },
    meta: {
        offline: true
    }
});
```

```
const action = () => ({
    type: '...',
    payload: { ... },
    meta: {
        offline: {
            effect: { ... }
        }
    }
});
```

```
const action = () => ({
    type: '...',
    payload: { ... },
    meta: {
        offline: {
            commit: { ... }
        }
    }
});
```

```
const action = () => ({
    type: '...',
    payload: { ... },
    meta: {
        offline: {
            rollback: { ... }
        }
    }
});
```

**Comment by sorodrigo** [comment]
This feature has been added in the latest release. 👍
