### ISSUE TITLE
How know if the app is offline or online

### ISSUE THREAD

**Issue by jose920405** [redux-offline/redux-offline#76]
Basing on
> `The current reported online state is stored in your store state as boolean state.offline.online`

I'm trying to read from my store this property without success:

`console.log('this.props.myStore offline ===> ', this.props.myStore.offline);` ==> That return **undefined**.

`console.log('this.props.myStore offline ===> ', this.props.myStore.offline.online);` ==> online from offline object cause crash

Is there something I'm doing wrong? I'm missing?

**Comment by DylanGriffith** [comment]
Hi @jose920405 . Are you using redux with ReactJS or something else? Are you able to read other props from your store? The correct way to read the redux store depends on how you're using it in general but [the redux](http://redux.js.org/) docs can give you the best explanation of what's appropriate access to the state in your case, however if you just want the simple example you can look at the first example in the docs and it says reading state from the store looks like:

```
store.getState().offline
```

However most likely in your react components you will want to use the store slightly differently. I suggest reading [the redux docs on usage with react](http://redux.js.org/docs/basics/UsageWithReact.html)

**Comment by jose920405** [comment]
hi @DylanGriffith i'm using react-native with redux.

The way that i use to access to my stores is `this.props.myStore.myKey`, exactly as I have it in question.

**Comment by DylanGriffith** [comment]
Ok. I think if you want help with this you'll need to provide more information about your code. Can you give your store configuration? How is your store being passed to yours components? Via Provider component to all connected components or some other way? Have you followed the redux guide for running with React? 

What I can tell you from having set this up with react native is that there is indeed an `offline` state/reducer and if you pass this through to your connected components you should have access to something like `state.offline.online` which is boolean you can look at to determine if redux offline thinks you're online.

**Comment by jose920405** [comment]
hi @DylanGriffith , Thanks for your time.

Code:

//My Provider
```
import setupStore from './utils/setupStore'

const store = setupStore();

// App component.
import App from './App';

export default class Root extends Component {
  render() {
    return (
      <Provider store={store}>
        <App />
      </Provider>
    )
  }
}

```

The **setupStore** class

```
// Node Core Third party
import { applyMiddleware, createStore, compose } from 'redux';
import { offline } from 'redux-offline';
import offlineConfig from 'redux-offline/lib/defaults';

import logger from 'redux-logger';
import thunk from 'redux-thunk';
// App Modules
import reducer from '../store';
// Assets

const config = {
  ...offlineConfig,
  persistOptions: {
    blacklist: ['noWantedStores'],
  }
};

export default function configureStore() {
  const store = createStore(
    reducer,
    compose(
      applyMiddleware(thunk),
      offline(config)
    )
  );

  //Hot Reloading  
  if (module.hot) {
    module.hot.accept(() => {
      const nextRootReducer = require('../store/index').default;
      store.replaceReducer(nextRootReducer);
    })
  }
  return store;
}

```

My Store `index.js` class

```
import { combineReducers } from 'redux';
import appStore from './stores/appStore';

export default combineReducers({
    router,
    appStore,
    itemStore,
    userStore,
    viewStore,
    modalStore,
});
```

My reducer structure:

```


const SET_CURRENT_VIEW = 'app/SET_CURRENT_VIEW';
const SET_EXTERNAL_TAB_PRESSED = 'app/SET_EXTERNAL_TAB_PRESSED';

// Initial state.
const initialState = {
    currentView: 'newUserHome',
    externalTabPressed: null,
    externalTabFrom: null
};

// Reducer.
export default function reducer(state = initialState, action) {
    switch (action.type) {
        case SET_CURRENT_VIEW:
            return {
                ...state,
                currentView: value
            }
        case SET_EXTERNAL_TAB_PRESSED:
            return {
                ...state,
                externalTabPressed: action.value,
                externalTabFrom: action.from !== undefined ? action.from : null
            };
        default:
            return state
    }
}

export const set_current_view = (value) => ({ type: SET_CURRENT_VIEW, value });
export const set_external_tab_pressed = (value, from) => ({ type: SET_EXTERNAL_TAB_PRESSED, value, from });

```

My escena example:

```
// Third party.
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';

// Actions.
import { set_external_tab_pressed } from '../../store/stores/appStore';

import MyClass from '../components/MyClass';

const mapStateToProps = ({ appStore }) => {
    return {
        appStore
    }
}

const mapDispatchToProps = (dispatch) => bindActionCreators({
    set_external_tab_pressed,
}, dispatch);

export default connect(mapStateToProps, mapDispatchToProps)(MyClass);

```

And in `MyClass` component i'm access to store using:

`this.props.appStore.externalTabPressed`


I still do not find a way to get the value of offline

Thanks.

**Comment by DylanGriffith** [comment]
You need to pass in the `offline` substate to your component:

```javascript
const mapStateToProps = ({ appStore, offline }) => {
    return {
        appStore,
        offline
    }
}
```

Then you will be able to access it in your component like `this.props.offline.online`

**Comment by Noitidart** [comment]
In my reducer I was doing:


```
import { OFFLINE_STATUS_CHANGED } from 'redux-offline/constants'

...
    case OFFLINE_STATUS_CHANGED: {
        const {payload:{ online }} = action;
        // i want to dispatch actions here
    }
...
```

Is there a better way to dispatch some actions when it goes online for example?

The other way I thought of was creating a `return null` component that was connected to the store:

```
connect( ({offline:{ online }}) => ({ online }) )(
    class OnlineWatcher {
        componentDidUpdate(props_old) {
            const { online } = this.props;
            const { online:online_old } = props_old;

            if (online && !online_old) {
                const { dispatch } = this.props;

                // dispatch some actions
            }
        }
        render = () => null
    }
)
```

Is there any better way? Somehow to do it in the reducer without creating a `null` component?
