### ISSUE TITLE
Use an Immutable store

### ISSUE THREAD

**Issue by okjulian** [redux-offline/redux-offline#78]
It would be great if this library could work with [Immutable.js](http://facebook.github.io/immutable-js/) stores, and I think it's a good idea to start talking about it in this issue.

I'm already using this library with an Immutable store and opened PR #54, but it only works with redux-offline v1.

To accept an Immutable store using my approach you only needed to set `config.immutable = true`. To achieve this, the only thing I needed was to teach redux-offline how to persist and rehydrate Immutable object. Luckily `redux-persist-immutable` makes this super easy, so I added it as a dependency.

Implementing this was straightforward: The key parts were using a different persistStore and autoRehydrate in [`index.js`](https://github.com/jevakallio/redux-offline/pull/54/files#diff-1fdf421c05c1140f6d71444ea2b27638), and converting the user's state to javascript in [`middleware.js`](https://github.com/jevakallio/redux-offline/pull/54/files#diff-f74cf7ea3fda676a7bafaf4bd8714ea4) so that redux-offline internals can still work with plain JS objects.

Please let me know of better ways to tackle this problem. Supporting Immutable stores would be great!

**Comment by Jimmy-CC** [comment]
If you only want to use Immutable object in the redux offline, passing transforms to persistOptions is a good enough solution. 

But it will be great if we can detect to use Immutable transit by passing options and works with immutable store.
```
import immutableTransform from 'redux-persist-transform-immutable'
import offlineConfig from 'redux-offline/lib/defaults'

const store = createStore(
  combineReducers(reducers),
  {},
  compose(
    applyMiddleware(middleware),
    offline({
      ...offlineConfig,
      persistOptions: {
        transforms: [immutableTransform()],
      },
    })
  )
)
```

**Comment by fabriziomoscon** [comment]
I created a PR #99 for this very same issue

**Comment by sorodrigo** [comment]
PR is now merged in master
