### ISSUE TITLE
Offline state slice not on root level

### ISSUE THREAD

**Issue by arieldf** [redux-offline/redux-offline#79]
Hi,

I would really like to test out this library and in order to do so I need to have the offline state slice in another location than root. As far as I can see I can not control the state locations in the config and I have tried to make changes to the source code but have not yet succeeded in making it work.

Anyone here that managed to make this work?

Best regards,
Ariel

**Comment by sorodrigo** [comment]
Hey @arieldf in the latest version `offlineStateLens` was introduced; this gives support to immutable root state stores, but also lets you choose the location of the offline reducer. Cheers!
