### ISSUE TITLE
How can I dispatch an action after commit?

### ISSUE THREAD

**Issue by dabit1** [redux-offline/redux-offline#80]
I need to dispatch an action after commit action is dispatched but I cant find the way. I think there is currently no option.. It is possible to pass function instead object on `commit` attribute? Do anybody have any idea? Thanks!

**Comment by Knight704** [comment]
Your commit action would be dispatched via standard redux flow, therefore I think you have (at a minimum) a chance to catch it inside middleware and dispatch any other actions.

Other option came to mind is using redux-thunk actions, but I don't actually know if it's possible to set thunk as an action for commit, because all metadata might have been persisted

Upd:
Also consider
[Pass Commit and Rollback actions to other middlewares](https://github.com/jevakallio/redux-offline/issues/77)

**Comment by dabit1** [comment]
Finally I created a middleware that dispatch an action after the commit or rollback. You can't set thunk as an action for commit because is not possible to persist it. I set the action that way:

```
   ...
   commit: {
            type: 'UPLOAD_ACTIVITY_SUCCESS',
            id,
            meta: {
              dispatch: {
                func: 'uploadPhotos',
                params: [id, 0]
              }
            }
     }
     ...
```
If somebody is interested in the middleware just say me something and I'll upload it in github.

Thanks!

**Comment by aislanmaia** [comment]
Hey @dabit1 , I was looking for something like that days ago. In my case, I just want to dispatch a toast popup that is working through dispatching redux action creators. Can you share your middleware ? Thanks!

**Comment by dabit1** [comment]
Of course! Right now Im in holidays wlthout access to any computer but in 1
week I gonna upload it to git :)

**Comment by dabit1** [comment]
Hi @aislanmaia !

Sorry for the late :S Hard work lately

I have just created a pull request of my middleware:

[https://github.com/redux-offline/redux-offline/pull/178](https://github.com/redux-offline/redux-offline/pull/178)

While it is reviewed you can add my fork to your dependencies:
[https://github.com/dabit1/redux-offline/tree/patch-4](https://github.com/dabit1/redux-offline/tree/patch-4)

I have also created a documentation :) (look for "What about if I want to dispatch a thunk after commit or rollback is dispatched?"):
[https://github.com/dabit1/redux-offline/blob/patch-4/README.md](https://github.com/dabit1/redux-offline/blob/patch-4/README.md)

I hope it help you!

Regards,

David Escalera

**Comment by isaaclem** [comment]
@dabit1 : May I know if there is any additional package i need to install?

I tried `import reduxOfflineThunkMiddleware from '@redux-offline/redux-offline/lib/thunk-middleware';` and it's hittting unable to resolve path issues
