### ISSUE TITLE
Store connection type "wifi" or "cell"

### ISSUE THREAD

**Issue by ShMcK** [redux-offline/redux-offline#84]
It would be helpful to know the connection type in redux offline when using react-native. This way certain heavy data transactions can be avoided, such as photo uploading.

[NetInfo](https://facebook.github.io/react-native/docs/netinfo.html) can be used to detect this status for both IOS and Android as "wifi" or "cell". The result could be stored as `offline.netInfo`.

I'd be happy to put in a PR ibce the details are all sorted.

**Comment by sorodrigo** [comment]
@j8seangel and I are already working on this, we have a solution and will submit it shortly. ;) @ShMcK

**Comment by sorodrigo** [comment]
@ShMcK see #86 👍
