### ISSUE TITLE
How to purge persist properly?

### ISSUE THREAD

**Issue by Noitidart** [redux-offline/redux-offline#88]
Hi all,
I am using redux-offline which puts an abstraction on redux-persist. I am trying to purge it via the offline config, but am not able to figure out how.

The only way I have been able to do it was by going into redux-offline source `node_modules/redux-offline/lib/index.js` and editing this line:
```
  if (config.persist) {
    persistor = config.persist(store, config.persistOptions, config.persistCallback);
  }
```
to:

```
   persistor = ....purge()
```

**Comment by fabriziomoscon** [comment]
I am able to purge the persisted store from my app with these lines

```js
import persist from 'redux-offline/lib/defaults/persist'
// ...
const persistOptions = {} // your persist options
// ...
persist(store, persistOptions).purge()
```

**Comment by Noitidart** [comment]
Thanks @fabriziomoscon ! However does this work after in unison with redux-offline? For example in the code below, where would I put the `.purge()`?

```
import { applyMiddleware, combineReducers, compose, createStore } from "redux";
import { offline, persistStore } from "redux-offline";
import offlineConfigDefault from "redux-offline/lib/defaults";
import thunk from "redux-thunk";

import * as reducers from "../reducers";

console.log('persistStore:', persistStore);
console.log('offlineConfigDefault:', offlineConfigDefault);

const reducer = combineReducers(reducers);
const store = createStore(
  reducer,
  undefined,
  compose(
    applyMiddleware(thunk),
    offline(
      {
        ...offlineConfigDefault,
        // rehydrate: false,
        persistOptions: {
          blacklist: ['form']
        }
      }
    )
  )
);

export default store
```

Would I put `persist(store, {}).purge()` right before the export?

**Comment by seclace** [comment]
@Noitidart in what use case are you want to purge your store? Right before the app running?

**Comment by fabriziomoscon** [comment]
@Noitidart use `purge` any time after `const store`

**Comment by sorodrigo** [comment]
@Noitidart This is an example of how I implemented it on another project. https://github.com/Vizzuality/forest-watcher/blob/develop/app/offline/index.js

**Comment by Noitidart** [comment]
Thanks @sorodrigo !

**Comment by SKempin** [comment]
Note the import should now be:
`import persist from '@redux-offline/redux-offline/lib/defaults/persist';
`
