### ISSUE TITLE
Add documentations on how network payload are handled upon completion on the 'commit' action

### ISSUE THREAD

**Issue by dharmawankenny** [redux-offline/redux-offline#89]
So i have been toying around with this beautiful piece of work for the past couple days and i couldn't wrap myself on how can i get network request data, turns out it is provided as a `payload` attribute on the `commit` action.

Since i am a newb on developing offline-first app, alongside with service worker and stuffs, this kind of thing can prove to be a bit frustrating, and after re-reading it on the docs, i realized that you mention it implicitly on the `A pessimist is never disappointed` part (on the code part), if my eyes were sharper i probably would found it out earlier but i was a bit confused as in the real action itself has a `payload` attribute too. Which is why i assume the `payload` in the `commit` action is the same as the initial action.

so maybe we can add a bit of docs on how network request are really handled? Not the part where how you execute the effect and how you stated that it could be configured, but on how you `complete` the effect after it has been fired and firing a `commit` action.

This is just a suggestion coming from an inexperienced developer though, so take it with a grain of salt. Cheers, great work by the way.

**Comment by sorodrigo** [comment]
Explained in https://github.com/redux-offline-team/redux-offline#a-pessimist-is-never-disappointed
