### ISSUE TITLE
Re-enable travis builds for the `redux-offline` org repo

### ISSUE THREAD

**Issue by bsouthga** [redux-offline/redux-offline#9]
Would someone with owner access to the repo mind heading over to https://travis-ci.org/ and enabling the builds so we can have PR checks? (not sure who that would be at this point).

**Comment by sorodrigo** [comment]
I'll set this up. I want to a little bit about the eslint config. IMHO its way to aggressive, whats your opinion to switching to another more common config such as Airbnb's one?

**Comment by bsouthga** [comment]
Switching to Airbnb's sounds good to me!

**Comment by bsouthga** [comment]
I'm also a fan of prettier https://github.com/prettier/prettier which could be nice for keeping things consistent and not worrying about formatting longer errors (could be used in conjunction with eslint)

**Comment by wacii** [comment]
Prettier was used sporadically in the original as well, it was just never enforced. I'm fine with another ESLint config.

**Comment by sorodrigo** [comment]
I'm closing this issue and opening another one about prettier so we don't forget
