### ISSUE TITLE
state.offline is undefined

### ISSUE THREAD

**Issue by Altiano** [redux-offline/redux-offline#92]
I'm using create-react-app to play with this library.
I just emit an action type `x` just to see if it will work or not and got this error
![image](https://user-images.githubusercontent.com/8316282/27759154-7a4c38f4-5e5b-11e7-8cbf-7afc14718438.png)

**Comment by dharmawankenny** [comment]
it is a known bug if you are using this library in conjunction with redux devtools, known possible fixes are #91 and #81 though it should be noted the bug itself was the incompatibility between redux offline and redux devtools that create some kind of race condition (#91 can explain it better).

**Comment by sorodrigo** [comment]
@Altiano @dharmawankenny this issue has now been fixed and its available in the latest version
