### ISSUE TITLE
Question on memory use

### ISSUE THREAD

**Issue by fungilation** [redux-offline/redux-offline#93]
With this library, Redux really is shaping up to be a kickass data store.

I'm researching different options for my client-heavy RN app. I see 3 options:

1. Redux with redux-offline. Particularly interesting for my needs as I'm also looking for fulltext search support, and I could get that with https://github.com/bvaughn/redux-search
2. Realm. I'm having bad issues with even getting it to build without crashing my app, and it doesn't support fulltext search other than simple %string% matching
3. Firebase. I don't really care about the realtime capabilities but it does have nice offline handling and data syncing for eventual data consistency, out of the box. My issue with it is cost, as I can have pretty much persist almost all data in RN mobile apps, for "free" without the niceties with the Cloud.

So with that background, my question really is on memory use. I see Redux with redux-offline as the best option for my app, but I worry about the nature of my app using local storage as the main database. Redux as a single tree store means loading everything from "disk" (flash) to memory. As users gather more and more data in the app, what is best practice for loading only part of the redux tree into memory, while leaving the whole tree on disk? Not possible with redux's architecture, so I shouldn't try relying on redux-offline as the sole data store for my client-heavy app?

**Comment by Jaikant** [comment]
@fungilation  I am new to react-native and am wondering if you got the answers to your question.
