### ISSUE TITLE
Can't get redux-offline working with next.js

### ISSUE THREAD

**Issue by harrisrobin** [redux-offline/redux-offline#94]
Hi,

I seem to be having trouble getting redux-offline to work with next.js.

Here is my current setup:
### store.js
```js
import { createStore, applyMiddleware, compose } from "redux"
import { offline } from "redux-offline"
import offlineConfig from "redux-offline/lib/defaults"
import immutableTransform from "redux-persist-transform-immutable"
import createSagaMiddleware, { END } from "redux-saga"

import createMiddleware from "./middleware"
import reducers, { initialState } from "../reducers"
import rootSaga from "../sagas"

export default (state = initialState) => {
  const saga = createSagaMiddleware() // saga middleware has to live here due to https://www.robinwieruch.de/nextjs-redux-saga/
  const middleware = compose(
    createMiddleware(saga),
    offline({
      ...offlineConfig,
      persistOptions: {
        transforms: [immutableTransform()],
      },
    }),
  )
  const store = createStore(reducers, state, middleware)
  // NOTE: you must attach `sagaTask` to the store
  store.sagaTask = saga.run(rootSaga)
  return store
}
```

### What is happening

1. Right now, I get the following error:
<img width="1292" alt="screenshot 2017-07-12 21 39 43" src="https://user-images.githubusercontent.com/3880008/28146800-a55b9cea-674a-11e7-9753-7a4bc1241f54.png">

```
Unexpected key "offline" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "ui", "authentication". Unexpected keys will be ignored.
```

2. in my component, I get the offline prop on the server but not on the client it is undefined:

#### Server
<img width="909" alt="screenshot 2017-07-12 21 40 42" src="https://user-images.githubusercontent.com/3880008/28146813-c470167e-674a-11e7-9f96-d7f4b2ff9749.png">

#### Client
<img width="1300" alt="screenshot 2017-07-12 21 40 58" src="https://user-images.githubusercontent.com/3880008/28146827-d0094c80-674a-11e7-8e7b-13d3e4e9a580.png">

Is there anything else I need to do to get redux-offline working properly with server side rendered apps? Any guidance is appreciated. 

Thank you for this awesome library!

EDIT: 
After finding this comment https://github.com/zeit/next.js/issues/861#issuecomment-280155417, it seems no one has managed to get redux-offline to work with next.js so I decided to let it go.

**Comment by jesper-bylund** [comment]
Just started looking into this myself. Anyone got this working?
Edit!
Found this thread: https://github.com/redux-offline/redux-offline/issues/197
